### ISSUE TITLE
Autocomplete the field by the URL

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#102]
Hi @bugy ,

It could be cool if the value in the field could be autocompleted by the values in the URL.

Example:
- http://my-super-script-server/index.html#My-super-script?hostname=1.2.3.4

Like that, if the script "My-super-script" have a field named "hostname", the value is autocompleted :)

**Comment by bugy** [comment]
Hi @csphoenix1, how is it supposed to create such URLs? Do you want to create them manually?

Just in case: do you know that you can specify default value for a parameter?

**Comment by csphoenix1** [comment]
Hi @bugy ,

Yes. I could create them manually. For example, I have a script to wake up my personnal computer et my wife computer (via WakeOnLan).
If I could pass the hostname parameter through the URL, I could create a desktop shortcut on my smartphone to wake on lan my computer or my wife's computer.
Exemple:
http://my-super-script-server/index.html#WakeOnLan?macadress=12:23:45:67:89:01
http://my-super-script-server/index.html#WakeOnLan?macadress=89:3E:45:67:89:01

The problem is may we have to encode the string value in Base64.

Do you think it is a good idea?

Yes I know about the default value, it's cool and I used it a lot :)

**Comment by bugy** [comment]
Hi @csphoenix1, I'm still thinking about this feature... On one hand I like the idea, but on the other hand I cannot find an easy way to implement and integrate it in the current UI. And I'm not sure, if this feature will be used often.

I'm thinking, that it could be some kind of presets (with the possibility to specify preset name in the URL).
Also I created issue #129 for having a list with mapped values, probably it would be useful in your case.

In any case, I would prefer to wait for additional 1-2 votes for this issue before starting the implementation for predefined values (from URLs, presets, or whatever).

**Comment by csphoenix1** [comment]
Hi @bugy,

I see the #129, and I understand your problem about the implementation.. Effectively, your solution with "specify preset name in the URL" seems to be a good alternative, and certainly more easy to implement.
But unfortunaly, this alternative can't do the job for all cases because we can't put we are limited to the values specified in the config file. So we have to think about all possible values a user can put.

So, about the possibility to implement this functionnality in the URL, i think about this solution : we can pass the values in the URL with a base64 encoded. Like that, we can pass absolutely anything in the URL without complication :)

What do you think about it?

Have a good day :)

**Comment by bugy** [comment]
Hi @csphoenix1, thanks for proposal and the ideas! My 2 major concerns are:
1. I'd like to keep URL tidy, so it could be shared easier. So there should be a way to get "shared link with parameters" on UI and when somebody opens the URL these values should be read and URL should be cleaned. In this case I don't think there is a need to have a base64 encoding
2. I'm not sure if an autocomplete from URL is the best way to solve this problem. In your case for me it looks more like presets (so, when you open a page, you can select this preset, without the need to keep an URL somewhere). These presets can be a part of URL as well (e.g. #WakeOnLan#my-pc).

I certanly understand, that your proposable is an much more flexible than presets. But on the other hand it's a bit harder to use, from my point of view.

At the same time, I just realized, that with my recent changes on client-side, this should be not so hard to implement. The only problem would be backward compatibility, if I decide to replace it one day.

**Comment by eltigre62** [comment]
Nice feature !

**Comment by bugy** [comment]
Done. The syntax is url ? parameters # script, e.g.:
http://my-super-script-server/index.html?hostname=1.2.3.4#My-super-script

This will replace ALL the parameters of a script with the values from the URL. If any parameter in the URL is missing, then it will be empty. (default script parameters are ignored)

Also, after replacing the parameters, page URL is cleaned (parameters are removed). This is intended to avoid any conflicts with other URL-based features

At the moment there is no way to create the parameterized URL automatically, so it should be done manually.

If you have any suggestions or requests for the feature, I'm completely open for it.

**Comment by eltigre62** [comment]
😀👌

**Comment by bugy** [comment]
Hi @csphoenix1 did you have a chance to test it? Does it work fine for you?

**Comment by bugy** [comment]
@eltigre62 @csphoenix1 
With 1.15 release (currently dev) I'm changing ULR format a bit
Now parameters should be in the end and script ULR is changed a bit also

Example of the new format:
http://localhost:8080/index.html#/Very%20parameterized?Simple%20Int=5&Required%20Text=hello

Sorry for the breaking changes. But I think current format makes much more sense and easier to support
