### ISSUE TITLE
RuntimeErrors on script execute

### ISSUE THREAD

**Issue by andres-v2** [bugy/script-server#105]
Trying to launch a simple "git push" script with bugy and the execution stalls with no output shown. If I insert any random text via the "your input" box the script launces normally and shows expected output, but does not finish script until page is reloaded.
Attached error messages from log.
[bugsy_error_log.txt](https://github.com/bugy/script-server/files/1864037/bugsy_error_log.txt)

Using python 3.5.3, tried with both latest Chrome and Firefox.

**Comment by bugy** [comment]
Hi Andres, thanks for the report. According to the logs, script execution works properly and input is accepted, but script output cannot be sent to the browser (server bug). I'll try to look later.
Are you using Windows?

**Comment by andres-v2** [comment]
Hi. Bugy is running in Debian 9 and browser in Windows 7. Thanks.

**Comment by bugy** [comment]
Hi @andres-v2, if you are using released version, could you try to replace src/server.py file with the attached one (unarchive it first)? 
[server.zip](https://github.com/bugy/script-server/files/1864885/server.zip)

Apparently, you are using tornado 5 (which was released not far ago for debian) and script-server doesn't work with it (I tried to do a quick fix in the attached file)

PS the project name is script-server (bugy is my nickname on github)

**Comment by andres-v2** [comment]
@bugy - yes, using tornado 5.0.1.  Good to know this is the cause of issue.
I tried replacing the server.py and got the following error when executing launcher.py:
Traceback (most recent call last):
  File "./launcher.py", line 11, in <module>
    server.main()
  File "src/server.py", line 681, in main
    result_files_folder = file_download_feature.get_result_files_folder(TEMP_FOLDER)
AttributeError: module 'features.file_download_feature' has no attribute 'get_result_files_folder'

**Comment by bugy** [comment]
Hi @andres-v2, I did the fix only for released version (from https://github.com/bugy/script-server/releases/tag/1.10-rc2) 
Could you try to use released script-server version? 
Download and unpack script-server.zip file, and then replace the server.py file there.

**Comment by andres-v2** [comment]
Hi @bugy , looks like that fixed it. I was using the latest version from git previously.
Thanks a lot, this is exactly what I needed.

**Comment by bugy** [comment]
Fixed in codebase as well
