### ISSUE TITLE
Long task is being killed

### ISSUE THREAD

**Issue by tristanlepachyderme** [bugy/script-server#111]
Hi !

Me again,
I think your script handler automatically kills a script if it doesn't display anything for a couple seconds.
Is it a normal behaviour and can we configure it ?
I'd like to run longer tasks that doesn't necessarily print stuff all the time.
And the execution_service doesn't log anything after '>> KILLED'  is displayed is the output.

Can you help ?

Thanks

**Comment by bugy** [comment]
Hi @tristanlepachyderme,
Script Execution is **killed** if a user is closing the page (or any other disconnect happens). I believe it's your case.
Script-server doesn't have any timeouts handling.
However, it could be, that if no output is provided for a couple of minutes, a browser can close WebSocket connection automatically. Thus script-server will kill execution on disconnect.

You can read about kill on disconnect here: https://github.com/bugy/script-server/issues/94
Also there is a parameter (for script config) - kill_on_disconnect, with which you can disable killing script on page close.

But anyway, it's a good finding - I need to add some kind of heartbeat to protect connection from autoclosing by browser. Thank you!

**Comment by tristanlepachyderme** [comment]
Hi,

Many thanks for you explanation,
Indeed kill_on_disconnect option of the script config do the job.
After, we need to go to the admin page to see the process output :)

Thanks !

**Comment by bugy** [comment]
Hi, thanks for the update and sorry for inconvenience.
Probably you could add some intermediate output to your script (e.g. printing a dot every minute) as a workaround.
I'll add heartbeat mechanism to the next released version.

**Comment by bugy** [comment]
Some more investigation info: 
It seems to be proxy (nginx) related - https://github.com/tornadoweb/tornado/issues/1070

**Comment by bugy** [comment]
Fixed. 
Will be in the next release
