### ISSUE TITLE
Add description for running script-server behind Apache reverse-proxy

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#113]
Moved from https://github.com/bugy/script-server/issues/82#issuecomment-394348126

> sorry for resurfacing this issue but I need a proper example for apache as I'm facing same issue.
> 
> can you post a working example with apache proxypass?

**Comment by bugy** [comment]
Hi @muzzol, I've created a config for apache as a reverse proxy. Please note, that I'm not professional Apache administator, so my solution can be not optimal/correct. But at least it works for me

The following apache mods should be installed:
- proxy
- proxy_http
- proxy_wstunnel
- rewrite
- headers

Add the following section inside VirtualHost:
```
        <Location /script-server/>
                Define ScriptServerUrl http://localhost:5000/

                ProxyPass ${ScriptServerUrl}
                ProxyPassReverse ${ScriptServerUrl}
                RequestHeader set Origin ${ScriptServerUrl}

                RewriteEngine On
                RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
                RewriteRule /(.*) ws:/$1 [P]
        </Location>
```
Update _ScriptServerUrl_ if needed

Also please note, that I will do some improvement to the config some days later to address the issue with user authentication behind proxy: https://github.com/bugy/script-server/issues/100#issuecomment-394425619. But for any released version, the config above should be fine

**Comment by muzzol** [comment]
thanks a lot for that quick response.
I'm really looking forward this project, so expect some feature requests and hard testing from my side
:)

**Comment by bugy** [comment]
Hi @muzzol, you are welcome!

> so expect some feature requests and hard testing from my side
Cool, I'm always glad to get new feature requests. Unfortunately I cannot guarantee quick solving of those. Depending on feature size it usually takes me 0.5 - 2 weeks for a new feature.

**Comment by muzzol** [comment]
Additional information regarding proxypass in apache: I had to activate some modules in order to get it working.
```

a2enmod proxy
a2enmod proxy_http
a2enmod proxy_wstunnel

```

pay special attention to the last one (wstunnel) as isn't usually activated by default.

**Comment by bugy** [comment]
Added to wiki: https://github.com/bugy/script-server/wiki/Reverse-Proxy-setup#apache
