### ISSUE TITLE
possibility to dynamically update option from result of another option

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#119]
question / suggestion 

use case:
running ansible:
1) choose playbook for example test1.yml (from ls on playbooks dir)
2)dynamically create  options from file of the same name but with _config (test1_config.json)

i guess all that needs react type of  ui updates.

may be you have some ideas

thanks

**Comment by bugy** [comment]
Hi @yosefy, I think it's a good idea, thank you for the proposal! 
Unfortunately it's not supported at the moment, and should be implemented. However I'm quite busy at the moment and won't be able to implement this feature in the nearest couple of weeks. But I'll work on it as soon as possible.

Probably as a temporal solution you could create select from option inside your script. I.e. the first parameter is selected in combo-box, but then during script execution there is an options selection like:

> 1. option A
> 2. option B
> :: Please enter your choice ::

**Comment by yosefy** [comment]
thanks!
question:
"but then during script execution there is an options selection like"
i don't understand how to do it...

lets say i have chosen from first option [install-java, install-some-other] -> install-java

now i need to choose the version[8,9,10]
but if i have chosen "install-some-other", i need to choose type[good, bad, ugly] 

say i have script that depending on first option generates next list
but how do i feed it to ui?

thanks

**Comment by bugy** [comment]
Hi @yosefy, please see bash script - https://gist.github.com/bugy/f61b493cfde75804889187bbbdc1a71c

Sample output:
```
bugy@bugy-pc:~/temp$ ./script.sh install-java
1) 8
2) 9
3) 10
Please enter your choice: 2
firstOption=install-java
secondOption=9

bugy@bugy-pc:~/temp$ ./script.sh install-
unsupported firstOption value install-

bugy@bugy-pc:~/temp$ ./script.sh install-some-other
1) good
2) bad
3) ugly
Please enter your choice: 2
firstOption=install-some-other
secondOption=bad
```

**Comment by bugy** [comment]
It won't be possible to feed it back to UI, back the script would be able to continue with both options (one recieved from the UI and another chosen by the script itself)

**Comment by yosefy** [comment]
thank you very much for your time.
it is working workaround!

i didn't know that it is possible to input data back to script

thanks again

**Comment by bugy** [comment]
I'd like to keep the issue open, since I'm going to implement this feature in future

**Comment by yosefy** [comment]
sorry i guess i have closed by mistake.
how it works in rundeck:

http://rundeck.org/2.0.0/manual/job-options.html#cascading-remote-options

the problem there is that you can't change the option name depending on another option value 

here is my pain :)  :
first option:
->choose an ansible playbook from ls  on playbooks directory.
2)then depending on the playbook, choose config file(i guess it can be done in current situation)
3)say i have chosen install-elasticserch.yml
4)now i need to choose es major version
5)now depending on the major version i need to choose from list of minor versions

or
-> choose an ansible playbook from ls  on playbooks directory.
playbook called add-users.yml (on the server)
1)option1 to  choose["user","group"]
2)option2 depending on that, provided list of "users" or "groups" from "http://provider.com/get-{{ option1.value}}"
(so second option also needs to have name "{{ option1.value}} name")


just sharing some thoughts as i am still not completely clear on the topic

**Comment by bugy** [comment]
Hi @yosefy, thanks for the description and rundeck references. It seems, that rundeck cascades only remote options, so some additional server will be required. 
I'm thinking about providing a possibility to calculate depending options via some script. For example, at the moment it's possible to specify values with a script:
```
...
parameters: [
{
"name": "option1",
"values": { "script": "ls /home/me/projects" } 
}]
```

I could extend it with a possibility to reference another parameter (like in rundeck) in the script, so your case could look like this in the configuration:
```
...
parameters: [
{
"name": "playbook",
"values": { "script": "ls /home/me/playbooks" } 
},
{
"name": "config",
"values": { "script": "cat /home/me/playbooks/${playbook}_config.yml | grep 'major'" } 
}]
```
Is it what would you expect? The script in the parameter values could be some shell/batch file as well, like: `"script": "my_script.sh ${playbook}`

By the way, out of curiosity, what did you choose script-server over rundeck? I thought that for advanced use-cases rundeck is a better option.

**Comment by yosefy** [comment]
amm may be to use some include directive?
like:
```
parameters: [
{
"name": "playbook",
"values": { "script": "ls /home/me/playbooks" } 
},
{
  "name": "include_config",
  "type": "**include**",
  "values": "/etc/${playbook}_config.json"
}]
```

and that include will "add" parameters we need for that playbook| script (if we need it),
so the playbook_config.json file will be just like:

```
    {
      "name": "Required Text",
      "param": "-p1",
      "description": "Parameter One",
      "required": true,
      "default": "Some default value"
    },
    {
      "name": "Simple Int",
      "param": "-p2",
      "description": "Parameter Two",
      "type": "int"
    }
```
another thing
if a parameter has ${something} in its valaue, it will wait for parameter it depends on

for a second :)
i like the technologies you have chosen much better and clear

thanks

**Comment by bugy** [comment]
Hi @yosefy, thanks for clarification. So, as far as I understand, each playbook configuration has completely own parameters (their count and names), is it correct? And you would like to create a separate json file for each of the playbooks manually?

**Comment by yosefy** [comment]
yep and most of them will not have one.
just those who need it (with versions and such and more complicated like creating a virutal instance for example
where you need to add cpus number, memory amount number of disks and their size)

thanks

**Comment by bugy** [comment]
Cool, thanks! I guess now I got it: dynamically include parameters section, based on another parameter value. So parameter fileds will be added and removed from the GUI, based on user choice.

Before that I thought, that you were talking about 2 dependent list parameters. So both parameters are shown to the user always, but one of them is filled only based on a selected value in another list.

**Comment by yosefy** [comment]
amm i think i mean both :)

**Comment by yosefy** [comment]
> dynamically include parameters section
may be parameters file could be better?
so parameter files can be saved together with specific script and referenced by same name as script like you mentioned.

> Before that I thought, that you were talking about 2 dependent list parameters. So both parameters are shown to the user always, but one of them is filled only based on a selected value in another list.

may be could be some tag saying show always or show only when "parrent" chosen

**Comment by bugy** [comment]
@yosefy, with include of parameter section I meant your proposal about files

> may be could be some tag saying show always or show only when "parrent" chosen
To be honest I don't like "flickering" GUI, so I would prefer to show parameters always (if they are known).
For "included" parameters they will be shown and hidden dynamically, but just because I don't see any alternatives.

This is my current understanding of the feature:
1. Add possibility to _include_ json files with parameters. This include can be static or depend on other parameter(s). If another parameter is not filled by a user, then _include_ should be ignored
2. Add possibility to refer to parameter in "script" tag of other list parameters

**Comment by yosefy** [comment]
Yes exactly. Thanks

**Comment by bugy** [comment]
Finally I've finished "2. Add possibility to refer to parameter in "script" tag of other list parameters"

The part with "include" is still pending. I'll move it to a separate issue and come back to it after closing some other smaller tasks

**Comment by yosefy** [comment]
nice thanks  a lot
