### ISSUE TITLE
Add a requirements file

### ISSUE THREAD

**Issue by olinox14** [bugy/script-server#120]
Hi! Would'nt it be more readable with a requirement.txt file?

**Comment by bugy** [comment]
Hi @olinox14, thank you for the suggestion. I think you are right, adding requirements.txt would be useful.
But to be honest I don't understand what do you mean with "more readable".

And script-server has only 1.5 mandatory dependencies (tornado and typing (which is default for python >= 3.5).
All other dependencies (email, auth, etc.) are optional, depending on your settings.

**Comment by olinox14** [comment]
Thank you btw, that's a great project: simple and efficient just as I like!

**Comment by bugy** [comment]
Hi @olinox14, I'm glad you liked it :)
