### ISSUE TITLE
Multiple selection list

### ISSUE THREAD

**Issue by quimm2003** [bugy/script-server#121]
Hi there!

Thanks for your awesome work!

I guess it would be useful a list type to create a select multiple element, which passes a list with the selections to the script's parameter.

For example, I use a script to issue a "git status --porcelain" to get a list of modified and untracked files. I want some of this files to be processed by the script.

Thanks.

**Comment by bugy** [comment]
Hi @quimm2003, thanks for the new proposal. Sounds reasonable.
How would you expect these multiple values to be passed to your script? As comma-separated values or as positional arguments?
e.g.
my_script.sh --files file1.txt,file2.txt
OR
my_script.sh --files file1.txt file2.txt

Or may be in a completely different way?

**Comment by quimm2003** [comment]
Hi @bugy,

my script expects the file paths to be passed as positional arguments. e.g.: my_script [options] file1 file2. Nevertheless, it will be easy to adapt my script to any of your proposals.

**Comment by quimm2003** [comment]
Thank you very much @bugy! No, it is not bad... I can still launch the script at command line... ;-)

**Comment by quimm2003** [comment]
Works like a charm! Thank you very much @bugy!
