### ISSUE TITLE
If opening a script page fails with error, then log panel height is broken

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#122]
If opening a script (selecting from the selection panel on the left side) fails with an error, then log panel in other scripts are not expanded to the full height anymore and adjust to the log content

Steps to reproduce:
1. Load script-server page with at least 2 scripts
2. Rename any script in the config file
3. Try to select the script in the UI (an error should be shown)
4. Select another script (with correct name)
5. Execute it

Actual result: height of the log panel adjusts to the content
Expected result: height of the log panel fills all the page height (like before the error)

**Comment by muzzol** [comment]
I've just tried a new installation, did a 

`git clone https://github.com/bugy/script-server.git`

and a 

`tools/init.py --dev`

and I get this error:

```
2018-07-17 11:42:18,989 [migrations.INFO] Applying migration add_execution_info_to_log_files
Traceback (most recent call last):
  File "/opt/script-server/launcher.py", line 11, in <module>
    main.main()
  File "src/main.py", line 53, in main
    migrations.migrate.migrate(TEMP_FOLDER, CONFIG_FOLDER)
  File "src/migrations/migrate.py", line 261, in migrate
    migration_descriptor.callable()
  File "src/migrations/migrate.py", line 90, in __migrate_old_files
    for file in os.listdir(output_folder)
FileNotFoundError: [Errno 2] No such file or directory: 'logs/processes'
```

can be related to this bug?
are you reworking log system?

**Comment by bugy** [comment]
Hi @muzzol, thanks for reporting it. Fixed!
(it was a regression issue, when I added better user identification)

**Comment by muzzol** [comment]
wow! that was fast!
:)

**Comment by muzzol** [comment]
Now I get this error and execution animation (rotating circle) is shown indefinitely:

```
2018-07-17 12:30:39,148 [tornado.access.INFO] 200 POST /scripts/execution/stop/4 (172.16.236.12) 0.79ms
2018-07-17 12:30:39,183 [script_server.observable.ERROR] Could not notify on_close, observer <react.observable._CloseSubscriber object at 0x7f75c98fe0f0>
Traceback (most recent call last):
  File "src/react/observable.py", line 67, in _fire_on_close
    observer.on_close()
  File "src/react/observable.py", line 279, in on_close
    self._callback(*self._args)
  File "src/web/server.py", line 248, in finished
    connection.ping_callback.stop()
AttributeError: 'WebSocketProtocol13' object has no attribute 'ping_callback'



```

do you want me to open a new issue on this or do you think is related to changes from this bug?

**Comment by bugy** [comment]
Actually I would prefer a separate bug. This particular task is for extremely minor visualization issue

Regarding your issue - could you tell me please, which tornado (full) version are you using? For me 4.5.1 and 5.0.1 works fine

**Comment by muzzol** [comment]
```
# dpkg -l | grep tornado
ii  python3-tornado                   4.4.3-1                        amd64        scalable, non-blocking web server and tools - Python 3 package

```

**Comment by bugy** [comment]
Thanks,  I'll have a look in one hour
But anyway this problem shouldn't be critical

**Comment by muzzol** [comment]
ok, I've tested on a Debian Buster with tornado version 5 and it works, so it's definitely related to old version.

I didn't realize that on Stretch tornado was that old.

you don't need to waste time on this.

**Comment by bugy** [comment]
Hi @muzzol, thanks for letting me know! 
I'll have a look anyway, but later then
