### ISSUE TITLE
Add possibility to dynamically include script parameter section

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#133]
There should be a possibility to add an "include" section to a script configuration, which would add/fill parameters configuration from another file. 
This "include" section can depend on current parameter values, so it will be loaded dynamically while user selects values on UI

There are 2 use cases behind:
1. Sharing parameters in different configurations
2. Depending on some parameter, we could include different corresponding additional parameters

For more details and reasoning please read comments in #119

**Comment by yosefy** [comment]
thanks a lot!

**Comment by yosefy** [comment]
sorry just a question, so i cant use values from included file in script?
so how to use it?

**Comment by bugy** [comment]
Hi, what do you mean?

**Comment by yosefy** [comment]
i dont see values form included when echo $@

**Comment by bugy** [comment]
That's extremely strange. Do you see these values on UI? And in the log, before script is called? (or after, in the admin page)

**Comment by yosefy** [comment]
![image](https://user-images.githubusercontent.com/12940013/53340099-c9d5c200-3910-11e9-804c-544ae15266e6.png)



{
  "hidden": false,
  "parameters": [
    {
      "name": "inc_param1",
      "type": "list",
      "values": [
              "aaa",
              "bbb"
                ]
    },
    {
      "name": "inc_param2",
      "no_value": "true",
      "param": "--inc2"
    }
  ]
}

**Comment by bugy** [comment]
Ok, apparently it doesn't work at all :( Will fix it

**Comment by yosefy** [comment]
@bugy , do you have some estimation of fixing  it
blocking from putting in prod :)

thanks

**Comment by bugy** [comment]
Hi, I'm working on another ticket at the moment (#184), and would need 2-3 days there probably.
The fix here will take ~1 day.

So if it's urgent for you, I could work on it today, otherwise estimation is Friday

**Comment by yosefy** [comment]
wow if it possible, would be really helpful
as i am actually waiting for it now to continue working with script-server

thanks

**Comment by bugy** [comment]
Ok, agreed

**Comment by bugy** [comment]
Fixed. Should be available in the latest stable release (1.13.2) and dev

**Comment by yosefy** [comment]
i don't know if it is known but default values don't work in included
scripts
not a big problem just updating
the rest work beautifully

thanks

**Comment by bugy** [comment]
Thanks for double-checking and reporting the issue with default values. I moved it to a separate ticket #201

**Comment by kbza** [comment]
Hello there!
Is there any way of including more than one external included file for script? thinking of one of the following:
- Multiple include directives (I think it only works the latest)
- The possibility of an include directive with array as a type.
- Another include on the included file.

I'm trying to figure out a way of having configuration files that will be the same across installations, some specific to each one and others specific to the servers.
Is there any way of achiving this in the current version? will you consider implementing something like this in the future?

Thanks in advance.

**Comment by bugy** [comment]
Hi @kbza, I'm afraid it's not possible at the moment, but would be more or less straightforward to implement. Do you want to try and submit a PR?

**Comment by kbza** [comment]
I don't think I'm confident enough... Many years as a sysadmin only making just some bash scripts, so my coding skills are a bit rusty. Also, I've never done any serious project with python. Nonetheless, I'm gonna give it a try, but I would like you to consider a "plan B" :P.

Anyway, which one of the two last options do you think is the best? I'm thinking more of a "chain" of includes as a better way of structuring... but, on the other hand, the array way could work with multiselect or script/command that finds more than one config file matching a pattern ("script": "ls /path/to/web*_server.json" -> will include web1_server.json, web2_server.json... )

**Comment by bugy** [comment]
I thought about replacing a single string with an array of strings, but i
don't fully know your use case and it might be not enough
How dynamic are these values?

kbza <notifications@github.com> schrieb am Mo., 31. Aug. 2020, 19:45:

**Comment by kbza** [comment]
This is more or less what I have atm:
```
{
  "name": "Param Test",
  "script_path": "./scripts/paramTest.sh",
  "include": "./platform_files/${Server Select}",
  "parameters": [
    {
      "name": "Server Type",
      "type": "multiselect",
      "values": [ "app", "db", "web", "lts" ],
      "separator": "|"
    },
    {
      "name": "Server Select",
      "type": "multiselect",
      "values": { "script": "find ./platform_files/ -regex '.*[${Server Type}]+[0-9]+_server.json' -type f -printf \"%f\n\" "}
    }
  ]
}

```
but only accepts one include file. So something like:

```
{
  "name": "Param Test",
  "script_path": "./scripts/paramTest.sh",
  "include": [ ${Server Select} ]
  "parameters": [
    {
      "name": "Server Type",
      "type": "multiselect",
      "values": [ "app", "db", "web", "lts" ],
      "separator": "|"
    },
    {
      "name": "Server Select",
      "type": "multiselect",
      "values": { "script": "find ./platform_files/ -regex '.*[${Server Type}]+[0-9]+_server.json' -type f -printf \" \"%f\"\n\" "}
      "separator": ","
    }
  ]
}

```
Could work with arrays.

**Comment by bugy** [comment]
Ah, i see, but for this one, i think, there is no need to change syntax in
the configuration file
The value of multiselect parameter is already an array, so we can just pick
every element from the array and include it
What do you think?

kbza <notifications@github.com> schrieb am Mo., 31. Aug. 2020, 21:16:

**Comment by kbza** [comment]
Exactly, that will be possible when include directive accepts an array of values/files. I think this is the easiest aproach, though atm, I have no clue how to do it.
