### ISSUE TITLE
Allow bash operators (|, &&, ||) in script section of for "values" fields

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#139]
Hi,

I discover a little problem :)

If we put a "pipe" in the script command, it does not work.

Eg.:
`      "values": {
        "script": "ps aux | grep foo"
      }
`

I don't have logs or anything else, but I think it can be easily reproductible.

Regards,

**Comment by bugy** [comment]
Hi @csphoenix1, thanks for reporting.
It's kind of known/expected issue for protection from script injection, but I guess the protection is not needed in such case. However in case of template variables (e.g. `ps ${var1} | grep foo`) this should be considered.

**Comment by csphoenix1** [comment]
Hi @bugy ,

Oh I understand what you mean. In this case, maybe we can add a feature to disable the script injection protection for a specific script ?

**Comment by bugy** [comment]
Hi @csphoenix1, I'll have a look what can be done. As a workaround you can put this command in a separate script and execute it instead :)

**Comment by csphoenix1** [comment]
Hi @bugy, yes I it's exactly what I do :)

Happy Christmas :)

**Comment by bugy** [comment]
Done. Now by default bash operators are enabled, if there are no variables (other parameters or auth variables)
This behavior can be set explicitly by using an additional `shell` flag (even for scripts with variables):
```
      "values": {
        "script": "ls /var | grep -v lock | grep -v backups",
        "shell": true
      }
```

**Comment by yosefy** [comment]
nice thanks!
