### ISSUE TITLE
Output files : issue if there is a space in the filename

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#140]
Hi !

I discover another problem.

In a script conf., If we put an output files with a space in the filename, the file is offered for download, but the name in truncated juste before the space (ie. : the filename is not the full filename).

`  "output_files": [
    "~/$$$filename - With IP and Mac address.txt"
  ]`

Regards,

**Comment by bugy** [comment]
Hi @csphoenix1, do you have any update on it?
