### ISSUE TITLE
Add possibility to specify a result of a command as value (the same thing than for list values)

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#141]
Hi !

Is it possible to add the possibility to specify a result of a command as the value of a parameter ?

Like that but not only for a list values.

`{
      "name": "Reload the current profile",
      "value": {
        "script": "cat /tmp/current_profile.txt"
      }
}`

**Comment by bugy** [comment]
Hi @csphoenix1, do you mean for constants and default values?

**Comment by csphoenix1** [comment]
Hi @bugy 

Yes for constant and default value, exactly.

**Comment by bugy** [comment]
Done. Usage example:
```
      "default": {
        "script": "shuf -i 10000-99999 -n 1"
      }
```
