### ISSUE TITLE
Put the script title in the page title

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#142]
Hi !

Does it is possible to add the script title in the Web page title ?

Example:
Instead of "Super Script Server"
We could have "Generate list of my movies - Super Script Server".

Like that, it's more easy to find the right tab if we open a lot of tabs in the browser :)

**Comment by bugy** [comment]
Hi @csphoenix1, nice idea. I'll add it as a suffix by default, but make configurable to make as a prefix

**Comment by csphoenix1** [comment]
Ok, thank you sir :)

**Comment by bugy** [comment]
Done. 

In the end, I implemented it as a prefix (like in youtube), with the possibility to disable it completely with `enable_script_titles` option in conf.json. By default, script titles are enabled
