### ISSUE TITLE
Browser slowed down when lot of residual text in the console

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#143]
Hi !

When I launch a script wich generate a lot of text (in verbose mode for example), the browser is slowed down.

I saw this issue closed (#10).
So maybe in more we can add a button to flush the current console?

**Comment by bugy** [comment]
Hi @csphoenix1, how much lines of output (or bytes) do you have? I checked ~10-50 thousands lines on my PC, and browser performance was ok. Though the server itself was a bit slow.

I have plans to refactor browser console to reduce currently shown text and load it dynamically on scrolling. But it's not coming this year :(

**Comment by csphoenix1** [comment]
Euh I don't known, but maybe one of my computer is slow.
Maybe I have thousands line too, like you.
But if you already plan to "refactor browser console to reduce currently shown text and load it dynamically on scrolling", it will certainly solve this problem :)

**Comment by bugy** [comment]
I made some performance improvements there. @csphoenix1 could you check please, if it works better for you now?
