### ISSUE TITLE
Add a preffix in the title webpage when a script is running

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#144]
Hi !

When a script is running, maybe we can add a preffix in the webpage:

Instead of: "Script Server"
We can have: "[RUN] Script Server"

In order to know if there is a least one script which is running?

**Comment by bugy** [comment]
Hi @csphoenix1, good idea. But I would suggest to change favicon instead (shown some green indicator on it, for example). What do you think?

**Comment by csphoenix1** [comment]
Yes your idea (favicon) is better :) OK for that :)

**Comment by bugy** [comment]
Done. Now, for executing scripts a green circle will be shown in a favicon. If all scripts are finished, then a tick is shown
