### ISSUE TITLE
Multi-instance for the same script

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#145]
Hi !

Before this feature #94, if we wanted to launch a multiple instance of this current script which is running, we have just to open a new tab.
Now, we can't because we going back to the running instance.

Going back to the running instance is really really cool ! But maybe we can add an improvement to allow the run of multiple instances of a same script?
I think it is not easy, but that could be cool too :)

**Comment by bugy** [comment]
Ye, this is definitely needed, I was waiting for this ticket (if anybody would need such functionality). 
The hardest part of this issue is to make it in a user-friendly way. I'll think about it

**Comment by bugy** [comment]
Hi @csphoenix1, good idea, I had similar idea also :) But  I'm thinking about putting the "tabs" to the right of script name, to save some vertical space

**Comment by csphoenix1** [comment]
Hi @bugy, cool :)
About the position, I'm afraid there is a probleme if the script name is long (on my server, I have some script which are a little long ^^).
A tab row is not very very high, maybe 20px? I'm not very good in design but I believe in you, if you think it's better, I'm okey with you :)

**Comment by bugy** [comment]
I hope anybody if following this thread :) I'm struggling a little bit with design, so far I came up with some ideas (screenshot attached). Any preferences here? :)
![script-server title](https://user-images.githubusercontent.com/1275813/81957741-50a5b600-960d-11ea-89e0-3eacbd0f16e5.png)

**Comment by antonellocaroli** [comment]
Hi,

In my system, that wouldn't be a function that would be used much.

But I probably like the last one...

**Comment by antonellocaroli** [comment]
or maybe this one

![image](https://user-images.githubusercontent.com/11161093/82028953-8e9aec80-9696-11ea-915f-7ad7d14e9988.png)

**Comment by bugy** [comment]
Hi @antonellocaroli thanks for the feedback!

**Comment by csphoenix1** [comment]
Hi @Bugy,

I love have lot information without additionnal click, and I love see the informations easily, so the one for me is a mix between 2 of your purposes.

![image](https://user-images.githubusercontent.com/12010592/82091185-347e4380-96f7-11ea-80df-db90cd2fbc04.png)

The reasons :
- We can have the full list and the state of each instances without additionnal clicks : all instance are displayed with their states.
- We can see very easily the thread on which one we are (underlined, in black and bold), and the other are in grey, and in a smaller size.
- We can add very fastly (and with few mouse movements) a new instance (just after click on the runner) thanks to the button which is near on the left).

:)

Good job in all cases :)

**Comment by bugy** [comment]
Done :) Feel free to get latest dev version and test it :)

**Comment by csphoenix1** [comment]
Hi Bugy !

I've just test the multi instance feature and... it's really cool ! Well done !

If i had to say negative things I will say that :

- I understand that the number of instance available depend of the free space at the right of the script title. If the script name/title is long, the number of instances will decrease (until only one instance available :'( ). A workaround could be let the user have an unlimited instances available by adding rows bellow. If the user need only few instances, all could be in the title row. And if it need more instances, row bellow will appear (it will be bad because it will reduce the size of the console bellow, but it the price to paid if he want more instances :) ). What do you think about it?

- When an instance is finished, if we move to another script and going back to the first one, the instance will autoclose. So, for example, if I want to compare the output of different instances launched previsouly, I can't because the instances were autoclosed. Maybe let the user to close himself the instances it has open ? Or add a global configuration variable to let the user the mode he want "autoclose the instance" or not ?

Despite of these two things, all is really cool and seem to work very well.

Very good job sir :)

**Comment by csphoenix1** [comment]
Hi Bugy,

I'm continuing to test the multi instance feature and I discover a problem.
When I add a new instance by clicking the + button, the default value of a variable (specified is the json script configuration file) is not present for the new instance. But is present for the default instance.
I think it's not normal.
It's a minor problem in all cases :)

**Comment by bugy** [comment]
Hi @csphoenix1 thanks for reporting this bug. Unfortunately, I missed your message and noticed this broken behaviour only now :) fixed

**Comment by bugy** [comment]
Regarding your 2 other comments, I created the separate tickets for future:
- Having more than 1 row: https://github.com/bugy/script-server/issues/328
- Manual tab close: https://github.com/bugy/script-server/issues/329, please check my comment there

**Comment by bugy** [comment]
Fixed too aggressive closing of non-viewed tabs or closing active tab on click
