### ISSUE TITLE
Force kill script is the first click on stop doesn't stop the script

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#146]
Hi !

Is it possible to add the possibility to force kill a script if the first try of stopping the script doesn't work?

Actualy, I think it's a SIGINT or SIGTERM which is sent.
Maybe, on the second time the user click on STOP, we can send a SIGKILL ?

Use case: recently, I develop a python script which prompt a message box is there is a problem.
The problem is through Script-Server, the message box was not displayed. So the script was stuck. So I click on STOP but the script doesn't stop.
I think it could be cool if on the force click on STOP, the button change to "KILL" and if I click on it, it kill the script? :)

**Comment by bugy** [comment]
Hi @csphoenix1, nice and simple idea and it should be pretty easy to implement (I even have API for it and it's even called when you log out).
But I would rather make it with a timer (let say 5 sec) to give a script a chance to stop gracefully :) I.e. you press stop, then a button disables for 5 sec and after 5 sec you can kill it.

**Comment by csphoenix1** [comment]
Hi @bugy,
About the timer, if we are in a test period where we test a script which we known an INT will not work and we will do a KILL each time during this test period, a timer of 5s can be boring.
But I understand that if a user click multiple times in STOP, he will click on KILL by mistake.
So... maybe we can simply add a KILL button in more of STOP button. Like that, no mistake is possible. And we can choose always STOP or KILL the process :)

**Comment by bugy** [comment]
For not I decided to go with a timer. Let's see how it goes, and if it will be too boring or annoying or whatever, we come back to it again.
