### ISSUE TITLE
Runner configuration : list files in directory

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#147]
Hi !

On linux, to add a dynamic variable which list the file in a directory, we can do something like that:

     {
      "name": "Command-based list",
      "param": "--var_file",
      "description": "List parameter 2",
      "type": "list",
      "values": {
        "script": "ls /var"
      }
    },

But on Windows, what we can use?

Maybe we can create a specific type of variable and also a feature to pass in argument:
- the filename with or without extension
- the fullpath with or without extension

What do yo think about it?

**Comment by bugy** [comment]
Hi @csphoenix1, isn't `dir` command work on windows?
But you are right, I think making explicit parameter type for it would make sense. There is another similar issue for it: https://github.com/bugy/script-server/issues/137

I think it would make sense to merge them

**Comment by csphoenix1** [comment]
Hi @bugy ,

Yes `dir` exist, but unfortunaly, it's like `ls -l`: there is some information which are not needed like for example the date.

**Comment by bugy** [comment]
Closing the ticket. It will be considered in #137 implementation
