### ISSUE TITLE
How to install python packages doc.

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#149]
Hello, first of all thanks for great project! This was something very helpful for me!
However I've totally messed up my python installation.
I guess I should've install required packages with
`pip3 install -r requirements.txt` but it returns:
```
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```
After reinstalling something here and there, I can successfully run the launcher with `python3 launcher.py` command. However when I put into systemd service, it returns 
```
Started Script Server.
Traceback (most recent call last):
File "/home/rnmkr/server/launcher.py", line 9, in <module>
import main
File "src/main.py", line 19, in <module>
from web import server
File "src/web/server.py", line 11, in <module>
import tornado.concurrent
ImportError: No module named 'tornado'
```

I've never liked this python and python3, pip , pip3 stuff. So please guide me through installation process :)

**Comment by bugy** [comment]
Hi, could you try to run
pip3 install tornado
?

**Comment by shinebayar-g** [comment]
Yes, it's already installed. But as far as i know if i try to install it second time it returns something like requirements already set .. etc yea? but it doesn't. Everytime I run this command it installs over and over again.

**Comment by bugy** [comment]
Hi, it doesn't look good... Python installation looks broken
Which distro are you using?
On debian/ubuntu you can also try
sudo apt install python3-tornado

Otherwise I would recommend to reinstall python or use pyenv

**Comment by shinebayar-g** [comment]
It's ubuntu 16.04 LTS with latest updates, yea it's broken asf.
I'm trying to install it on virtual env. This is what I did so far
1. Installed pip3 using `sudo apt-get install python3-pip` command.
2. Installed virtualenv with pip3 using `pip3 install virtualenv`.
3. However when I type `virtualenv .env` it says virtualenv command not found...

**Comment by bugy** [comment]
Well, pip3 cannot install tornado, i wouldnt trust it now :)

I can send you pyenv setupp instructions once i get to PC in a couple of hours

**Comment by shinebayar-g** [comment]
Well thanks, in the meantime I'm making some progress. I'll keep you updated.

**Comment by shinebayar-g** [comment]
Yes! I got it working. Here is steps:


1. Install python virtualenv using
`sudo apt-get install python-virtualenv`
2. Create virtualenv for python3 using
`virtualenv -p python3 env`
3. Enter to virtual env
`source env/bin/activate`
4. Check python version using
`python -V`
5. Download latest release
`wget https://github.com/bugy/script-server/releases/download/1.12.0/script-server.zip`
6. Extract zip contents
`unzip script-server.zip -d script-server` (If unzip command not found, install unzip with `sudo apt-get install unzip`
7. Go to extracted folder and run
`cd script-server`
`python launcher.py`

Hope this helps someone, mention it on readme or somewhere else if you want.
When I deploy python project I always encounter some version error, always. So virtualenv is best option, even I don't have any other python project.

**Comment by bugy** [comment]
Done, created a wiki page for the guide + added a link to it in the read.me
Thank you @shinebayar-g !

**Comment by bugy** [comment]
Hi @shinebayar-g thanks for checking it. That's weird, I'll double check my guide again.
Do you know which python version is installed?

**Comment by shinebayar-g** [comment]
For me both virtual env's python -V reports 3.6.7
I think the difference is I installed `sudo apt-get install python-virtualenv` and created virtual env with `virtualenv -p python3 env` and wiki says
`sudo apt install python3-venv` , `python3 -m venv any/path/envname` those are only differences.

**Comment by bugy** [comment]
Yep, these are the differences, but as far as I understood this is the recommended way to install virtualenvs. If I won't find the reason of failure, I'l switch to you version

**Comment by shinebayar-g** [comment]
I see, I'd like to know the reason too. :)

**Comment by shinebayar-g** [comment]
Oh by the way, is it possible to change listening port when using systemd service?

**Comment by bugy** [comment]
You can use this server configuration parameter:
https://github.com/bugy/script-server/wiki/Server-configuration#port

If you want to have 2 configurations, please check new option (dev version only at the moment):
https://github.com/bugy/script-server/pull/135

**Comment by shinebayar-g** [comment]
> Today, I decided to use dev release instead of stable (which looks like quite old) and I followed your [instruction](https://github.com/bugy/script-server/wiki/Installing-on-virtualenv-(linux)).
> However on step 8 it gives error:
> 
> ```
> pip install -r requirements.txt
> Collecting typing (from -r requirements.txt (line 1))
>   Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
> Collecting tornado<6 (from -r requirements.txt (line 2))
>   Downloading https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz (516kB)
>     100% |████████████████████████████████| 522kB 2.3MB/s 
> Building wheels for collected packages: tornado
>   Running setup.py bdist_wheel for tornado ... error
>   Complete output from command /home/shinee/sites/script-server/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9m5zqpq7/tornado/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8sqzva6bpip-wheel- --python-tag cp36:
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: -c --help [cmd1 cmd2 ...]
>      or: -c --help-commands
>      or: -c cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for tornado
>   Running setup.py clean for tornado
> Failed to build tornado
> Installing collected packages: typing, tornado
>   Running setup.py install for tornado ... done
> Successfully installed tornado-5.1.1 typing-3.6.6
> ```
> 
> Looks like you modified my steps little bit. However if I try my steps there is no error. (make sure to clear ~/.cache/pip folder when reproducing this).

If anyone getting this error update your pip version or install wheel package.
src: https://github.com/tornadoweb/tornado/issues/1602

`pip install --upgrade pip` or `pip install -U wheel`
