### ISSUE TITLE
There is no way to go back to home page.

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#150]
Hi, as title says there is no way to go back to home page. Reason why we need is:
If I execute one script it stays as check marked and doesn't refresh. So there is a way to refresh to get rid out of this check mark. And there is no button to click to refresh or go back to home page. So I'd like to add href link on **Script server** word. PRs are welcome?

![image](https://user-images.githubusercontent.com/3091558/50213722-66cc2a00-03b9-11e9-8040-aeb026baba8f.png)

**Comment by bugy** [comment]
Hi @shinebayar-g, just for better understanding: why do you want to get rid of this mark? You can execute the same script again without any problems. It is just showing that the script is finished until "any" further action (see below)

Two ways to get rid of it: 
1. Refresh the page
2. Navigate to another script (which you don't have according to the screenshot)

But PRs are always welcome :) You can make "Script server" text in the left upper corder a link (but please keep styles: black font and no underlines)

**Comment by shinebayar-g** [comment]
Ye, I thought If I add more scripts check mark would disappear if I select between scripts. Noted.

**Comment by bugy** [comment]
:) But why don't you like this check mark?

**Comment by shinebayar-g** [comment]
I don't know it just feels off, I'd provide more feedback after I get used to in few days.

**Comment by bugy** [comment]
I see. But navigation to a home screen itself is not needed for you, right?

**Comment by bugy** [comment]
I think the link to a homepage is ok for almost any website :)

The problem for me, is that I would like to fix the root cause why anybody would want to go to the homepage. I'm completely fine for this link to exist, but I would like that people wouldn't need to use it

Regarding your usecase, I think that some kind of "Reset" button would be helpful. It could clean the check mark and all parameter values for the currently open script. Do I understand correctly?

**Comment by shinebayar-g** [comment]
Umm, that could be useful too! Reload or refresh button that doesn't perform full page reload, but reloads certain element would be cool.

**Comment by bugy** [comment]
Now Script server title is clickable and leads to a "home page" (black page basically)
In future, I'm planning to support #84 with a possibility to start a new script from scratch (i.e. reset current parameters)
