### ISSUE TITLE
403: Forbidden when accessing admin page

### ISSUE THREAD

**Issue by Smadger1** [bugy/script-server#154]
Hello,

Whenever I try to access the administrator panel I get a 403: Forbidden error?
![image](https://user-images.githubusercontent.com/22797936/50594680-75284480-0e95-11e9-96ea-bab0d3074840.png)

**Comment by bugy** [comment]
Hi @Smadger1, by default you can access it from localhost only (if no auth is enabled).
A small documentation about admin page: https://github.com/bugy/script-server/wiki/Authorization#admin-users

If you don't have auth enabled, you need to add your IP to [trusted_ips](https://github.com/bugy/script-server/wiki/Server-configuration#--trusted_ips) in server config
And in any case you need to add your username or IP to [admin_users](https://github.com/bugy/script-server/wiki/Server-configuration#--admin_users)

I understand, that it's a little bit inconvinient, but there is aways trade-offs between security and usability

**Comment by Smadger1** [comment]
Hi @bugy thank you for this,

Sorry I didn't spot it in the documentation.

**Comment by bugy** [comment]
Hi @Smadger1, did you manage to solve the issue? Does the config work for you?

**Comment by Smadger1** [comment]
Hi, I have been extremely busy recently so haven’t had a chance to fix the issue yet. Sorry about the delayed response, will get back to you as soon as I attempt the fix. Thank you😊

**Comment by Smadger1** [comment]
All working thank you @bugy
