### ISSUE TITLE
Calling the script...   ---  ERRORS  ---  Exec format error

### ISSUE THREAD

**Issue by Smadger1** [bugy/script-server#155]
I get the following error when trying to run a bash script on my server. This script currently runs hourly with a cron job and runs fine.
**ERROR**
```
2019-01-02 14:12:11,990 [web_server.ERROR] Error while calling the script
Traceback (most recent call last):
  File "src/web/server.py", line 319, in post
    all_audit_names)
  File "src/execution/execution_service.py", line 46, in start_script
    executor.start()
  File "src/execution/executor.py", line 64, in start
    process_wrapper.start()
  File "src/execution/process_base.py", line 28, in start
    self.start_execution(self.command, self.working_directory)
  File "src/execution/process_pty.py", line 44, in start_execution
    start_new_session=True)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/runBackup.sh'
```

**CONFIG**
```
{
  "name": "Backup",
  "script_path": "/home/runBackup.sh",
  "description": "Some useful description on what the script does"
}
```

**Comment by Smadger1** [comment]
Here is the backup script
```#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runBackup.sh
cd ..
d=$(date '+%Y_%m_%d_%H_%M')
echo "Deleting old backup contents"
rm -r /home/backup/*
echo "Copying Survival World"
cp -R /srv/daemon-data/4409f08f-514a-482c-8736-4253549b048d/world "/home/backup/survivalWorld $d"
echo "Copying Creative World"
cp -R /srv/daemon-data/502ac3e7-d630-4bc6-aaa7-910cdfc05683/world "/home/backup/creativeWorld $d"
echo "Copying Project Ozone"
cp -R /srv/daemon-data/41a34524-6d1a-401f-b15a-252084be5e5c "/home/backup/projectOzone $d"
echo "Zippping up backups folder"
tar -a -czf "/home/backup/backup $d.tar.gz" /home/backup
echo "Uploading backup"
gdrive upload --parent "/home/backup/backup $d.tar.gz"
echo "Backup created. View backup here -> "
```

**Comment by Smadger1** [comment]
Below is a screenshot of my current script which does have the shebang and it still produces the same error. How would I go about checking to see if it is a permissions problem.

![image](https://user-images.githubusercontent.com/22797936/50596089-ef0efc80-0e9a-11e9-9895-50a73c801c4c.png)

**Comment by bugy** [comment]
Hi @Smadger1 , this is really strange. I copypasted your code above (for backup script) and it worked fine for me
For permission issue there should be a different error "Permission denied"

**Comment by Smadger1** [comment]
@bugy Could it possibly be a formatting error since I created the file on my windows machine and uploaded it via ftp?

**Comment by bugy** [comment]
Interesting assumption. I think it could be a problem with line endings. On Windows it's different and could be that Linux cannot recognize shebang in such case

**Comment by Smadger1** [comment]
I have recreated the file using nano, how would I fix the permissions so that script-server can run it since the new file gets a permissions error?

By the way thank you for the help!

**Comment by bugy** [comment]
Try `chmod +x myscript.sh`

You are welcome

**Comment by Smadger1** [comment]
I _think_ that fixed it only problem now is that it gets stuck on Calling the script.

Here is the log file (cut out IP addresses ect.)

```
2019-01-02 14:45:14,324 [web_server.INFO] Calling script Backup. User {}
2019-01-02 14:45:14,324 [script_server.execution_service.INFO] Calling script #20: /home/createbackup.sh
2019-01-02 14:45:14,327 [tornado.access.INFO] 200 POST /scripts/execution () 5.46ms
2019-01-02 14:45:14,409 [tornado.application.ERROR] Uncaught exception in /scripts/execution/io/20
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 322, in wrapper
    return callback(*args, **kwargs)
  File "src/web/server.py", line 211, in open
    validate_execution_id(execution_id, self)
  File "src/web/server.py", line 403, in validate_execution_id
    raise tornado.web.HTTPError(400, reason='No (active) executor found for id ' + execution_id)
TypeError: must be str, not bytes
2019-01-02 14:45:14,409 [web_server.INFO] disconnected
```

**Comment by bugy** [comment]
Hi @Smadger1, which version of script-server are you using? This one looks like a bug

**Comment by Smadger1** [comment]
I believe it is the latest non-dev version. Is there an easy way to find out?

**Comment by bugy** [comment]
If it's the latest non-dev, then it's 1.12

May I ask you for some help and change your local code in src/web/server.py file?
Please find the following line (should be ):
`def open(self, execution_id):`
After the following code after it:
`        execution_id = execution_id.decode("utf-8")`
(check that whitespaces match the next line)

And then try to run the script again

**Comment by Smadger1** [comment]
That fixed it thank you @bugy

**Comment by Smadger1** [comment]
@bugy Having upgraded Tornado to 5.1.1 and removed that extra line I can confirm it still works. Thank you and sorry for being an idiot with such an ancient version of Tornado.

**Comment by bugy** [comment]
No worries and thank you for all the checks!
