### ISSUE TITLE
Fonts not found

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#158]
I've setup nginx reverse proxy in front of script server as described [here](https://github.com/bugy/script-server/wiki/Reverse-Proxy-setup). (with basic auth)
However when I browse my script-server address, some fonts are not loading. It's because they're looking at wrong path. I think correct path should be:
```
https://mydomain.com/script-server/fonts/roboto-latin-300.woff2
```
etc currently it's looking at
```
https://mydomain.com/fonts/roboto-latin-300.woff2
```
which is incorrect IMO. I think It didn't happen on 1.12.0 release. (I'm running on dev release)

![image](https://user-images.githubusercontent.com/3091558/51173834-48424b80-18f1-11e9-8c29-003c495510ec.png)

**Comment by bugy** [comment]
Thanks! Most probably it comes after my large web-side refactoring on dev. I'll have a look.

**Comment by shinebayar-g** [comment]
Just tried to reproduce this errors on 1.12.0 release. Looks like these are new additions since last release.
1.12.0 release uses these:
```
https://mydomain.com/script-server/css/fonts/roboto/Roboto-Regular.woff2
https://mydomain.com/script-server/css/fonts/roboto/Roboto-Light.woff2
```

**Comment by shinebayar-g** [comment]
Also, consider what if user want to put script-server on different path like `mydomain.com/not-script-server` etc, in such case it still should be working. I mean it should be flexible.

**Comment by bugy** [comment]
In the code I don't have anything related to `script-server` path, so it should be ok.

**Comment by shinebayar-g** [comment]
That's great.

**Comment by bugy** [comment]
Should be ok now on the latest dev

**Comment by shinebayar-g** [comment]
Confirm fixed.

**Comment by bugy** [comment]
thanks for sharing! True, admin page has different paths :( 

And thanks for telling about dev release date. I started such releases only recently (actually 20 days ago), and don't know all the details about it. Hopefully it could be fixed somehow via travis

**Comment by bugy** [comment]
After couple of hours of fighting with webpack and ccs/file loader plugins, I still couldn't find a way to solve it...
So it will take some time

**Comment by shinebayar-g** [comment]
Ugh, i see. Also could you please add go back to homepage button somewhere? Once you go to admin page, there is no navigation back.

**Comment by bugy** [comment]
Created a ticket for it: #166

**Comment by bugy** [comment]
Hi @shinebayar-g, completely offtopic to this ticket, but I couldn't find any other contact to you :)
I'm trying to spread a word about Script server, and would like to ask you for some feedback https://github.com/mahmoud/awesome-python-applications/issues/35

I would greatly appreciate your help in this regards!

PS I'll delete this comment after you read it. If possible and needed, please contact me via email buggygm@gmail.com or telegram/whatsapp: 017622246174

**Comment by shinebayar-g** [comment]
Ok I'll write you email.

**Comment by bugy** [comment]
Fonts should be fixed on admin page as well now. 

Please be careful, in a recent commit for #137 I changed server API urls. So if the JS code is **cached** in browser, while server side is updated, it will cause issues. Apart from caches it shouldn't cause any other problems

**Comment by shinebayar-g** [comment]
Confirmed fixed.
