### ISSUE TITLE
What happens when user's browser crash / freeze / refresh or internet disconnect?

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#162]
I'm sorry for making so many issues lol. But it happened to me today. I was running my heavy script and I've got internet outage during that time. When I refresh my browser it doesn't seem to be running any task. It just showed its index page. But when I check the server processes with `htop` program it was running the heavy script and eventually it finished. (Cuz end of the script it pushes new image to registry and it did).
But I cannot say it's expected behaviour or not, do you have any handler on events like this? Cuz then later I've had another outage, but this time script didn't finish I think.

**Comment by bugy** [comment]
You should be able to reconnect to the script: https://github.com/bugy/script-server/issues/100
The problem for you could be, that you tried to connect from a different browser/place (if you don't have an auth enabled). 
You should also be able to see script info on admin page (its status and current logs)

**Comment by shinebayar-g** [comment]
Oh I don't have any auth except nginx basic auth. I don't have to admin page at the moment, due to no auth :D 

Question: If I had auth enabled I could reconnect to running script from another browser too?

**Comment by bugy** [comment]
> Question 2: If I disconnected from script-server will scripts complete on its own?
Yes, they should, unless you stop the server explicitly. You can test it with some simple script and sleep inside.

> Question: If I had auth enabled I could reconnect to running script from another browser too?
Yes. You can do it even without auth, if you add your reverse proxy to `trusted_ips`. Then user IP will be his unique name, and you would be able to add it to `admin_users`

> Cuz then later I've had another outage, but this time script didn't finish I think.
This is really strange and I cannot imagine it happening if script itself didn't die or Script server wasn't killed in between.

**Comment by shinebayar-g** [comment]
> This is really strange and I cannot imagine it happening if script itself didn't die or Script server wasn't killed in between.

I should make an update here, I think I worried about scripts and stopped service I think. So don't really worry on this one.

**Comment by shinebayar-g** [comment]
Is it possible to add reverse proxy itself's IP address to trusted_ips? I don't think I can do this, because end user's (my) IP is sent to script-server not reverse proxy's right?

I don't have static IP at my work / home, so this method is not gonna work for me i guess.
