### ISSUE TITLE
Script server cuts large logs on UI sometimes

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#163]
When output is too large (e.g. 50k lines) and with bash formatting Script server randomly stops showing logs on UI (though they are logged properly to the file). For more details please look at https://github.com/bugy/script-server/issues/161#issuecomment-454439920

**Comment by bugy** [comment]
Hi @shinebayar-g, I couldn't reproduce it. I executed a script with 45k lines multiple times (almost burned down my CPU :) ) and every time the log was fully shown on UI

Could it be, that there was some disconnect or server restart during script execution?
Also at the moment, when there are a lot of logs, written very fast, they are not flushed immediately, but somehow "stuck" until all logs are processed by the server. And then the huge batch of logs is sent to UI. Could it be your case?

**Comment by bugy** [comment]
Hi @shinebayar-g, thanks for info.
Could it be, that you didn't wait until script stopped on UI? There is an issue with unresponsive massive output: #172 

Did you or your collegues experience this problem afterwards? If we could reproduce it (even very seldomly) it would help to find out the reason.

**Comment by shinebayar-g** [comment]
Script was finished, at first I thought that too. I waited like 5 minutes at least, after script complete.

**Comment by bugy** [comment]
Since I didn't manage to reproduce the issue and since #174 is there (with almost complete new implementation of displaying logs on UI side), I'm closing this ticket. If it happens again, please fell free to reopen this one or create new.
