### ISSUE TITLE
admin panel's execution history doesn't support bash formatting

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#165]
I've this bash script with color formatting. It has some visual bugs when executing this type of files (I couldn't catch what is exactly bugging this, but I'll find it and probably raise an another issue)

If I check execution history from admin panel these type of scripts looks like this:
```
[1m01:34:11 : Changing directory to service[0m
[1m01:34:11 : Pulling update from master[0m
From https://github.com/user/repo
 * branch            master     -> FETCH_HEAD
Already up to date.
[1m01:34:11 : Changing directory to user-base[0m
[1m01:34:11 : Pulling update from master[0m
From https://github.com/user/user-base
 * branch            master     -> FETCH_HEAD
Already up to date.
```

![image](https://user-images.githubusercontent.com/3091558/51199712-75fbb480-1932-11e9-8f9b-17a4ea8357cc.png)

original script is:
```
#!/bin/bash
now=$(date +"%T")

# Pull changes
echo -e "\e[1m\e[34m$now : Changing directory to service\e[0m"
cd /home/shinee/service/service

echo -e "\e[1m\e[34m$now : Pulling update from master\e[0m"
git pull origin master

echo -e "\e[1m\e[34m$now : Changing directory to user-base\e[0m"
cd /home/shinee/service/user-base

echo -e "\e[1m\e[34m$now : Pulling update from master\e[0m"
git pull origin master
cd /home/shinee/service
```

**Comment by bugy** [comment]
Hi, this is expected behaviour. On admin panel I'm showing raw output without any processing, to avoid possible confusion caused by invalid formatting or weird script outputs.

I'll keep this ticket for make output type (raw/formatted) configurable (probably via checkbox on UI)

**Comment by bugy** [comment]
So, after finishing #174, admin terminal will always show formatted output. I would create a separate ticket to make it configurable (raw/formatted)
