### ISSUE TITLE
Is it possible to dump & download?

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#167]
Example, mysql or mongodb dump & download is possible to do with script-server?

**Comment by bugy** [comment]
Should be, please have a look at https://github.com/bugy/script-server/wiki/Script-config#output_files

So if you have a script like:
```
mysql dump my-database -o /tmp/dumps/$(date +%s).sql
```

then you can have config:
```
"output_files": [
	"/tmp/dumps/#\d+#.sql"
]
```
This config will check output logs and search for any string matching `/tmp/dumps/#\d+#.sql` and make it downloadable
