### ISSUE TITLE
How to setup Google Oauth?

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#168]
Hi, I've just setup my google app and got my secret and client_id. And also setup **Authorized redirect URIs** (which wasn't documented in wikis) except [here](https://github.com/bugy/script-server/issues/95).

Now my `conf.json` looks like this, but script-server is not starting up.
```json
{
  "address": "127.0.0.1",
  "auth": {
          "type": "google_oauth",
          "client_id": "REDACTED.apps.googleusercontent.com",
          "secret": "REDACTED"
  },
  "admin_users": ["me@gmail.com"],
  "allowed_users": "me@gmail.com"
}
```

and I've got this from journalctl logs.
```
Exception: auth.allowed_users field is mandatory for google_oauth
```

Then I moved `allowed_users` to auth level.

```json
{
  "address": "127.0.0.1",
  "auth": {
          "type": "google_oauth",
          "client_id": "REDACTED.apps.googleusercontent.com",
          "secret": "REDACTED",
          "allowed_users": "me@gmail.com"
  },
  "admin_users": ["me@gmail.com"]
}

But still it's giving same error. Now I'm just stuck, what should I do?
Also wiki documents should be updated with more detailed instructions.

**Comment by bugy** [comment]
Hi, there is some documentation: 
https://github.com/bugy/script-server/wiki/Authentication#google-oauth

`allowed_users` is now part of `access` field, i.e.:
```
{
    "access": {
        "allowed_users": []
   }
}
```

You can find better example at the end of the page: https://github.com/bugy/script-server/wiki/Server-configuration

**Comment by shinebayar-g** [comment]
> You can find better example at the end of the page: https://github.com/bugy/script-server/wiki/Server-configuration

Oh thanks! Didn't see that one, my bad. If it's possible, can I have access to contribute to wiki?

**Comment by shinebayar-g** [comment]
Quick question: Can you tell me what's the difference between `access.admin_users` and just `admin_users`?

![image](https://user-images.githubusercontent.com/3091558/51539381-ccb34200-1e8e-11e9-81a2-8793ad2cd13d.png)

**Comment by bugy** [comment]
Obsolete config. It was moved to the access section as well

**Comment by bugy** [comment]
I added you to collaborators, could you check your wiki access rights? (and may be fix the example above)

**Comment by shinebayar-g** [comment]
Done, I've made little changes on that page. Thank you. I'll be fixing wiki in the meantime. :)
