### ISSUE TITLE
Uncaught TypeError: Cannot read property '$destroy' of null

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#175]
This error is logged in browser time to time. Please check comments https://github.com/bugy/script-server/issues/164#issue-399459276 and  https://github.com/bugy/script-server/issues/164#issuecomment-457922448

Corresponding screenshot: https://user-images.githubusercontent.com/3091558/51198695-f5d44f80-192f-11e9-8d51-99a5d63ec1fc.png

**Comment by bugy** [comment]
Hi @shinebayar-g I was able to reproduce the issue, quickly switching between different scripts. 
Interestingly, that after it happens, you cannot open any script anymore (until page reload). 

I'm not sure if stop button can cause such exception. According to the code, it shouldn't

**Comment by shinebayar-g** [comment]
> Hi @shinebayar-g I was able to reproduce the issue, quickly switching between different scripts.
> Interestingly, that after it happens, you cannot open any script anymore (until page reload).
Yea, that was happening. It breaks until full page reload.

> I'm not sure if stop button can cause such exception. According to the code, it shouldn't

**Comment by bugy** [comment]
Should be fixed now.

In this way I was able to reproduce that socker error also (closed before establishing connection).
Sorry for not putting attention to this browser error earlier :( I confused cause and effect

**Comment by shinebayar-g** [comment]
Okay nice, if it's resolved feel free to close the issue.
