### ISSUE TITLE
running parametrized.sh no USER

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#179]
cloned master brunch
running parametrized.sh

python[26030]: 2019-02-06 11:01:47,802 [tornado.application.ERROR] Uncaught exception GET /scripts/Very%20parameterized (10.177.158.121)
python[26030]: HTTPServerRequest(protocol='http', host='yosef-airflow-tests.pipl.pro:5000', method='GET', uri='/scripts/mote_ip='10.177.158.121')
python[26030]: Traceback (most recent call last):
python[26030]:   File "/opt/script-server/env/lib/python3.6/site-packages/tornado/websocket.py", line 546, in _run_callback
python[26030]:     result = callback(*args, **kwargs)
python[26030]:   File "src/web/server.py", line 110, in wrapper
python[26030]:     return func(self, *args, **kwargs)
python[26030]:   File "src/web/server.py", line 132, in wrapper
python[26030]:     return func(self, *new_args, **kwargs)
python[26030]:   File "src/web/server.py", line 202, in open
python[26030]:     self.config_model = self.application.config_service.create_config_model(config_name, user)
python[26030]:   File "src/config/config_service.py", line 64, in create_config_model
python[26030]:     return self._load_script_config(path, json_object, user, parameter_values)
python[26030]:   File "src/config/config_service.py", line 105, in _load_script_config
python[26030]:     parameter_values=parameter_values)
python[26030]:   File "src/model/script_configs.py", line 68, in __init__
python[26030]:     self._init_parameters(username, audit_name)
python[26030]:   File "src/model/script_configs.py", line 141, in _init_parameters
python[26030]:     self.working_directory)
python[26030]:   File "src/model/script_configs.py", line 282, in __init__
python[26030]:     self._reload()
python[26030]:   File "src/model/script_configs.py", line 301, in _reload
python[26030]:     self.default = _resolve_default(config.get('default'), self._username, self._audit_name)
python[26030]:   File "src/model/script_configs.py", line 626, in _resolve_default
python[26030]:     resolved_env_default = resolve_env_vars(default, full_match=True)
python[26030]:   File "src/model/model_helper.py", line 20, in resolve_env_vars
python[26030]:     return env_utils.read_variable(value[2:])
python[26030]:   File "src/utils/env_utils.py", line 8, in read_variable
python[26030]:     raise Exception('Environment variable ' + variable_name + ' is not set')
python[26030]: Exception: Environment variable USER is not set

**Comment by bugy** [comment]
Hi @yosefy, thanks for reporting! I thought USER env variable is set on all linux distributions :(

**Comment by yosefy** [comment]
it is running vis systemd thats why i think

**Comment by bugy** [comment]
Then it makes sense. I'll just remove this parameter from the script then or update not to reference environment variable

**Comment by bugy** [comment]
Removed environment variables from the sample file. 
Replaced them with a couple of unit tests
