### ISSUE TITLE
enable google auth via proxy

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#183]
i think it can't get to google without proxy config

Feb 18 12:27:53 XXX python[31362]: 2019-02-18 12:27:53,088 [script_server.tornado_auth.INFO] Trying to authenticate user
Feb 18 12:28:13 XXX python[31362]: 2019-02-18 12:28:13,110 [script_server.GoogleOauthAuthorizer.ERROR] Failed to load access_token: Timeout while connecting

**Comment by bugy** [comment]
Hi @yosefy, could have a look at this answer please?
https://stackoverflow.com/a/31641300

Basicaly, before starting the script server, could you try to export mentioned environment variables with your proxy config?

**Comment by yosefy** [comment]
Doesn't work
Found this one :
https://github.com/tornadoweb/tornado/issues/754

**Comment by bugy** [comment]
ok :( Thanks for checking it

**Comment by yosefy** [comment]
what worked for me on ubuntu 18


apt-get install libssl-dev libcurl4-openssl-dev python-dev
pip install pycurl

add to src/auth/auth_google_oauth.py

####################################
import os
defaults = {}
http_proxy = os.environ.get('http_proxy')
if http_proxy:
    if http_proxy[:7] == "http://":
        http_proxy = http_proxy[7:]
    defaults['proxy_host'], defaults['proxy_port'] = http_proxy.split(":")
    defaults['proxy_port'] = int(defaults['proxy_port'])

httpclient.AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient", defaults=defaults)
############################

**Comment by bugy** [comment]
Great thanks for checking it! Will refactor it somehow and add.

A question: did you configure environment variable `http_proxy` before that? With lowercase?

**Comment by yosefy** [comment]
Yes I did
Thanks
May be better just add it in config

**Comment by bugy** [comment]
I would prefer to use default python approach with environment variables (as in stackoverflow answer). Just need to adjust code to it.

**Comment by bugy** [comment]
Done. Now any environment variables (https_proxy or http_proxy, all lowercase or all uppercase) can be used.

This feature requires pycurl to be installed

@yosefy could you check please, if the latest version works for you?
