### ISSUE TITLE
Add possibility to upload large files

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#184]
At the moment, when uploading a large file (~100Mb), web server fails with 
> Malformed HTTP message from ....: Content-Length too long

It should be possible to allow larger files, probably with setting max file size manually in Script server configuration.

**Comment by bugy** [comment]
Done. Now max request size can be configured in server config (conf/conf.json), with `max_request_size` parameter (in megabytes).
By default the current limit is 10Mb

Also implemented streamed reading of uploaded_files, i.e. bytes are written to disk as soon as they come without buffering in memory. Tested on 6gb file, memory consumption stayed below 25Mb during the upload.
This can cause regression issues with parsing input parameters of the scripts

**Comment by rrbbt** [comment]
What a useful feature!
Thank you so much!

**Comment by dridk** [comment]
could you add this new parameter into the documentation ?

**Comment by bugy** [comment]
Oops, thanks for noticing, @dridk!
Fixed!
