### ISSUE TITLE
int may support zero

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#185]
if we make int field required and fill in 0, then it will not take it

**Comment by bugy** [comment]
Is UI field validation fails with "required"?
Or you get it as a server response?

**Comment by yosefy** [comment]
in UI
it was 0 not "0"
i guess it translated to falser somehow

**Comment by bugy** [comment]
Hi @yosefy, unfortunately I couldn't reproduce it :(
Which version of Script server and browser are you using?
And could you share the configuration of the parameter, please?

**Comment by yosefy** [comment]
it is in included params file only i think
where also default values don't work btw

**Comment by bugy** [comment]
Hi @yosefy, unfortunately i still cannot reproduce it :(
Could you send me a screenshot please, and share the configuration? May be you could create a minimal config, which would allow me to reproduce it.

**Comment by bugy** [comment]
Hi @yosefy, could you check my last message, please?

**Comment by yosefy** [comment]
Let's close it for now. I I get into this again, I will update

**Comment by bugy** [comment]
ok. Sorry for not coming back to you earlier :(
