### ISSUE TITLE
when list is longer then browser size, scrolling doesn't work

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#187]
when the list crosses the lower boundary of the browser, no scrolling
if resize the browser while the list is opened, scrolling starts working

**Comment by bugy** [comment]
@yosefy could you send a screenshot please?

**Comment by yosefy** [comment]
![image](https://user-images.githubusercontent.com/12940013/53505080-d34f5d80-3abb-11e9-8132-9633179c5033.png)

**Comment by bugy** [comment]
It was kind of known issue of materialize css: https://github.com/Dogfalo/materialize/issues/2592
Made a fix, works for me on Chrome, but could be very browser-dependant

@yosefy could you check if it works for you, please?
