### ISSUE TITLE
when the list is very long, very useful to have filter/search on top of it

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#188]
though it is sorted which is very helpful

we sometimes have very long lists coming from some api
and it is little pain to scroll and search 

though is just a cosmetics :)

**Comment by Vierz** [comment]
I would be very nice to have this feature. I manage a lot of scripts for different accounts in AWS, and the list is insane so its really difficult to find the account.

**Comment by bugy** [comment]
Done. If a list has more than 10 elements, a search field is added automatically
