### ISSUE TITLE
state and exit status of script

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#194]
if we run a script via api, then the caller service needs to know if we are finished for example:
(we call from airflow )

GET /state/$RUN_NUMBER

res:
{ 
    "state": "running",
    "exit-status-code": None
}

or

{ 
    "state": "done",
    "exit-status-code": -1
}

what do you think?

thanks

**Comment by bugy** [comment]
Hi, there is endpoint GET /executions/status/executionId for it. It should return either "running" or "finished".
May be it can extended with exit code and wrapped in a json

**Comment by yosefy** [comment]
ah nice!

yep adding exit code could be very useful so caller will continue depending on it

may be another rout and not json
but i guess json is also good

thanks

**Comment by bugy** [comment]
Hi, there is an API for history, which would be better for you:
`/history/execution_log/long/(.*)`
You pass script id, and it will return all the info about the script, you can check `status` and `exitCode` fields there
