### ISSUE TITLE
Couldn't download output files with cyrillic names

### ISSUE THREAD

**Issue by rrbbt** [bugy/script-server#195]
I've just adopted nice music downloader script to run with Script Server:
https://github.com/yask123/Instant-Music-Downloader
It works just fine except for the songs with cyrillic names. When trying to download such file, browser gives 404 error (file not found).

**Comment by bugy** [comment]
Thanks for reporting, I committed the fix, it will go into the next release.

Quite weird, that I didn't notice it before. The failing code is there for 2 years already
