### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by gcmroi** [bugy/script-server#196]
Can one use Script Server to call Python 2.7 scripts or the support is limited to Python 3.4 and above?

Thanks.

  GC

**Comment by bugy** [comment]
Hi @gcmroi, python2 scripts are perfectly fine. Actually you can call any types of scripts (bash, perl, py2, py3, etc.). Script server runs scripts in separate processes.

But the server itself should be run with python 3

**Comment by gcmroi** [comment]
Thanks @bugy. Appreciate the quick response.

**Comment by gcmroi** [comment]
@bugy. Follow up question... I have tried to call a Python 2.7 script but some imports in the 2.7 script being called fail. Is there a specific way to format the call that is needed for this to succeed?

Thanks!

**Comment by bugy** [comment]
Hi @gcmroi , which OS are you using?
If linux/macos, do you have a shebang in the script? Does it refer to a proper python?
If you could share some logs/errors, it would be helpful to find out the problem

**Comment by gcmroi** [comment]
I am testing on Mac OS. I believe we have a shebang but I will need to double check (one of my engineers wrote the script.) 

The error we're getting is simply: ImportError: No module named <module_name>.

If we install the missing module in script-server the error goes away, but this poses 2.7/3.6 compatibility issues, of course.

Note that both script-server as well as the script being called use virtual environments.

Thanks for the quick follow-up!

**Comment by bugy** [comment]
Hi @gcmroi, I guess the script is executed with python 3, exactly because of being run in virtual environment: all child processes inherit environment from the parent (Script server), including python virtual env, probably.
So the option would be to use exact python path in the script shebang, or in the json file for Script server, e.g.
`"script_path": "/path/to/python2 my_script.py"`

**Comment by gcmroi** [comment]
That was my hunch as well, but didn't know how to address it, so thanks for clarifying. I'll try the adding the exact path and report back.

**Comment by gcmroi** [comment]
Quick update... 

I was able to address the issue by adding both the shebang to the script being called, as well as adding the full `venv/python` path plus the full script path to the "`script_path`" parameters. Now everything seems to be working.

Thanks a lot for your support and congrats on a great tool!

**Comment by bugy** [comment]
I'm glad it worked :) I think one of those should be enough

**Comment by gcmroi** [comment]
It actually seems it needs both. Thanks again for your help.
