### ISSUE TITLE
Couldn't download output files when secure parameter is used

### ISSUE THREAD

**Issue by pulpo** [bugy/script-server#198]
When I try to use a secure parameter, for example for a **password**, the download file dialog is not displayed. 

```
    {
      "name": "Password",
      "param": "-p",
      "type": "text", 
      "secure": "true"
    },
``` 
If I change the `secure`to `false`, after the execution the dialog is displayed. In both cases the `temp/resultFiles` folder is created.

**Comment by bugy** [comment]
Hi @pulpo, thanks for reporting. Does the filename depend on the secure parameter or match it somehow?

**Comment by pulpo** [comment]
Hi @bugy. The filename doesn't depends on the secure parameter. I made an script that does nothing but showing a hello message, and when I add a secure parameter I reproduce the problem. I tested it against stable and dev tags (from the docker image) with the same results. 

```
{
  "name": "Download file",
  "output_files": [
    "/tmp/final.json"
  ],
  "working_directory":"/app/scripts",
  "script_path": "hello.sh",
  "parameters": [
    {
      "name": "Bla",
      "param": "-p",
      "type": "text",
      "secure": "true" 
    }
  ]
```
Changing the secure's value or removing parameters shows me the download dialog.

**Comment by bugy** [comment]
Thanks a lot for the nice description and configuration examples. I'll have a look

**Comment by bugy** [comment]
I reproduced it locally, looks like a race condition for me (sometimes the download file is still shown). Will work on the fix in the nearest days

**Comment by bugy** [comment]
Fixed. Should work now.

Thanks again for reporting!

**Comment by pulpo** [comment]
I can confirm that it's fixed, tested on the dev branch. Thanks for your great work!
