### ISSUE TITLE
Add support for default values for included parameters

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#201]
If script configuration contains included parameters (from another file), then default values of these parameters are ignored.
Default values should be filled once included parameters are shown for the first time, i.e. if a user puts some value in such a parameter and then switches to another included config and back, the value should remain, as set by the user

**Comment by yosefy** [comment]
waiting for this one patiently :)
we need it in prod
devs 99 % of the time don't need to choose the values, and they don't know the default

thanks

**Comment by bugy** [comment]
Hi @yosefy, I implemented support for default values. Could you check please, if it's working for you in a dev build?

**Comment by yosefy** [comment]
nope , not working

i clone the repo, then "tools/init.py --dev --no-npm"
...

included file:

{
  "hidden": true,
  "parameters": [
    {
      "param": "ansi__exporterType",
      "name": "exporter name",
      "default": "test",
      "type": "list",
      "values": {
              "script": "ls /dir/"
      }
    }
  ]
}


shows nothing
no log

**Comment by bugy** [comment]
Perfect, thanks for confirming!

**Comment by bugy** [comment]
By the way, you can download the latest release from releases or use docker. There is no need to clone the whole repo
