### ISSUE TITLE
LDAP groups cannot be added to user-defined groups

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#212]
If LDAP auth is enabled, script server is taking user groups from LDAP. Additionally, admin can specify own groups in the script server. However, specifying LDAP groups in user-defined groups is ignored. 
Please see comment for details: https://github.com/bugy/script-server/issues/207#issuecomment-489151339

**Comment by bugy** [comment]
Hi @tristanlatr, the fix is done. You can check it on dev version

**Comment by tristanlatr** [comment]
I confirm that it works now !

**Comment by bugy** [comment]
Perfect, thanks!
