### ISSUE TITLE
allow auth.username and auth.audit_name in script values

### ISSUE THREAD

**Issue by muzzol** [bugy/script-server#217]
opening this feature request as recommended here: #130 

it would be nice to allow auth variables in script values.
ex:

```
    {
      "name": "Roles",
      "type": "list",
      "values": { "script": "/opt/scripts/list_rols.sh ${auth.audit_name}" }
    },


```

**Comment by autogun** [comment]
Hey @bugy,

I'd like to add this one, also to have ${auth.username} templated in the `description` field.
Can you point me to the right place?

**Comment by bugy** [comment]
Hi @autogun, for filling the values, there is a `model_helper.replace_auth_vars` method

For script substitution: parameter_config.py:183
For the description: parameter_config.py:70
