### ISSUE TITLE
can't see output behind proxy

### ISSUE THREAD

**Issue by muzzol** [bugy/script-server#221]
another proxypass problem:

since 1.14.0 output is not shown. If I connect directly to port 5000 I can work without problemes, but with apache and proxypass output is empty even if scripts are indeed executed.

this is my configuration

```
	<Location /comandes/>
                 # Define ScriptServerUrl http://localhost:5000/
		 Define ScriptServerUrl http://gestor.xxx.net:5000/
 
                 ProxyPass ${ScriptServerUrl}
                 ProxyPassReverse ${ScriptServerUrl}
                 RequestHeader set Origin ${ScriptServerUrl}
 
                 RewriteEngine On
                 RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                 RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
                 RewriteRule /(.*) ws:/$1 [P,NE]
         </Location>

```

apache version is 2.4.25

**Comment by bugy** [comment]
Hi @muzzol, thanks for reporting. Could you provide browser/server logs? And do you have a list of accesses (which URLs were called and forwarded) from Apache?

**Comment by muzzol** [comment]
hi @bugy , I've investigated a little bit and I've found that it works in Firefox but not in Chrome.

I'm testing it right now with last master version pulled from git.

**Comment by bugy** [comment]
Hi, I think I've fixed this problem just before 1.4 release. And I cannot
reproduce it locally with the same Apache settings
Could you try to test on the version, built by CI? Also, try to refresh JS
code in browser (ctrl+R probably)

Also, could you send me info from the browser's network tab, after you try
to run a script?
And if there are any errors in the browser console

mussol <notifications@github.com> schrieb am Fr., 7. Juni 2019, 12:09:

**Comment by bugy** [comment]
Hi @muzzol, could you check my last message please?

**Comment by bugy** [comment]
Hi @muzzol, could you check my last message please?

**Comment by zrks** [comment]
Just FYI - had the same issue behind proxy which was solved by adding:
`access.trusted_ips=<LB_IP>`
