### ISSUE TITLE
Problem in interpretation with a script parameter cmd.exe

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#224]
Hi !

I've just see a bug:

>     {
>       "name": "Test",
>       "param": "--test",
>       "type": "list",
>       "values": {
>         "script": "cmd.exe /c \"echo lol\""
>       },
> 	  "required": true
>     },

Response :

> Calling the script...
> 
> Invalid parameter Label Template Path Dev value: has value lol
> ] but should be in [lol

Have a good day :)

Version : 1.14.0
OS : Windows
Python : 3.6.14

**Comment by bugy** [comment]
Hi @csphoenix1, thanks for reporting!

PS I'm surprised, that someone is using script server on windows :) Probably I have to put more attention to testing there

**Comment by csphoenix1** [comment]
Hi @bugy,

Yes I use it ALSO on Windows, and it work very well :) Just this little problem I've just said.

Ciao.

**Comment by yosefy** [comment]
just to notice, we use it as main ansible runner and for more stuff and
it is beautiful :)

**Comment by bugy** [comment]
Hi @csphoenix1, unfortunately, I was not able to reproduce on win7 and latest dev , but I guess I know the root of the problem, based on your log message.
I made a fix, could you check please if it works for you?
