### ISSUE TITLE
Kill by PGID or by PID

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#227]
Hi,

I have a script (launched by Script-Server) which allow me launching some programs.
The problem is when I click on STOP, the child programs are killed.

After investigation in the code, I saw that the STOP function send an INT to the PGID :
File : 
> src/execution/process_base.py
Code :
> group_id = os.getpgid(self.get_process_id())
> os.killpg(group_id, signal.SIGTERM)

If I replace by it bellow, my programs aren't killed.
> group_id = self.get_process_id()
> os.kill(group_id, signal.SIGTERM)

Why does we kill by PGID ? Is there a reason ?
Is there a possibility to kill only by PID ?
Maybe a parameter in the .json file ? Or a global parameter ?

Thank you.

**Comment by bugy** [comment]
Hi @csphoenix1, actually killing child programs is intentional. In my understanding, all child programs are sub-programs, used by the main script. I.e. some kind of utilities. They make no sense to exist, if the main script is not running anymore. Otherwise, there will be some kind of zombies.

**Comment by csphoenix1** [comment]
Hi @bugy ,
Humm I understand.
Because in the Python file of my program, I use "os.system" to invoke my program, or via subprocess.
So I think I have to launch it with a different PGID.
I will make changes in my code, because I share you "understanding/opinion" :)
