### ISSUE TITLE
Migration to Vue.JS

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#229]
At the moment, script server main UI is built mostly on vanilla JS. To make it easier to maintain, it's better to migrate to Vue.JS

**Comment by yosefy** [comment]
Why not react? (Just curious)

**Comment by bugy** [comment]
Hi @yosefy, one year ago, when implementing admin panel for script-server, I decided to play with one of the modern frameworks. I wanted to use it as a library, i.e. mix vanilla js and use framework's components when needed. For that use case, Vue js was most suitable among all. So I fully implemented admin panel in Vue js, and then used vue js components for the controls (text fields, comboboxes, etc.) in main script server UI (keeping main code in vanilla).

So far I'm pretty satisfied with Vue js, and the time has come to fully migrate to it. It also will make some complicated parts of code easier to maintain.

Also, at my current work, we are using React for UI, so I got some experience with it. And I have to admit, that I like vue js waaaay better. For me, coding in Vue js is much more natural, because of "pure" HTML, javascript and CSS. In React you have to write React code (with react styles and react html). And as for me, Redux is really awful.

**Comment by bugy** [comment]
Migration is finished. I tried my best to find out all the issues, but probably there will be quite some bugs...
