### ISSUE TITLE
Supporting images in the script output

### ISSUE THREAD

**Issue by kucbd** [bugy/script-server#231]
It would be very helpful if there is a way to include dynamically generated images in the script output.

Example of expected output:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/54399273/63508254-e460b080-c4d9-11e9-90b8-b798f02a0f0f.png">

**Comment by bugy** [comment]
Hi @kucbd, thank you for the proposal! How can Script server know about an image? Is it stored in some filesystem location?

**Comment by kucbd** [comment]
In our case, it could be either
- a dynamically created image stored under script-server/images 
```print('<img src="images/result4632468327.png" \>')```

or
- an image stream
```
from io import BytesIO 
flo = BytesIO()
ax.figure.savefig(flo,format="png", bbox_inches="tight")
print('<img src="data:image/png;base64,%s"/>' %  base64.encodebytes(flo.getvalue()).decode())
```

**Comment by bugy** [comment]
Hi @kucbd, thanks for the proposal. There are a couple of concerns:
1. I would like to avoid parsing html tags in the script output. It can be used for some hijacking and also complicates output parsing 
2. I think it would be better if nobody would have to modify their scripts to make Script server work (if possible). 

In your current script, do you log the image filename somehow? And do you have to show images during script execution, or only when a script is finished?

**Comment by kucbd** [comment]
I fully agreed to 1) and 2)
We know the image filenames as the python script is generating it based on the input data. Ultimately we would like to be able to show images during script execution, but even showing images when a script is finished is already a big advantage.

**Comment by bugy** [comment]
I would suggest to reuse output files functionality. In this case your script will write a file somewhere, and print the path, so that Script server will be able to find it

And then in the configuration we can have:
```
"output_files": [
	{
             "type": "inline-image",
             "path": "##any_path/[0-9]{8}.png#"
        }
]
```
(`"path": "##any_path/\w+.png#"` syntax mean: find any path, ending with .png, in the output)

And then Script server will parse output logs in real-time and if he finds a log statement with a png, it will insert an image after it.

**Comment by kucbd** [comment]
When I try this suggestion, I  unfortunately get 
`2019-08-24 14:30:46,416 [script_server.execution_service.ERROR] Could not notify finish listener (<function FileDownloadFeature.subscribe.<locals>.execution_finished at 0x7f8040566f28>), execution: 152
Traceback (most recent call last):
  File "src/execution/execution_service.py", line 211, in _fire_execution_finished
    callback(execution_id)
  File "src/features/file_download_feature.py", line 47, in execution_finished
    owner)
  File "src/features/file_download_feature.py", line 71, in _prepare_downloadable_files
    script_param_values)
  File "src/features/file_download_feature.py", line 119, in substitute_parameter_values
    substituted_file = fill_parameter_values(parameter_configs, output_file, values)
  File "src/model/model_helper.py", line 157, in fill_parameter_values
AttributeError: 'dict' object has no attribute 'replace'`

**Comment by bugy** [comment]
Hi, I'm totally sorry for confusing you: it was just a proposal. You can try current "output_files" behavior using
```
"output_files": [
            "##any_path/[0-9]{8}.png#"
]
```

**Comment by kucbd** [comment]
ahh ... I see. I was too fast trying it out :-)
The proposal sounds great!

**Comment by bugy** [comment]
Done.
To use this feature you can use the configuration from above:
```
"output_files": [
	{
             "type": "inline-image",
             "path": "##any_path/[0-9]{8}.png#"
        }
]
```

**Comment by kucbd** [comment]
It works great!
![Screenshot_script_server_inlineimage](https://user-images.githubusercontent.com/54399273/64420223-0f80fd80-d09f-11e9-973b-efac21b548c0.png)

**Comment by bugy** [comment]
Hi @kucbd thanks for confirming!
