### ISSUE TITLE
File upload does not work under Safari

### ISSUE THREAD

**Issue by kucbd** [bugy/script-server#232]
Under Safari on Mac the File upload field returns NoneType as the file field does not get the filename value. It works fine in Chrome (Version 75.0.3770.142)

Safari Version 12.1.2 (14607.3.9) 
MacOS Mojave 10.14.6

**Comment by bugy** [comment]
Seems like a Safari bug: https://bugs.webkit.org/show_bug.cgi?id=149398

**Comment by bugy** [comment]
Fixed
