### ISSUE TITLE
Did something changed with nginx proxy username authentication?

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#238]
I think that after a apt upgrade on my server, I now get 403 forbidden when accessing the script-server.

Same setup, nothing changed, password and username were saved in browser.

It seems to not be using my username anymore and instead went back to the IP, but it worked for ages...

```
2019-10-30 16:48:51,852 [identification.INFO] Assigned user_id=IP-9186a420abd443b6 to {'proxied_username': 'admin', 'proxied_ip': 'IP', 'proxied_hostname': 'pinkiepie.optical-server.com', 'ip': '172.18.0.8', 'hostname': 'nginx-proxy.cloudbox'}
2019-10-30 16:48:51,852 [web_server.WARNING] User IP-9186a420abd443b6 is not allowed
2019-10-30 16:48:51,852 [tornado.general.WARNING] 403 GET /index.html (172.18.0.8): Access denied. Please contact system administrator
```

**Comment by Nottt** [comment]
Yes I'm talking about #219.

It's weird because I didn't touch any configuration files and they were working before.. It is possible that my nginx docker updated to a newer nginx but that shouldn't affect it right?

my conf.json

````
{
   "port":5000,
   "address":"0.0.0.0",
   "title":"WebUI",
   "access":{
      "allowed_users":[
         "admin",
         "90994",
         "771313",
         "170605",
         "510701",
         "489995",
         "111780"
      ],
      "admin_users":[
         "admin"
      ],
      "user_header_name":"X-Auth-Name",
      "trusted_ips":[
         "172.18.0.2"
      ],
      "logging":{
         "execution_file":"$DATE-$ID.log",
         "execution_date_format":"%y-%m-%d_%H-%M"
      }
   }
}
````

my nginx vhost file

```
auth_basic           "Script server auth";
auth_basic_user_file /etc/nginx/htpasswd/domain.com;
proxy_set_header X-Auth-Name $remote_user;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Origin http://$proxy_host;
```

**Comment by Nottt** [comment]
Never mind, my nginx docker was assigning a different IP so the trusted_ips was wrong. Is there a way to make any IP trusted since it's only possible to reach this server from the reverse proxy?

**Comment by bugy** [comment]
Hi @Nottt, sorry for the late reply. Unfortunately, it's not possible to allow all IPs at the moment
