### ISSUE TITLE
Can we add new scripts through UI? Instead of adding them via runners folder

### ISSUE THREAD

**Issue by cinguva** [bugy/script-server#241]

**Comment by bugy** [comment]
Hi, @cinguva do you mean the new admin web page? 
Adding new scripts will be done there sometime soon

**Comment by cinguva** [comment]
> Hi, @cinguva do you mean the new admin web page?
> Adding new scripts will be done there sometime soon

Can we expect in which release and by when we can have this feature?

**Comment by bugy** [comment]
Hi @cinguva, since I'm working on this project in my free time, which is not very schedulable, I cannot give you any good estimates. I would expect 1-2 weeks for the dev version, but can be more

**Comment by bugy** [comment]
Done, closing this ticket in favor of #127
