### ISSUE TITLE
Divide scripts in groups

### ISSUE THREAD

**Issue by hifi25nl** [bugy/script-server#243]
I have many scripts that I would like to use with script-server
Ideal would be to make different groups with specific titles

Is this possible?

**Comment by bugy** [comment]
Hi @hifi25nl,
unfortunately, this is not possible. I was thinking about this feature since the very beginning of the project, but I had never really needed it for myself :)

I'll keep this issue open as a feature request

**Comment by muzzol** [comment]
as a simple workaround i always put a prefix to titles so you can filter easily:

```
MAIL - List users
MAIL - Add alias
WEBPRE - Restart Apache
WEBPRO - Restart Apache
LDAP - Check password

```

and so on...

**Comment by hifi25nl** [comment]
Yes, I m doing it now this way:

11 MAIN name1
12 MAIN name2
---
21 SYSTEM name1
22 SYSTEM name2
23 SYSTEM name3

etc.

**Comment by muzzol** [comment]
@bugy can I suggest detecting automatically subsections?

some dinamic sites do it that way.
you can use a delimiter in name to define a section.

for example if name is **WEB:** it automatically creates a section called WEB and put that item inside.

**Comment by bugy** [comment]
Hi @muzzol, thanks for the idea, I like it!
But I think this should be optional somehow. And also, if you check the example from @hifi25nl, this won't work :)

**Comment by hifi25nl** [comment]
Working with scripts, I discovered that if I change the script name link after creation the corresponding file name in /conf directory is not changed.

I fear that this could lead to unpredictable results.

**Comment by bugy** [comment]
Done
You can use `"group": "groupName"` in a script config now

**Comment by deelerke** [comment]
YES !!!! perfect !! PERFECT !!!! thank you

**Comment by antonellocaroli** [comment]
perfect!!!!

Can you explain how this works?

**Comment by antonellocaroli** [comment]
Okay, got it.

it works
