### ISSUE TITLE
Simple login to server with user and password

### ISSUE THREAD

**Issue by hifi25nl** [bugy/script-server#244]
I would like to enable a very simple login with user an clear text password to server.

If possible one login as user and one login as administrator where only the last one can edit or create new script links.
If I understand right I must edit the file /conf/conf.json
Using the example on the site I have always an error like this:
json.decoder.JSONDecodeError: Expecting ',' delimiter

Could you show me a very simple authentication configuration?

**Comment by bugy** [comment]
Hi @hifi25nl, for authentication there are multiple options:
1. Integrate with LDAP server
2. Integrate with Google OAuth server
3. Authenticate users by IP
4. Get authentication, provided by reverse proxy 
Depending on your case, I could send you an example.

Unfortunately, Script server doesn't have its own authentication where you could specify users/passwords. 
There is a request to implement it #159, which is not yet done

**Comment by bugy** [comment]
Now as #159 is implemented, I think what you ask should be possible
It's not exactly cleartext password, but I think htpasswd is good, safe and simple enough
