### ISSUE TITLE
How to execute script only if a single parameter is given

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#246]
```
      {
         "name":"ID",
         "type":"text",
         "required":false
      },
      {
         "name":"NAME",
         "type":"text",
         "required":false
      }
```

Given those parameters, and a single script that will execute different stuff based if a ID or NAME is given how you would do this?

I can't use `if [ ! -z "$1" ]` for example. Because if someone only gives a name, it will be `$1` and vice versa. 

I tried to use `"param":"2",` in my json because I thought that way I could control that `$1` will always be a ID and $2 a NAME

**Comment by bugy** [comment]
Hi @Nottt unfortunately, that's not possible. If parameter is not specified, it's not passed at all

**Comment by Nottt** [comment]
So what I should do to accomplish what I want? I don't want to clutter the UI with lots of scripts

**Comment by Nottt** [comment]
So what I should do to accomplish what I want? I don't want to clutter the UI with lots of scripts.

I'm not sure you understood me...what I saying is that I want to control inside the script what variable is what...

Either by controlling the order (e.g first parameter is always $1, second is $2) or by other means... like I define that first parameter will be variable X so I can use that with if statements

**Comment by bugy** [comment]
I believe there is no automated solution in Script server.

In my scripts i always used named parameters (e.g. -p1 xxx -p2 yyy) in such
cases

In Script server, you can accomplish it by using param field
But it would require some modifications of your script

There is a feature request: https://github.com/bugy/script-server/issues/181
I can implement it next week, probably

Nottt <notifications@github.com> schrieb am Mo., 23. Dez. 2019, 19:13:

**Comment by bugy** [comment]
Sorry, may be it was confusing. The approach with "param" field is there
already

The feature request is for another approach, which will make everything way
easier for you

Yaroslav Shepilov <buggygm@gmail.com> schrieb am Mo., 23. Dez. 2019, 19:27:

**Comment by Nottt** [comment]
+1 for #181 :smile: 

I think I'm using "param" wrong then. 

```
      {
         "name":"ID",
         "type":"text",
         "param":"id",
         "required":false
      },
      {
         "name":"Nome",
         "type":"text",
         "param":"name",
         "required":false
      }
```

With this script:

```
echo $id
echo $name
```

Doesn't work.

**Comment by bugy** [comment]
Yes, it works differently, if you have parameters id and name, with the
values 123 and Nottt, for example, then the script will be called like this

myScript.sh id 123 name Nottt,

So $1 will be id, $2 = 123, $3 = name, $4 = Nottt

You can use getopts or alternatives to "parse" it

The feature request #181 is exactly about how you are trying to use it now
:) so you will have $ID and $NAME variables additionally

Nottt <notifications@github.com> schrieb am Mo., 23. Dez. 2019, 19:34:

**Comment by Nottt** [comment]
Thanks for the support! This is working:

```
      {
         "name":"ID",
         "type":"text",
         "param":"-id",
         "required":false
      },
      {
         "name":"Nome",
         "type":"text",
         "param":"-name",
         "required":false
      }
```

In the script:

```
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -id)
    ID="$2"
    shift
    shift
    ;;
    -name)
    NAME="$2"
    shift
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}"

```

**Comment by bugy** [comment]
I added a ticket (#247) to address this problem in a different manner: by always passing parameters, even if they are empty
In this case $1 parameter would exist and `if [ ! -z "$1" ]` check will work properly (because the value will be empty)
