### ISSUE TITLE
Add button to copy output of script

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#258]
It'd be nice to have this feature :)

Also I think you should put some donation information in your readme

**Comment by bugy** [comment]
Done. The button is in the right bottom corner of the output panel
![ - 22](https://user-images.githubusercontent.com/1275813/77835036-dc40b180-7149-11ea-828b-81c4ce2d5739.png)

**Comment by Nottt** [comment]
restarted my docker and I picked the change. Isn't it better to have it right upper corner? In a big screen you'd have to move the mouse all the way down to copy and the go up again. 

but regardless, awesome job as always! thanks
