### ISSUE TITLE
feature request: grouping of scripts

### ISSUE THREAD

**Issue by deelerke** [bugy/script-server#259]
would be cool to have scripts grouping, so you can expand/collapse groups with scripts in

**Comment by bugy** [comment]
Hi @deelerke, thank you for the feature request
There is already a similar ticket: #243, so I'll close this one

**Comment by deelerke** [comment]
ok, sorry, thank you

    On Wednesday, January 22, 2020, 2:35:14 PM GMT+1, Iaroslav Shepilov <notifications@github.com> wrote:  
 
 
Hi @deelerke, thank you for the feature request
There is already a similar ticket: #243, so I'll close this one

**Comment by bugy** [comment]
Done, you can test it on latest dev build
