### ISSUE TITLE
Issue whe trying to run scripts

### ISSUE THREAD

**Issue by HerzGegenFame** [bugy/script-server#264]
Hello, everytime i try to run scripts i get the following error in the Browser:
```
Failed to load script info. Try to reload the page. Error message:
Failed to connect to the server
```

And in the cli i get this:
```
020-02-06 09:54:20,765 [web_server.ERROR] Failed to load script config shuttrunk
Traceback (most recent call last):
  File "src/web/server.py", line 253, in open
    load_config_future = tornado.ioloop.IOLoop.current().run_in_executor(executor=None, func=functools.partial(
AttributeError: 'EPollIOLoop' object has no attribute 'run_in_executor'

```

**Comment by bugy** [comment]
Hi, thanks for reporting! which version of tornado and python are you using?

HerzGegenFame <notifications@github.com> schrieb am Do., 6. Feb. 2020,
09:56:

**Comment by HerzGegenFame** [comment]
Hello, thanks for the quick reply. 
My tornado version is 4.5.3-1ubuntu0.1
My python version is 2.7.15~rc1-1

**Comment by bugy** [comment]
Unfortunately supported versions are tornado >= 5, and python >=3.5

HerzGegenFame <notifications@github.com> schrieb am Do., 6. Feb. 2020,
10:12:

**Comment by HerzGegenFame** [comment]
My python version now is 3.6.7-1~18.04
And my tornado version is 5.1.1

now my error looks like this:

```
2020-02-06 10:27:52,863 [web_server.ERROR] Failed to load script config shuttrunk
Traceback (most recent call last):
  File "src/web/server.py", line 253, in open
    load_config_future = tornado.ioloop.IOLoop.current().run_in_executor(executor=None, func=functools.partial(
AttributeError: 'EPollIOLoop' object has no attribute 'run_in_executor'

```

**Comment by bugy** [comment]
Hi @HerzGegenFame, I believe you are still running with Tornado 4. The attribute `run_in_executor` was added in Tornado 5

How do you run script server? By just running `./launcher` ?
If yes, could you check the output of the following command, please:
`/usr/bin/env python3 -c "import pkg_resources; print(pkg_resources.get_distribution('tornado').version)"`

**Comment by HerzGegenFame** [comment]
Hey, 
yeah it seems like i´m still running 4.53
Output is:
`4.5.3`

**Comment by HerzGegenFame** [comment]
I was able to solve the problem. i needed to delete python-tornado manually
so
`rm-rf /usr/lib/python3/dist-packages/tornado
#and 
rm -rf /usr/lib/python3/dist-packages/tornado-4.5.3.egg-info/
`

Thanks for responding so quickly.

Einen schönen Tag noch :)
