### ISSUE TITLE
Proposed upgrade script

### ISSUE THREAD

**Issue by tristanlatr** [bugy/script-server#276]
Hello,

I've been using script-server at work for a long time and it's working great. Thanks.

## Upgrading script-server (Linux)

Here is a script that is supposed to upgrade painlessly your script-sever install.  

### Usage
- Save script in your system
- Configure hard-coded variables
- Execute it as root
```
$ sudo upgrade.sh 1.5.2
```

### Requirements:
- Correctly set up script-server as a service on your Linux server. See 
- The service must be running when calling the script
- `unzip` and `wget` commands

### Warning: 
- This will move all your content in the installation folder to a backup directory named as the script-server install with datetime string like `%Y-%m-%dT%H-%M-%S` 
- Replace all files contained in the install directory 
- If you're using default `conf` directory, your configs files will be moved to the backup directory too.

### You must configure manually some variables
- `scriptServerService`: The name of the Script-Server service
- `scriptServerUser`: The name of the user who run the service
- `scriptServerInstall`: Folder of the source files.

##### `upgrade.sh`

```bash
#!/bin/bash
#
# Script-Server upgrade script
#
# Usage: upgrade.sh <Version>
# Usage: sudo upgrade.sh <Version>
# Usage: echo "myPAssw0rd" | sudo -S upgrade.sh <Version>
# Usage: echo "$SUDO_PASSWD" | sudo -S upgrade.sh <Version>
#
# Setting bash strict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
# Script will stop if error occurs
set -euo pipefail
# 
# scriptServerService: The name of the Script-Server service
scriptServerService="script-server"
# 
# scriptServerUser: The name of the user who run the service
scriptServerUser="script-server"
# 
# scriptServerInstall: Folder of the source files.
scriptServerInstall="/home/script-server/script-server"
#
#
datestr=`date +"%Y-%m-%dT%H-%M-%S"`
#
#
# Upgrade begin
cd /tmp/
echo "Backing up sources to ${scriptServerInstall}-${datestr}"
cp -r ${scriptServerInstall} ${scriptServerInstall}-${datestr}
echo "Cleaning temp files"
rm -rf script-server 2>/dev/null || true
rm -f script-server.zip 2>/dev/null || true
echo "Downloading new script-server sources"
wget https://github.com/bugy/script-server/releases/download/$1/script-server.zip
echo "Exracting..."
mkdir script-server
unzip ./script-server.zip -d ./script-server
echo "Service status"
service ${scriptServerService} status
echo "Stopping service"
service ${scriptServerService} stop
echo "Removing current sources."
rm -rf "${scriptServerInstall}/.*"
echo "Moving new source files"
cp -r ./script-server/* ${scriptServerInstall}
echo "Changing ownership of source files"
chown ${scriptServerUser}:${scriptServerUser} ${scriptServerInstall}
echo "Starting service"
service ${scriptServerService} start
echo "Service status"
service ${scriptServerService} status
```

Tell me if you like it, could be added to the Wiki maybe ?

Thanks

**Comment by tristanlatr** [comment]
It has been working well on Oracle Linux 6 and 7 to upgrade from version 1.4 to 1.5.2

**Comment by bugy** [comment]
Hi @tristanlatr, thanks a lot! I added it to the wiki: https://github.com/bugy/script-server/wiki/Upgrade-script-(linux)
