### ISSUE TITLE
Show an indicator when a script is loading

### ISSUE THREAD

**Issue by antonellocaroli** [bugy/script-server#281]
couldn't you make the description appear right away?
before the scripts in the parameters are queried?
I have some scripts in the parameters that take some time, so a user might think the system is locked, entering a description of this would make it clear to the user to wait for the query of the script...

**Comment by bugy** [comment]
Hi antonellocaroli,
good idea. But what do you think about a progress bar instead? Or may be
both

antonellocaroli <notifications@github.com> schrieb am So., 29. März 2020,
08:38:

**Comment by bugy** [comment]
As an example, there is a progress bar in a history section

antonellocaroli <notifications@github.com> schrieb am So., 29. März 2020,
08:38:

**Comment by antonellocaroli** [comment]
the progress bar would be great.
but in the history section, I see it's not very visible.

it would be nice to have it either right under the title, or even better on the EXCUTE button.

like the EXCUTE button becomes WAIT...with a progress bar underneath and when finished it becomes EXCUTE.

**Comment by bugy** [comment]
Done, now script loading will have a progress indicator under header (I also made it for history section)
Also, there will be a loading text and execute button will be disabled. 

Could you please check, if it works for you, please?

**Comment by antonellocaroli** [comment]
@bugy 
That's great!!
Thank you!!!!
it works fine!
:)

Loading ....... what a lovely weather today ........ patience is power ......... doing my best .......... I give up :(

**Comment by bugy** [comment]
Wow, it takes more than 30sec to load the script Oo I hoped nobody would read the last message

**Comment by antonellocaroli** [comment]
maybe just "i give up" comes "too soon." ?

I have long scripts :)

**Comment by bugy** [comment]
Well, usually people are fine for waiting 3-5 sec in such services. 30 sec for me sounds already quite a lot
Probably I need to change this message. "I give up" sounds like the loading is finished, but actually it's not

**Comment by antonellocaroli** [comment]
I've changed it so far.

 Loading ....... I'm still alive ........ some bits got stuck ......... don't leave me .......... waiting :)

**Comment by antonellocaroli** [comment]
Still great!!!!
I really like it!!!!

**Comment by bugy** [comment]
@antonellocaroli I changed the last message to "loading time is unknown". So if you want, you can use it and avoid custom changes on your side
