### ISSUE TITLE
Migrate project to vue-cli 3

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#282]
At the moment webpack + babel + karma + plugins are used for frontend building and unit testing.
Unfortunately, it causes a lot of headache in configuration (many people use different combinations and versions, so it is extremely hard to find working solution anywhere). Especially it causes problems for unit testing (making everything built and tested properly is not trivial).
Another problem is bundle size. At the moment, Script server has almost 1Mb for the index page (600Kb js, 200Kb css, and everything else).

To solve these problems and make frontend infrastructure more lightweight, it makes sense to migrate to vue-cli, which uses predefined set of tools and plugins

**Comment by bugy** [comment]
Done, now script server uses almost latest versions build frameworks and vue cli. It makes configuration easier and builds faster
Also, new `vue-cli serve` command works faster and cooler

And the main benefit during this migration: sources for index page were reduced from 1.5Mb to around 300Kb (gzipped)

@antonellocaroli I know, that you do some customizations of Script server UI and my changes are definitely breaking changes for you. Really sorry about it. 
If you would need some help, feel free to contact me directly, I will be glad to help you
And now I owe you one feature: will take one issue from you with the highest priority :)

**Comment by antonellocaroli** [comment]
@bugy I'm glad you know my project...

now I'm gonna try the new script-server and let you know if I have any problems...

> And now I owe you one feature: will take one issue from you with the highest priority :)

:) :)
