### ISSUE TITLE
Admin interface: allow script creation/upload

### ISSUE THREAD

**Issue by jagerzhang** [bugy/script-server#284]
Hi，We hope to support online management script and scheduled execution.

**Comment by bugy** [comment]
Hi @jagerzhang , for the scheduling please check this ticket:
https://github.com/bugy/script-server/issues/180#issuecomment-541411834 (and especially linked comment)

For online management, there is an admin page: https://github.com/bugy/script-server/wiki/Admin-interface

**Comment by jagerzhang** [comment]
@bugy Thanks for replay. :)
The online management feature I mean to be able to edit scripts online and then store them.

**Comment by bugy** [comment]
Got it. I would call it "allow script creation/upload from the admin interface" and keep this ticket as a feature request. 
Unfortunately, I won't have time to work on it in the nearest future (there are quite some other issues).

**Comment by jagerzhang** [comment]
Yes it is.
Of course, it's better if you can store scripts in a storage cluster like mysql.

**Comment by bugy** [comment]
Done. Now you can decide to edit path or click a button on the right and choose other edit modes (code editor or upload):
![image](https://user-images.githubusercontent.com/1275813/119256029-ea0f8c80-bbbe-11eb-9d2f-bea39cf0c0b9.png)

The scripts for **new** configurations are uploaded to `./conf/scripts`
The scripts for **existing**  configurations are uploaded to the same path as specified in Script path
