### ISSUE TITLE
Use logged user as variable inside scripts

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#285]
Is it possible to have a script use the logged user as a variable inside the scripts

**Comment by bugy** [comment]
Hi @Nottt, yes, if you pass it as a parameter
https://github.com/bugy/script-server/wiki/Script-config#--default

**Comment by Nottt** [comment]
Is that true even if I'm using the nginx authentication ?

**Comment by bugy** [comment]
Yes, if you enabled https://github.com/bugy/script-server/wiki/Server-configuration#--user_header_name
then you would be able to access it via `${auth.username}`
Otherwise, it should be ${auth.audit_name}

**Comment by Nottt** [comment]
Thanks! Can you vie me an example? I can't get this working

```
   "parameters":[
      {
         "name":"Username",
         "type":"text",
         "required":true
      },
      {
         "constant":"true",
         "param": "-u",
         "default": "${auth.username}"
      }
   ]
```

With this when I try to open the script it says Failed to load script info. Try to reload the page.

I want my user to only input the username and use the logged username inside the script

**Comment by bugy** [comment]
Hi @Nottt, unfortunately, I cannot test proxy set up at the moment. It looks like proxied username is not picked up by Script server. Is `user_header_name` working for you at all?

But please try ${auth.audit_name} instead

**Comment by Nottt** [comment]
that worked. Thanks! awesome work as always

**Comment by Nottt** [comment]
When I try to run a script with only this:

```
{
   "name":"Test 3",
   "script_path":"scripts/test3.sh",
   "description":"Test 3",
   "allowed_users":[
      "admin"
   ],
   "parameters":[
      {
         "constant":"true",
         "param": "-u",
         "default": "${auth.audit_name}"
      }
   ]
}
```

I get this:

```
Calling the script...

 ---  ERRORS  --- 
Unknown error occurred, contact the administrator
```

This script doesn't need any input...so I just need the logged user param...any ideas?

**Comment by bugy** [comment]
Could you check server logs, please?

Nottt <notifications@github.com> schrieb am Fr., 3. Apr. 2020, 10:38:

**Comment by Nottt** [comment]
![image](https://user-images.githubusercontent.com/13532436/78341480-2cff4280-756e-11ea-97c9-ddc5c042a6f3.png)

**Comment by bugy** [comment]
damn... could you set the parameter name in the config? 
Looks like a bug: a name for constant shouldn't be needed. But in my recent changes I forgot about it...

**Comment by Nottt** [comment]
of course. no problem :) 

that fixed it

**Comment by bugy** [comment]
Thanks for reporting, I moved this to a separate ticket #287 
Probably will fix it in the nearest days (bugs are always highest priority here)

**Comment by Nottt** [comment]
np...may I ask something a bit off topic...

WIth this feature I no longer need to duplicate scripts only to change the variable $username but some of my scripts interact with a mysql database, and I can't retrieve the password from the database.

So currently I duplicate my scripts for every user that needs it, only to change the username and password. But is there a better way to do this?

Maybe I could store all user passwords plain text somewhere and get the correct one with logged user variable... but I don't know how I'd do it...

I accept suggestions :)

**Comment by bugy** [comment]
Hi, I think you could have an additional wrapping script, which will get a username from Script server, resolve a password from some file, and call your current script

**Comment by Nottt** [comment]
Something really weird is happening:

```
#!/bin/bash

set -x

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -u)
    REV_USERNAME="$2"
    shift
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}"
```

This code broke script-server so much I had to restart the container. And if I try to look at the history of the script, the chrome tab dies lol. so strange

**Comment by bugy** [comment]
Did you try running this script from a console?

Nottt <notifications@github.com> schrieb am Fr., 3. Apr. 2020, 16:04:

**Comment by Nottt** [comment]
No I didn't...but I got it working now...don't know what cause it...but it's all good now! thanks
