### ISSUE TITLE
Did you remove --dev from init.py

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#298]
My docker build started failing with this error...then I tracked it to `--dev` being removed from the init.py file...

What does that means for us ?

**Comment by bugy** [comment]
Hi @Nottt, sorry for the inconvenience :(

I moved to a new build system (#295) and decided to drop dev profile (it was more or less redundant anyway). Please just remove the flag

**Comment by Nottt** [comment]
OK. No problem.

```
# Install necessary packages

apt update > /dev/null 2>&1 && apt install curl -y > /dev/null 2>&1

# Retrieve files

curl -Ls https://github.com/bugy/script-server/archive/dev.tar.gz | tar xz --strip 1 -C /app > /dev/null 2>&1

# Install dependencies

curl -Ls https://raw.githubusercontent.com/bugy/script-server/master/requirements.txt | pip install -r /dev/stdin
```

Is this this still current to keep using your dev releases?

**Comment by bugy** [comment]
Yes, it should be fine. I changed only web build part.  Everything else is kept untouched
