### ISSUE TITLE
Weird commands showing up when trying to execute script

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#302]
I have a very simple bash script, that is just a `cd /dir && ./script.sh` but when I execute it I see this weird stuff?

```
+ '[' -z '\s-\v\$ ' ']'
+ shopt -s checkwinsize
+ '[' -z '' ']'
+ '[' -r /etc/debian_chroot ']'
+ '[' -n '' -a -n '' ']'
+ PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+ '[' -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ']'
bash: /root/.bashrc: Permission denied
tornado@fa129eebf689:/app$ 
```

If I go inside the docker, as the `tornado` user, and `cd` to the folder, and execute my script, it works. But via web interface I get this weird stuff here

**Comment by bugy** [comment]
I believe piped commands are not supported (due to security reasons)
Please use [working_directory](https://github.com/bugy/script-server/wiki/Script-config#working_directory) instead of `cd /dir`

**Comment by Nottt** [comment]
OK I have done that...now it seems like the script is being run as root instead of the tornado user?

My working directory is in `/opt` and uses rclone

**Comment by bugy** [comment]
The script should be run with the same user, as your run script server.

I mean, Linux won't allow a normal user to run anything as root. Only root can start other processes as root

And in script server there is no feature like "run as", it just spawns child processes

**Comment by Nottt** [comment]
I don't know then...rclone is trying to open `/root/.config/rclone` for the configuration file, which means it's somehow running as root.

But I'll make it work anyway

**Comment by Nottt** [comment]
This is happening to me again, and I'm not using piped commands... What else could cause this? The commands I'm running are also not directory specific

**Comment by bugy** [comment]
Hi @Nottt do you have a sample script and a Script server configuration for it?

**Comment by bugy** [comment]
Hi @Nottt, do you still have this problem?

**Comment by Nottt** [comment]
No, it stopped
