### ISSUE TITLE
Feature request: Search box in multiselect

### ISSUE THREAD

**Issue by autogun** [bugy/script-server#303]
I came across the need of enabling a large multiselect list of values. A search box to filter relevant pick(s) would be super nice. Just a thoguth...

**Comment by autogun** [comment]
Oh my, now saw this https://github.com/bugy/script-server/issues/188

_Duplicate_, closing.

**Comment by autogun** [comment]
@bugy Seems like #188 addresses only `list` type. Is  there a reason why `!this.config.multiselect` is in https://github.com/bugy/script-server/blob/e81bffa8e66a76df55f6966fd03bab6a7dd3a712/web-src/src/common/components/combobox.vue#L51

**Comment by bugy** [comment]
Hi @autogun to be honest I don't remember. There are 2 potential reasons:
1. It can interact with multiselect in a wrong manner (when to close/open the dropdown, when user clicks somewhere)
2. If can be a bit weird from UX perspective, because you are hiding already selected options

You can try to remove this check and see if it will work

**Comment by autogun** [comment]
@bugy I did try, it works as expected. Hence wanted to check maybe I miss something here.
There is one UI glitch which I find annoying and that's when scrolled text of a `multiselect` list with a search on top is getting over the search text itself.
![image](https://user-images.githubusercontent.com/11921235/87287653-0785bb80-c503-11ea-9023-5dc6f84e2e1b.png)![image](https://user-images.githubusercontent.com/11921235/87287789-300db580-c503-11ea-9133-6acb93d871a0.png)

This is fixed with a tiny `z-index: 1` on `combobox-search-header`.

Would you accept a PR on this?

**Comment by autogun** [comment]
@bugy See https://github.com/bugy/script-server/pull/321

**Comment by autogun** [comment]
Closing.
