### ISSUE TITLE
Support of --arg= arguments

### ISSUE THREAD

**Issue by miksir** [bugy/script-server#308]
Hi! I got a request for support --arg=value. Currently there is no options to do it because space added between argument name and value. I can see two ways - separate options for it (do_not_add_space \o/) or transparent behaviour - if arg name ended with = - do not include space. What you think about second way?

**Comment by bugy** [comment]
@miksir let's continue the discussion in a similar ticket: https://github.com/bugy/script-server/issues/288 :)
