### ISSUE TITLE
Suggesting dash/plotly output

### ISSUE THREAD

**Issue by tsp-kucbd** [bugy/script-server#312]
It would be awesome if script-server will support Dash or Plotly (https://plotly.com/) output. Maybe that will be possible if direct html output will be supported?

**Comment by bugy** [comment]
I think HTML would be the most flexible approach. Would it be enough?
I'll keep here reference for it #245

**Comment by kucbd** [comment]
yes, I think so

**Comment by bugy** [comment]
Closing in favor of #245
