### ISSUE TITLE
Set user cookie expiration duration

### ISSUE THREAD

**Issue by jtprof** [bugy/script-server#313]
Hi Iaroslav,

Could you please advice way how to change 'username' cookie expires duration?
One mount which is set by default is too long.

Thank you in advance.

**Comment by bugy** [comment]
Hi, you mean 30 days expiration? 
Unfortunately it's not configurable at the moment

You can change the code in src/auth/tornado_auth.py:73
`request_handler.set_secure_cookie('username', username, expires_days = 7)`

**Comment by jtprof** [comment]
Thank you.

**Comment by bugy** [comment]
Fixed in #316
