### ISSUE TITLE
Can't use rich to print output in python script

### ISSUE THREAD

**Issue by srqjan** [bugy/script-server#323]
I have problem printing script output when using rich https://github.com/willmcgugan/rich
for some reason, i can't print script output when script is called from script-server
in terminal everything is fine

there is no visible output in script server

if i use python3 print function i am getting this output
<rich.table.Table object at 0x7f3b2b488400>

This is log file (logs/processes)
root@athene:/home/srdjan/script-server/logs/processes# cat GPON__ONT_RFO_LOSS_Report_192.168.128.132_200724_143245.log
id:2460
user_name:192.168.128.132
user_id:192.168.128.141-04f1204895df4625
script:GPON _ONT RFO LOSS Report
start_time:1595601165629
command:/home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
exit_code:0
>>>>>  OUTPUT STARTED <<<<<

**Comment by bugy** [comment]
@srqjan thanks for reporting.
Is it really nothing after OUTPUT STARTED? :open_mouth:

**Comment by srqjan** [comment]
Actually , just empty space, you may see my terminal prompt at the bottom

root@athene:/home/srdjan/script-server/logs/processes# cat GPON__ONT_RFO_LOSS_Report_192.168.128.132_200724_143245.log
id:2460
user_name:192.168.128.132
user_id:192.168.128.141-04f1204895df4625
script:GPON _ONT RFO LOSS Report
start_time:1595601165629
command:/home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
exit_code:0
>>>>>  OUTPUT STARTED <<<<<
 














 
 






















root@athene:/home/srdjan/script-server/logs/processes#

**Comment by bugy** [comment]
Wow, that's really weird. No idea what kind of magic this Rich library does then :) I'll have to test it myself

**Comment by srqjan** [comment]
Ok , it will be amazing if you can integrate rich with script server.

Best Regards

**Comment by willmcgugan** [comment]
Author of Rich here. Happy to help if you need it. Suspect is related to capturing stdout somehow...

**Comment by bugy** [comment]
Hi @willmcgugan, thanks for you help!
Is Rich using some standard ANSI escape codes? Or how does the formatting work?

Script server just captures stdout from running processes, without any processing.

**Comment by willmcgugan** [comment]
It will write standard ANSI escape codes, but if Rich detects its not writing to a terminal it will disable all escape codes and just write plain text.

What environment variables to set to run a process? Do you set COLUMNS ?

You might want to try this, as the simplest possible script using Rich...

```python
from rich import print
print("[bold magenta]Hello World!")
```

**Comment by bugy** [comment]
Hi @willmcgugan, you were right, COLUMNS is the reason. I don't set any, I just run python subprocess and grab output
I tried setting columns to 80 and the example worked fine

@srqjan could you try setting the env variable also, please?

**Comment by willmcgugan** [comment]
I tested it myself (cool project btw). Oddly `shutil.get_terminal_size()` always returns (0, 0).

Rich attempts to word wrap to a width of 0 which is why nothing is printed. I see why setting COLUMNS fixes it, bit it shouldn't be necessary as get_terminal_size should fall back to 80 if it can't auto-detect the width.

**Comment by bugy** [comment]
@willmcgugan great thanks for looking into it and helping!
I'm using https://docs.python.org/3/library/pty.html for terminal emulation (so that called scripts think that they are executed in a terminal mode). 
Apparently this guy is not setting windows size. Actually there is no concept of window size in Script server at all. Users can resize their browser as they like, and there might be multiple windows open for the same output (each with a different size)

So I think the correct approach here would be to advise everyone to use COLUMNS env variable with high value (e.g. 300)

**Comment by willmcgugan** [comment]
That sounds like a reasonable fix, but it might be better to set it to something lower. Rich does word wrapping and tables with unicode box characters which might not look so good when wrapped in html.

**Comment by bugy** [comment]
Got it, thanks!
I checked it and on my monitor and resolution, there is 195 characters width. So smth like 150 would be reasonable enough

**Comment by srqjan** [comment]
My env COLUMNS in linux is 
root@athene:/home/srdjan/script-server/conf/runners# echo $COLUMNS
150

I 've created env variable in python script as you suggest, but still have a problem
os.environ['COLUMNS'] = '150'

But 
id:2471
user_name:192.168.128.132
user_id:192.168.128.141-04f1204895df4625
script:GPON _ONT RFO LOSS Report
start_time:1595709034044
command:/home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
exit_code:1
>>>>>  OUTPUT STARTED <<<<<
 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-70: ordinal not in range(128)

**Comment by willmcgugan** [comment]
Try setting env var `PYTHONIOENCODING=utf8`

**Comment by srqjan** [comment]
I alredy added env var in python script 
os.environ['PYTHONIOENCODING'] = 'utf-8'

Unfortunately ,  still im getting unicode error : UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-70: ordinal not in range(128)
Printing to terminal works fine.

**Comment by bugy** [comment]
Do you have full stack trace?

srqjan <notifications@github.com> schrieb am So., 26. Juli 2020 08:18:

**Comment by srqjan** [comment]
No , i am getting just unicode message 

![image](https://user-images.githubusercontent.com/16043616/88473718-9ab9ea80-cf20-11ea-8e49-de293ac1e1ed.png)

**Comment by bugy** [comment]
could you check logs/server.log file on server, please?

**Comment by srqjan** [comment]
This is log for today
2020-07-26 02:41:23,104 [tornado.access.INFO] 101 GET /scripts/GPON%20_ONT%20RFO%20LOSS%20Report (192.168.128.141) 3.52ms
2020-07-26 02:41:23,110 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 08:17:43,393 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 08:17:43,413 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 08:17:43,421 [web_server.INFO] Calling script GPON _ONT RFO LOSS Report. User {'ip': '192.168.128.141'}
2020-07-26 08:17:43,421 [script_server.execution_service.INFO] Calling script #2479: /home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
2020-07-26 08:17:43,430 [tornado.access.INFO] 200 POST /executions/start (192.168.128.141) 43.44ms
2020-07-26 08:17:43,610 [tornado.access.INFO] 101 GET /executions/io/2479 (192.168.128.141) 1.24ms
2020-07-26 08:17:45,173 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 08:17:45,173 [web_server.INFO] 192.168.128.141 disconnected
2020-07-26 08:17:45,220 [tornado.access.INFO] 200 POST /executions/cleanup/2479 (192.168.128.141) 1.98ms
2020-07-26 09:09:29,412 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:09:29,418 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:09:29,429 [web_server.INFO] Calling script GPON _ONT RFO LOSS Report. User {'ip': '192.168.128.141'}
2020-07-26 09:09:29,430 [script_server.execution_service.INFO] Calling script #2480: /home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
2020-07-26 09:09:29,439 [tornado.access.INFO] 200 POST /executions/start (192.168.128.141) 33.77ms
2020-07-26 09:09:29,626 [tornado.access.INFO] 101 GET /executions/io/2480 (192.168.128.141) 2.19ms
2020-07-26 09:09:31,487 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:09:31,488 [web_server.INFO] 192.168.128.141 disconnected
2020-07-26 09:09:31,808 [tornado.access.INFO] 200 POST /executions/cleanup/2480 (192.168.128.141) 2.38ms
2020-07-26 09:14:31,351 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:14:31,357 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:14:31,366 [web_server.INFO] Calling script GPON _ONT RFO LOSS Report. User {'ip': '192.168.128.141'}
2020-07-26 09:14:31,367 [script_server.execution_service.INFO] Calling script #2481: /home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
2020-07-26 09:14:31,377 [tornado.access.INFO] 200 POST /executions/start (192.168.128.141) 31.23ms
2020-07-26 09:14:31,534 [tornado.access.INFO] 101 GET /executions/io/2481 (192.168.128.141) 1.92ms
2020-07-26 09:14:33,213 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:14:33,213 [web_server.INFO] 192.168.128.141 disconnected
2020-07-26 09:14:33,291 [tornado.access.INFO] 200 POST /executions/cleanup/2481 (192.168.128.141) 1.95ms
2020-07-26 09:19:21,708 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:19:21,725 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:19:21,734 [web_server.INFO] Calling script GPON _ONT RFO LOSS Report. User {'ip': '192.168.128.141'}
2020-07-26 09:19:21,735 [script_server.execution_service.INFO] Calling script #2482: /home/srdjan/script-server/conf/runners/rich_ma4k_ltp_high_loss_detailed.py 24
2020-07-26 09:19:21,744 [tornado.access.INFO] 200 POST /executions/start (192.168.128.141) 42.08ms
2020-07-26 09:19:22,071 [tornado.access.INFO] 101 GET /executions/io/2482 (192.168.128.141) 1.15ms
2020-07-26 09:19:32,220 [script_server.audit_utils.WARNING] Could not get hostname for 192.168.128.141
2020-07-26 09:19:32,221 [web_server.INFO] 192.168.128.141 disconnected
2020-07-26 09:19:32,330 [tornado.access.INFO] 200 POST /executions/cleanup/2482 (192.168.128.141) 1.97ms

**Comment by willmcgugan** [comment]
Its not enough to add it to is.environ It need to be added to the environment the process is launched with.

**Comment by srqjan** [comment]
If i add try/except in problematic part of code 
print(" ")
try:
    table1 = Table(title="ONT RFO LOSS Report")
    table1.add_column("FTTH Network" , justify="center", style="green")
    table1.add_column("For the last" , justify="center", style="green")

    table1.add_row("SATTRAKT" , args[0] + " Hours")
    console = Console()
    console.print(table1)
except Exception:
    traceback.print_exc()
print(" ")

I am getting the same message
Traceback (most recent call last):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-70: ordinal not in range(128)
 
 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 346-501: ordinal not in range(128)

**Comment by srqjan** [comment]
It is added 
root@athene:/home/srdjan/script-server# echo $PYTHONIOENCODING
utf8
But, still doesn't solve the problem, I am getting the same unicode error

**Comment by willmcgugan** [comment]
It’s the script server that sets the environment variables for the script. I’m guessing there is configuration to do that. @bugy ?

**Comment by bugy** [comment]
All environment variables are just propagated to the called scripts. @srqjan could you print the encoding variable inside your script, please? And then call it from Script server

**Comment by srqjan** [comment]
Hi, 
If i run script disabling rich ,  output is formated on different way and everything works fine , there is no any unicode error.
This is example of output from script server
 
OLT :satt-srb-subotica-olt-2
PON_SERIAL: 454C54587001C0F0
  ONT:2/2/29 
   Loss Counter: 225
     DYING GASP Counter: 0
     GPON Admin Reboot Counter: 0
     Optical Loss Counter: 225
Please check the Optical Line !!!

**Comment by srqjan** [comment]
If i print environ dictionary form python script in terminal , I can see this
root@athene:/home/srdjan/script-server/conf/runners# python3 rich_ma4k_ltp_high_loss_detailed.py 3
environ({'LC_PAPER': 'en_US.UTF-8', 'XDG_SESSION_ID': '848138', 'LC_ADDRESS': 'en_US.UTF-8', 'LC_MONETARY': 'en_US.UTF-8', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'LC_NUMERIC': 'en_US.UTF-8', 'OLDPWD': '/home/srdjan', 'USER': 'root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_TELEPHONE': 'en_US.UTF-8', 'SUDO_USER': 'srdjan', 'SUDO_UID': '1006', 'USERNAME': 'root', 'MAIL': '/var/mail/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'LC_IDENTIFICATION': 'en_US.UTF-8', 'PWD': '/home/srdjan/script-server/conf/runners', 'LANG': 'en_US.UTF-8', 'LC_MEASUREMENT': 'en_US.UTF-8', 'SHLVL': '1', 'SUDO_COMMAND': '/bin/su', 'HOME': '/root', 'LANGUAGE': 'en_US:en', 'LOGNAME': 'root', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'XDG_RUNTIME_DIR': '/run/user/1006', 'SUDO_GID': '1006', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_TIME': 'en_US.UTF-8', 'LC_NAME': 'en_US.UTF-8', '_': '/usr/bin/python3'})

If i call script from script-server , i see this 
![image](https://user-images.githubusercontent.com/16043616/88477342-96e99080-cf3f-11ea-8ec5-6e021f0ac865.png)

**Comment by bugy** [comment]
Well, to be honest, I don't see PYTHONIOENCODING in neither of those

**Comment by bugy** [comment]
@willmcgugan from which sources does Rich get the encoding? Only this env variable?

**Comment by willmcgugan** [comment]
This is actually a Python thing. For some reason the encoding of stdout is ascii. This can happen if Python is run without environment variables. I think it gets the encoding from LANG first. PYTHONIOENCODING is a last resort.

Suspect the same error would occur if you used built in print to print Unicode not in ASCII takes.

**Comment by srqjan** [comment]
Ok , now it is here from terminal
environ({'LC_PAPER': 'en_US.UTF-8', 'XDG_SESSION_ID': '848138', 'LC_ADDRESS': 'en_US.UTF-8', 'LC_MONETARY': 'en_US.UTF-8', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'LC_NUMERIC': 'en_US.UTF-8', 'OLDPWD': '/home/srdjan', 'PYTHONIOENCODING': 'UTF-8', 


But from script server i do not getting it 
environ({'PATH': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin', 'TERM': 'linux', 'UPSTART_JOB': 'healthbot', 'UPSTART_INSTANCE': ''})
 
Traceback (most recent call last):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-70: ordinal not in range(128)
 
 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 346-501: ordinal not in range(128)

**Comment by bugy** [comment]
How did you set env variables for Script server? It seems that it was not picked up

**Comment by srqjan** [comment]
I 've added it to ~/.bash_profile
root@athene:/home/srdjan/script-server/conf/runners# cat ~/.bash_profile | grep PYTHONIOENCODI
PYTHONIOENCODING='UTF-8'
root@athene:/home/srdjan/script-server/conf/runners# cat ~/.bash_profile | grep COLUMNS
COLUMNS='150'
Is this correct way ? Also i can added it inside python script if need.

BR

**Comment by bugy** [comment]
Did you restart the Script server after adding it there?

**Comment by srqjan** [comment]
Adding it to /etc/environment didn't help me
root@athene:/home/srdjan/script-server/conf/runners# cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
PYTHONIOENCODING='UTF-8'
COLUMNS='150'

**Comment by bugy** [comment]
I tried running your code and it works for me :( I didn't set encoding
Might be related to docker environment

**Comment by srqjan** [comment]
Problem is solved by adding env vars to /etc/init/script-server.conf 
env COLUMNS='300'
env PYTHONIOENCODING='UTF-8'

But now output doesn't look good 
![image](https://user-images.githubusercontent.com/16043616/88479082-1336a080-cf4d-11ea-9d63-a4d357d46d13.png)
I 've tried to change COLUMS in range from 80 to 300 but I didn't get good output

**Comment by bugy** [comment]
How does it look for columns 100?

**Comment by srqjan** [comment]
it is the same problem , i 've resized my columns names , so it can be acceptable now

![image](https://user-images.githubusercontent.com/16043616/88479319-88ef3c00-cf4e-11ea-95ca-8ce5680f7a5e.png)
@bugy @willmcgugan ,  s huge thanks for help

**Comment by bugy** [comment]
Nice, glad to hear it worked!
Please note, that script server might not support some features (like specific colors, for example). But in general, it should be ok, I hope :)

**Comment by srqjan** [comment]
Yup, colors are not same in terminal and script server output , but it is ok , it is quite better now
Thanks one more time

**Comment by bugy** [comment]
@willmcgugan thanks a lot for your help!

**Comment by srqjan** [comment]
One small problem here , if use progress bar from documentation 
https://rich.readthedocs.io/en/latest/progress.html
Print from terminal is fine as usual , but print from script server show me some strange symbols at the end 
![image](https://user-images.githubusercontent.com/16043616/88481643-f30edd80-cf5c-11ea-8640-014d992bb907.png)

**Comment by bugy** [comment]
Yep, unfortunately this command is not supported. 

If it disturbs you much and you know a little bit of JavaScript, you can fix it, should be pretty easy :sweat_smile:

**Comment by srqjan** [comment]
Forget it. I can live without it

thanks
