### ISSUE TITLE
Reverse Proxy - Failed to load script info.

### ISSUE THREAD

**Issue by Melodoni** [bugy/script-server#326]
Hey guys,

straight to the problem...
I have a apache2 webserver which acts as a reverese proxy.

rv_proxy.conf (apache2 config)

```
<VirtualHost` *:80>
    ServerName test
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
<Location /script-server/>
    Define ScriptServerUrl http://127.0.0.1:8080/

    ProxyPass ${ScriptServerUrl}
    ProxyPassReverse ${ScriptServerUrl}
    RequestHeader set Origin ${ScriptServerUrl}

    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /(.*) ws:/$1 [P,NE]
</Location>
</VirtualHost> 
```

conf.json (Script-Server)

```
{
        "port": 8080,
        "address": "localhost",
        "title": "Script Server",
        "access": {
                "trusted_ips": ["10.32.152.220, 10.20.0.100"],
                "admin_users": ["10.32.152.220-bde028a8d4e24fd5"],
                "user_header_name": "X-Forwarded-User"
                },
        "logging": {
                "execution_file": "$DATE-$ID.log",
                "execution_date_format": "%y-%m-%d_%H-%M"
                 }
}
```

remoteip.conf (apache2)
```
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 10.20.0.100
```

Before the reverse proxy, everything just worked fine. now the following massage is displayed:
"Failed to load script info. Try to reload the page. Error message:
Failed to connect to the server"

Log of journalctl -xe

> Aug 12 14:48:20 test systemd-resolved[12112]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Aug 12 14:48:20 test python3[8645]: 2020-08-12 14:48:20,891 [script_server.audit_utils.WARNING] Could not get hostname for 10.32.152.220

i hope someone can help me ^^"

**Comment by bugy** [comment]
Hi @Melodoni could you check browser console/network tabs? What is shown there? 
Most common problem is misconfiguration of web sockets

According to your config, you already checked the wiki: https://github.com/bugy/script-server/wiki/Reverse-Proxy-setup
But just to double-check, did you install and activated all the modules listed there?

**Comment by Melodoni** [comment]
Hi @bugy 
I got this from my webbrowser 
![Script-Server-Web](https://user-images.githubusercontent.com/51383468/90096712-573ee900-dd34-11ea-856d-d2f8baadcd35.PNG)

ws://openvpn/scripts/Show%20connected%20Clients 
openvpn is the DNS name and "Show%20connected%20Clients" is the script name (which is not available)

I've checket the modules like ... 5 times by now? :D

> Module proxy already enabled
> Considering dependency proxy for proxy_http:
> Module proxy already enabled
> Module proxy_http already enabled
> Considering dependency proxy for proxy_wstunnel:
> Module proxy already enabled
> Module proxy_wstunnel already enabled
> Module rewrite already enabled
> Module headers already enabled

Thanks for the quick response :)

**Comment by Melodoni** [comment]
Okay i've found the problem. 
I was probably a bit too tired yesterday...

In my apache2 vhost conf i put in this peace of code 
```

<Location /script-server/>
    Define ScriptServerUrl http://127.0.0.1:8080/

    ProxyPass ${ScriptServerUrl}
    ProxyPassReverse ${ScriptServerUrl}
    RequestHeader set Origin ${ScriptServerUrl}
    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /(.*) ws:/$1 [P,NE]
</Location>
```

The line with `<Location /script-server/>` defindes where you find the website ... so i need to type http://openvpn/script-server/ and now everything works fine :) 

Thanks for your help :)

**Comment by bugy** [comment]
Nice, I'm glad it worked!
