### ISSUE TITLE
Multiple tabs in script server

### ISSUE THREAD

**Issue by bentpetersendk** [bugy/script-server#327]
We are a scientific group working on several different projects at the same time. Within each project, we are developing several prediction tools, which we run using bugy script-server all on the same web-server. It works excellent, but, we really have the need to separate each project from each other, so the different tools are not under the same project.

This functionality could be implemented by adding the possibility to add different tabs, which could be a new project group. Would that be possible to implement in the near future?

**Comment by bugy** [comment]
Hi @bentpetersendk, I'm not sure if I fully understand what you mean.
Is #243 what you mean, probably?

**Comment by bentpetersendk** [comment]
Yes, this is exactly what I needed. Sorry that I didn't realize that by myself.
