### ISSUE TITLE
Is it possible to override the default authentication duration?

### ISSUE THREAD

**Issue by realroywalker** [bugy/script-server#330]
The documentation for LDAP authentication says:- 'User login will stay valid in Script server for 1 month (even if he looses access to the LDAP server).'

Is there any property that can be set to override this value ?
We have a system where we'd like to ensure users a forced to regularly authenticate back into the script server, so would like to change the valid session time to maybe a few hours.

**Comment by bugy** [comment]
Hey, it was implemented in dev version only, `auth -> expiration_days`. I didn't check it, but probably you can use float value for hours, e.g. `"expiration_days": 0.2`

**Comment by realroywalker** [comment]
Thanks very much - I'm just about to leave work, but I'll test when I return next week and feed back if float does indeed work.

**Comment by realroywalker** [comment]
Sorry for the late update on this - I have tested it out and float seems to work fine
