### ISSUE TITLE
Trusted IPs allow to use * or subnet

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#331]
In my docker setup, each container get an random IP when it starts. It would require me to do a lot of modifications to be able to give my nginx container a static IP so the trusted ip work.

I suggest 2 options

1) Allow to use * as the trusted ip, meaning any IP will be ok
2) Allow to use a subnet instead of a specific IP like 178.18.0.0/24

Currently, every time my nginx container get a new IP I have to edit the configuration file to add the new ip...

**Comment by bugy** [comment]
Hi @Nottt, I think subnets would be a nice approach

**Comment by Nottt** [comment]
If you implement it, let me know it please so I can test it. Thanks

**Comment by Nottt** [comment]
Hey @bugy any news around this? I have been hit multiple times in the last weeks with this issue.

I can just get the ip from the logs and change conf.json and restart it, but It seems I'm suffering the Murphy's law and this only happens when I'm away for a extended time and then script server is offline only because of this.

If this is marked as won't fix, then I'll find a way to give a permanent static to my nginx container...

**Comment by bugy** [comment]
Hi, it's definitely will be implemented, not sure about the estimate
though. Will try to find some time for it in the next 2 weeks

ad90xa0-aa <notifications@github.com> schrieb am Di., 29. Sept. 2020, 08:36:

**Comment by Nottt** [comment]
Hi. I can't use computers much recently because of health related issues. And my script server is getting this a lot more now that for some reason docker is restarting by itself on my server.

What do you think of a bounty of $50 for this issue for this before monday ?

**Comment by bugy** [comment]
Hi, i got your priority :) I'll do it (dev version), without a bounty
1 question, do you think a mask would work for you? Like not allowing
everything, but only limited range of IPs

ad90xa0-aa <notifications@github.com> schrieb am Sa., 10. Okt. 2020, 11:17:

**Comment by Nottt** [comment]
I think subnet is enough. Since most docker setups will have dynamic ips, but always from the same subnet.

**Comment by Nottt** [comment]
Or did you mean something like 178.18.0.* ? If by that, I think that would be good too

**Comment by bugy** [comment]
Just standard subnet syntax, like 192.168.1.0/8

ad90xa0-aa <notifications@github.com> schrieb am Sa., 10. Okt. 2020, 11:52:

**Comment by Nottt** [comment]
Yes that would be perfect too

**Comment by bugy** [comment]
Hi @Nottt I added support for ip4 subnets, could you try it, please?

**Comment by Nottt** [comment]
It seems to be working as expected. Give me your btc wallet

**Comment by bugy** [comment]
Hi, nice to hear that!
I'm not going to take money from contributors :)

ad90xa0-aa <notifications@github.com> schrieb am Mo., 12. Okt. 2020, 07:19:

**Comment by Nottt** [comment]
Are you sure about that ? I'd be happy to donate :)

**Comment by bugy** [comment]
Absolutely! I prefer "donations" by contribution :)

ad90xa0-aa <notifications@github.com> schrieb am Mo., 12. Okt. 2020, 08:13:

**Comment by Nottt** [comment]
What do you mean ?

**Comment by bugy** [comment]
For me, an implemented feature or some utility script is more important,
than money.
And you already did it by providing extended docker image

ad90xa0-aa <notifications@github.com> schrieb am Mo., 12. Okt. 2020, 08:19:

**Comment by Nottt** [comment]
Oh ok thank you! I didn't think people were using my container already lol. Your software is amazing as always

**Comment by Nindaleth** [comment]
Thanks for the improvement! Would be lovely to see this in the server config example. I'm just going to drop another useful keyword here to improve searchability - CIDR notation.

**Comment by bugy** [comment]
Hi @Nindaleth, this is already in the example for `trusted_ips` section: https://github.com/bugy/script-server/wiki/Server-configuration#--trusted_ips

**Comment by Nindaleth** [comment]
Aha! I missed that one, sorry about that.
