### ISSUE TITLE
Additional information regarding ldap auth

### ISSUE THREAD

**Issue by zrks** [bugy/script-server#334]
Hi,
currently I'm trying to set up ldap auth for script-server.
Are there additional fields for ldap user configuration? As I see only 401 in script-server logs then I assume that this comes from ldep server (I don't have access to ldap server logs).

**Comment by muzzol** [comment]
this is my current configuration and it works great:

```
{
  "auth": {
    "type": "ldap",
    "url": "ldap://example.net",
    "username_pattern": "uid=$username,ou=users,dc=global",
    "base_dn": "ou=rols,ou=groups,dc=global",
    "version": 3
  },
  "access":{
    "groups": {
        "operators": ["@rol1", "@rol2"]
    },
    "allowed_users":["@admin_users", "@operators"],
    "admin_users":["useradmin1","useradmin2"],
    "trusted_ips":["127.0.0.1"]
  },
  "title": "My script server"
}

```

have you checked reachability with ldapsearch from script server to LDAP server?

**Comment by zrks** [comment]
I have very similar config at the moment. I can reach ldapsearch however I need to specify user and password in order to do that.

Is it possible to specify user (and how) in script-server config?
Maybe I'm missing something, feel a bit lost :/

**Comment by bugy** [comment]
Hi Marcis,
Do you see login page on the UI?

Marcis Veveris <notifications@github.com> schrieb am Fr., 4. Sept. 2020,
11:08:

**Comment by zrks** [comment]
Hi @bugy :)
Yes

**Comment by bugy** [comment]
Cool, then my main assumption would be the username pattern, does it fully
match the full (and unique) username on LDAP server?

Marcis Veveris <notifications@github.com> schrieb am Fr., 4. Sept. 2020,
11:20:

**Comment by zrks** [comment]
@bugy understood - lets close this one as I need to check with admins

thanks for input :)

**Comment by bugy** [comment]
You can also try to put just $username as a pattern, and on login page try
different full usernames (like dn, email, etc.)

PS sorry, I'm not ldap expert, so I might use wrong terms

Yaroslav Shepilov <buggygm@gmail.com> schrieb am Fr., 4. Sept. 2020, 11:23:
