### ISSUE TITLE
Show some UI feedback when refreshing dependant lists

### ISSUE THREAD

**Issue by realroywalker** [bugy/script-server#338]
Currently if a list/multiselect is getting it's values provided by a script, which is in turn using a parameter provided by another item (eg. another list), there is no UI feedback when the multiselect values are getting refreshed.

In an ideal world, the behaviour would be that when the use selects a new value in 'list A' (which triggers reloading of values in 'list B') - the web UI would show the loading bar at the top of the screen to display something is in progress.
This would really help to avoid confusion when there are scripts which take seconds to execute to populate 'list B', as currently it doesn't look like anything is happening.

**Comment by bugy** [comment]
I guess it's the same as #190 
Closing this one in favor of the older ticket
