### ISSUE TITLE
Add possibility to automatically execute script

### ISSUE THREAD

**Issue by ghost** [bugy/script-server#346]
Hello,
Please correct me if I am wrong or if this is a duplicate.
There are two steps involved when executing the script: 1) Selecting the script on the left hand side and then 2) clicking on EXECUTE.
Could you add the possibility to execute scripts when the page is opened? That is, that script runs without clicking on the EXECUTE button. (Clicking on the EXECUTE button would run the script again.)
You could add a new property in the script JSON config like "automatic_start" whose default value is false.

**Comment by bugy** [comment]
Hi, to be honest i find this behavior quite confusing. What kind of script
do you have, so that you want to start it automatically during navigation?

whng3 <notifications@github.com> schrieb am So., 4. Okt. 2020, 08:28:

**Comment by whng3** [comment]
It's just a simple status script to check whether a specific server is alive and healthy.

**Comment by bugy** [comment]
closing in favor of https://github.com/bugy/script-server/issues/218
