### ISSUE TITLE
Right bar  - scripts list changing the Script-Server title

### ISSUE THREAD

**Issue by Alonel** [bugy/script-server#350]
Is there any way to change the "Script-Server" tile in the right bar on the top above the script list? is there any property I can add to the main conf.json file which will control it?

**Comment by Alonel** [comment]
One small correction I mixed right and left. I obviously meant the left bar on top of the script list. sorry hour was too late :-)

**Comment by bugy** [comment]
Done, now the property [`title`](https://github.com/bugy/script-server/wiki/Server-configuration#title) overwrites the default title (i.e. not only in the tab name)

CC @jarrah31
