### ISSUE TITLE
Google Oauth document needs update

### ISSUE THREAD

**Issue by shinebayar-g** [bugy/script-server#355]
Hi. I'm trying to deploy script-server on a new server. But google [oauth2 docs](https://github.com/bugy/script-server/wiki/Authentication#google-oauth) is a little bit vague. Could you let me know how to create new google apps to provide google oauth for script server?

**Comment by bugy** [comment]
Hey, I guess you have to add https://console.developers.google.com/apis/credentials OAuth 2.0 Client ID
And there you would need to enable "Authorized redirect URIs"

For script server you would need to copy Client ID and Client Secret

**Comment by shinebayar-g** [comment]
Ah yes, thanks for the reminder. I also found my old issue asking how to set up google oauth =)).

I've updated the [Google oauth wiki](https://github.com/bugy/script-server/wiki/Authentication#google-oauth), added some instructions.

**Comment by bugy** [comment]
Cool thanks

Shinebayar G. <notifications@github.com> schrieb am Mo., 19. Okt. 2020,
07:04:
