### ISSUE TITLE
Secure LDAP over SSL/TLS

### ISSUE THREAD

**Issue by tristanlatr** [bugy/script-server#365]
Hello @bugy ,

First, thanks for the 1.16 release.

My servers authentication is setup like

```
"auth":{
	"type":"ldap",
	"url":"ldaps://10.x.x.x",
	"base_dn": "DC=domain,DC=com",
	"username_pattern": "DOMAIN\\$username",
	"version": 3
  },
```

I was wondering if the `ldaps://` part had any effect ?
Does the traffic is actually encrypted ?
There is no references to LDAPS in your docs, so I'm starting to doubt... 

Thanks for your answer.

**Comment by bugy** [comment]
Hi @tristanlatr I think that it doesn't enable secure layer, even if you use ldaps protocol. SSL should be enabled explicitly (which Script server is not doing)

**Comment by tristanlatr** [comment]
Hello @bugy,

Thank for your answer.
I feel a bit stupid to have thought for years that LDAPS would be enable just by setting the right sheme...

Do you think you could implement this security for the next version? If not, is it very hard? I could give it a try. 
It looks easy when reading the documentation https://ldap3.readthedocs.io/en/latest/ssltls.html

We could create a `secure` boolean flag inside the `auth` section of the server's config.

**Comment by bugy** [comment]
Hi @tristanlatr if you could try to implement and test it, it would be cool
I don't have a ldap server running, so it's not so straightforward for me

**Comment by tristanlatr** [comment]
Hello @bugy,

It looks like the `ldap3` module effectively creates a secure connexion when passing a server name like: `ldaps://server.ca:636`. 

I checked with a TCPDUMP and it's effectively using LDAPS protocol. 

Maybe a note about that on the Wiki could be good. 

Bu anyway, I'll close this issue.

**Comment by andrazjelenc** [comment]
Hi guys, 
passing server name that starts with "ldaps://..." creates a secure connection, but it DOES NOT VALIDATE server certificate.(https://ldap3.readthedocs.io/en/latest/ssltls.html)
"
IF you don’t use a specific Tls object and set use_ssl=True in the Server definition, a default Tls object will be used, it has no certificate files, uses the ssl.PROTOCOL_SSLv23 (if available in your Python interpreter) and performs no validation of the server certificate. It’s recommended to set validate=ssl.CERT_REQUIRED to verify the certificate server. Example:
"

**Comment by bugy** [comment]
Hi fnpanic, may be you could try to change this line on your side
https://github.com/bugy/script-server/blob/caf25c07f4456360c2e4d75ecdfa811320b3aed4/src/auth/auth_ldap.py#L153

and replace 
```
self.url,
```
with 
```
Server(self.url, use_ssl = True),
```

**Comment by fnpanic** [comment]
@bugy will try and report back!

**Comment by fnpanic** [comment]
@bugy tested it but throughs an expection

2022-03-03 10:58:42,436 [script_server.LdapAuthorizer.ERROR] Error occurred while ldap authentication of user thomas@ldap.local
Traceback (most recent call last):
  File "/opt/venv-ss/script-server/src/auth/auth_ldap.py", line 121, in authenticate
    connection = self._connect(full_username, password)
  File "/opt/venv-ss/script-server/src/auth/auth_ldap.py", line 153, in _connect
    Server(self.url, use_ssl = True),
NameError: name 'Server' is not defined

Without the change it works but i made sure it is not validating the cert of the server.

**Comment by bugy** [comment]
Oh, sorry, of course, this `Server` class should be imported first

please try adding somewhere at the top of the file
`from ldap3.core.server import Server`

**Comment by fnpanic** [comment]
Adding this works. I will do some tests and wireshark captures to see if it works as expected. Thanks!
