### ISSUE TITLE
LDAP auth username case sensitive

### ISSUE THREAD

**Issue by hamsterbacke** [bugy/script-server#367]
I use the LDAP auth for login and allowed_users with the sAMAccountName.
The login is working successfull but sometimes the user can't see the scripts that it should be allowed to via allowed_users config.
I figured, that the case of the username on login is used for matching against allowed_users.
They logged in with "Bob" instead of bob and that prevents correct matching in allowd_users array.

As a quick fix I edited the file "auth/auth_ldap.py" and added .lower() in line 110:
`username = request_handler.get_argument('username').lower()`

I guess this case problem is affecting every login method.

**Comment by bugy** [comment]
True, thanks for reporting!

**Comment by bugy** [comment]
Fixed, now all authorization checks should be case-insensitive (for any auth provider)
