### ISSUE TITLE
Include image in the terminal output (log_panel)

### ISSUE THREAD

**Issue by poloh11** [bugy/script-server#370]
Hi,
Thanks for this great tool !
For my use it would be even more incredible if I could include an image in the terminal output.
I mean, display an image in script execution and history from web url or sever location.
By looking around the code, I found
```
setInlineImage(output_path, download_url) {
        this.inlineImages[output_path] = download_url;
        this._notify_inline_image_change(output_path)
}
```
in file _script-server/web-src/src/common/components/terminal/terminal_model.js_
So I assume that you created the functionality. But how to use it from my script ? I there a specific syntax to use ?
Thank you so much
Paul

**Comment by bugy** [comment]
Hi Paul, please check this comment:
https://github.com/bugy/script-server/issues/231#issuecomment-527242372

**Comment by poloh11** [comment]
Thanks bugy, I managed to make it work on live execution. But it do not display image in history right ?

**Comment by bugy** [comment]
Yes, unfortunately that doesn't work for history

**Comment by sir-max** [comment]
Sry for asking this, but I can not determine where to put the config snippet to achieve this. Would you be so kind to tell me?

**Comment by bugy** [comment]
@sir-max you have to put it into script configuration:
my_script.json:
```
{
  "name": "My script",
  "script_path": "scripts/my_script.sh",
  "output_files": [
	{
             "type": "inline-image",
             "path": "##any_path/[0-9]{8}.png#"
        }
  ]
}
```

**Comment by sir-max** [comment]
Thanks, that worked (at least with an absolute path in it). Is **"##any_path/[0-9]{8}.png#"** some kind of regex for matching a printed output? I can not get it to match any dynamically generated images.

But it is not urgent since I can just use a fixed path and name for my use case.

**Comment by bugy** [comment]
@sir-max exactly, this is a regex for printed output, you can read more here: https://github.com/bugy/script-server/wiki/Script-config#output_files
