### ISSUE TITLE
PCI env TLS version

### ISSUE THREAD

**Issue by dutangp** [bugy/script-server#371]
Hello,

I really like this script-server and I am testing it at the moment. As I would like to deploy it in PCI environment (ultra secure) I need to disable TLS1.0 and 1.1.

Is there a specific configuration for that? I check everywhere but no luck so far, I am planning to check the code to try to find that.

Thanks a lot

**Comment by bugy** [comment]
Hi, @dutangp I think you would be the first person, using SSL in script server :) 
Usually, people are having a reverse proxy in front, with enabled SSL

At the moment, there is no such feature out of the box.
In the code, it's configured here: https://github.com/bugy/script-server/blob/85f923c3c055a89ea6fc8be9327021f96bb92b64/src/web/server.py#L935

**Comment by dutangp** [comment]
Hi, @bugy  thanks a lot I patched the file and it works perfectly.

I understand the reverse proxy but unfortunately I can't easily do that.

```
    if server_config.is_ssl():
        ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
        ssl_context.load_cert_chain(server_config.get_ssl_cert_path(),
                                    server_config.get_ssl_key_path())
```

**Comment by jgriff500** [comment]
@dutangp -- so you replaced this one line in the server.py with the 5 lines you have listed?

**Comment by ninjatrench** [comment]
@dutangp can you share how you patched it? I don't want to modify the original code from Bugy but I can monkey patch if required.

@bugy can't we make it a configurable parameter in configuration file ?

**Comment by bugy** [comment]
Hi @ninjatrench, sure it's doable. But someone has to do it :)
