### ISSUE TITLE
Script disappears from WebUI after editing coressponding json in conf/runners/

### ISSUE THREAD

**Issue by schnippendullerich** [bugy/script-server#374]
Hi,

well, the title is a bit incomplete as it generally works. But if the chnage is to big, it disappears from the WebUI.

I tried to add a json file manually, which I could not get to appear in the webUI. After adding a script in the admin panel with minimal values it was there. 

Then I have editet the autmatically created json file a liitle bit, like the description, which worked as was shown also in the webUI. 
After that, I have added a bunch of parameters in the same jason file and bang, it's gone from the webUI.

I fixed it by creating the script again and didn't touch the json file too much. I just don't get this... please someone tell me why. :-)

Kay 

great job @bugy !

**Comment by sir-max** [comment]
Hi @schnippendullerich,

I experienced this behaviour, when I misconfigured the json file. Are you really sure you configured it the right way? No missing commas or other syntax errors? I guess it would also help to attach your config for debugging purposes

**Comment by bugy** [comment]
Hi Kay, i would also assume, that the problem is a broken json syntax.
You could check logs/server.log file. It should contain json parsing errors
in this case

sir-max <notifications@github.com> schrieb am Do., 10. Dez. 2020, 00:55:

**Comment by schnippendullerich** [comment]
Argh... you are right!
There was one bracket more than neaded which was not able to see yesterday. Sorry, I was tired.
