### ISSUE TITLE
UI Feature - Selection window mobile browser friendly

### ISSUE THREAD

**Issue by MelBourbon** [bugy/script-server#379]
I don't think that the server is intended to be working on mobile browser but so far it's doing very well. One problem I have with the selection window (file selection option enabled). The select button (low right corner) is hard to reach (not at all in portrait mode - screen attached) and only hard in landscape mode. Maybe there is a easy fix to improve.

![Screenshot_20201219-084020](https://user-images.githubusercontent.com/30600002/102684184-a3180800-41d6-11eb-8e76-9ca06d18fb9c.jpg)

**Comment by bugy** [comment]
Thanks for reporting

**Comment by bugy** [comment]
@MelBourbon could you try dev version? I made a fix

**Comment by MelBourbon** [comment]
@bugy Tested it and works as expected in dev version. Thanks for fixing.

**Comment by bugy** [comment]
Cool, thanks for confirming!

**Comment by antonellocaroli** [comment]
@bugy the drop-down menus on the phone now work, the only thing is the positioning of the excute key overlapping

![image](https://user-images.githubusercontent.com/11161093/103442680-cd4ada80-4c58-11eb-9ea9-47e369cedc48.png)

**Comment by MelBourbon** [comment]
@antonellocaroli I can not confirm or reproduce this. Nor with Chrome or Firefox (both mobile). Is this behavior in Desktop versions of these browsers.

**Comment by antonellocaroli** [comment]
@MelBourbon 
only on iphone, not on android. on android it works fine!
with both chrome and safari

**Comment by bugy** [comment]
Hi @antonellocaroli, thanks for reporting. 
I think it's more related to #324 changes (they were really massive). 

Do you have any possibility to debug/fix it? I don't have an iPhone, so it's quite hard for me to find the root cause

**Comment by antonellocaroli** [comment]
Hi @bugy ,
I'm happy to debug it, but I don't know how... if you give me directions...

**Comment by bugy** [comment]
@antonellocaroli do you have a mac machine? if yes, I think this should help: https://www.lifewire.com/activate-the-debug-console-in-safari-445798
For windows I believe it's smth like this: https://medium.com/@haroonabbasi/remote-debugging-safari-iphone-ipad-ios-11-on-windows-340b403a9829

**Comment by antonellocaroli** [comment]
@bugy 
I only have linux PCs.

Anyway for info, I don't think it's due to the last changes you made, it was happening before.
The problem occurs when there are multiple menu choices.

![image](https://user-images.githubusercontent.com/11161093/103454368-8229d980-4ce3-11eb-8941-4757c54fb512.png)


![image](https://user-images.githubusercontent.com/11161093/103454376-8e159b80-4ce3-11eb-86ca-7a8f7a24fe0a.png)

**Comment by bugy** [comment]
@antonellocaroli thanks for the info. Do you mean, that this happen, when there are many parameters or a long combobox list? I mean, if you add 10 text fields (without drop downs), will it behave correctly?

**Comment by antonellocaroli** [comment]
@bugy I think it's due to both, how much space they take up....

![image](https://user-images.githubusercontent.com/11161093/103461358-1b75e180-4d1e-11eb-9db8-fed4ba0952c2.png)


![image](https://user-images.githubusercontent.com/11161093/103461365-24ff4980-4d1e-11eb-9298-5d79c1180cee.png)
