### ISSUE TITLE
A more visible title?

### ISSUE THREAD

**Issue by jarrah31** [bugy/script-server#384]
Would it be possible to have the script server title visible on the webpage itself please? 

I can see the "title" text appears on the browser tab, but that then disappears when selecting a script, and is generally not that visible when you have multiple tabs open. 

I'm not quite sure where the best place for it would be though. It could replace the "Script Server" text, but that would hide the name of this excellent project. A better place may be on the same line as the script name, aligned to the right of the page so that the two don't clash?

The reason for this is I'd like to run a couple of different script servers (e.g. one dev, one prod), but there's no easy way to tell them apart at the moment. It could be the upcoming feature to change colour schemes would solve the problem because then dev could be a different colour, or perhaps the ability to change images means I could have one with embedded text...

Thanks.

**Comment by bugy** [comment]
Hi @jarrah31, I think #350 is kind of a similar issue
I think replacing "Script server" in the left panel with the `title` property is a way to go

**Comment by jarrah31** [comment]
Thanks, yep let's use that issue for the feature request.
