### ISSUE TITLE
Dynamic list values are not cleaned after script execution

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#385]
Steps to reproduce:
1. Create a list parameter, which depends on another parameter (let say either 1 -> [A, B], 2 -> [C, D])
2. Select value **1**, so that the parameter has list [A,B]
3. Select value A
4. Execute the script, and wait for finish
5. Change to value **2**

Actual result: the list has [A, C, D] parameters
Expected result: the list has [C, D] parameters only

Demo: https://gph.is/g/Evp9OXV

Reported by @autogun

**Comment by bugy** [comment]
Done
Additionally I improved some other things
- Loading dependant values for running script (or for predefined parameters) is much more stable now, and considers "included" script parameters
- Now "obsolete values" in comboboxes are disabled and show validation error
- Switching between execution tabs made faster (removed extra server request)
- Multiselect comboboxes header is improved

**Comment by antonellocaroli** [comment]
@bugy 

I hope this does not mean that:

if in field 1 I have a list of its values

and in field two I have to get a list based on the value I choose in the 1 item....
field 2 lists the results according to the list in field 1 and not according to the value chosen.
Because from a test I've done it seems to me that it works just like that...and this would be a mess....

**Comment by antonellocaroli** [comment]
@bugy 

this is the example I used:

{
      "name": "Audiocard",
      "param": "-t",
      "type": "list",
      "required": true,
      "values": {
        "script": "/opt/.gentooplayer/web/scripts/script/card/card.sh"
      },
      "description": "Select AudioCard"
    },
    {
      "name": "Max Sample rate",
      "param": "-R",
      "type": "list",
      "values": {
        "script": "/opt/.gentooplayer/web/scripts/script/card/maxrate.sh ${Audiocard}"
      },
      "required": true,
      "description": "Select Max SR dac supported"
    },


the first parameter lists the audio outputs...
choosing the audio output in the second parameter displays the maximum supported frequency.
but now it lists all the maximum frequencies.....for each audio output listed in parameter1

**Comment by bugy** [comment]
Hi, actually the existing behavior should stay almost untouched
In your example it should show only supported frequencies, as you expect
If it doesn't work this way, it's a bug :(

antonellocaroli <notifications@github.com> schrieb am Mi., 6. Jan. 2021,
17:31:

**Comment by bugy** [comment]
Hi @antonellocaroli could you create some minimal reproducible config and a script, please?
For me everything works fine :(

**Comment by antonellocaroli** [comment]
Hi @bugy ,

ok, I'll check again....maybe it's a problem in the script....

**Comment by BConcept59** [comment]
Hi,

I have a little problem.

I use the dynamic list values but it isn't send full "text" of combobox.

Combobox N°1 (Naming : Etablissement) 

- Residence Tulopre
- Residence Tarlure
- Residence Tart Opera

i use ${Etablissement} at the end in script line, but in value in my param in script is only "residence", i don't have more text.

Do you have idea ?

Sorry for my English, i'm not very good.

**Comment by bugy** [comment]
Hi @BConcept59, could you try wrapping the `${Etablissement}` in quotes?
e.g. `"script": "my_script.py '${Etablissement}'"`

**Comment by BConcept59** [comment]
Hi @bugy , i try wraping in quote, but this isn't ok.

My cmd line is : `powershell -ExecutionPolicy Unrestricted -Command ./src/features/sc_script_003.ps1 ${Etablissement}`

For my other parameters, it's perfect, juste for the `${Etablissement}` this isn't ok.

**Comment by bugy** [comment]
Are you running script server on windows or Linux?

**Comment by BConcept59** [comment]
Thank for your help @bugy !! 

I running on Windows.

**Comment by bugy** [comment]
Thanks, I'll check later

**Comment by bugy** [comment]
Hi @BConcept59. I saw your original message, with "this isn't ok." and wanted to check.
However, it seems, that quotes are working fine for you.

I created a separate ticket for making the behaviour less confusing: https://github.com/bugy/script-server/issues/420
