### ISSUE TITLE
can't get script status by admin users

### ISSUE THREAD

**Issue by yosefy** [bugy/script-server#387]
so i have tried like this

{

  "port": 5000,
  "title": "Script Server",
  "access": {
        "admin_users": [ "127.0.0.1" ],
        "trusted_ips": [ "10.0.0.15","127.0.0.1" ]
  }
}

the log:

Dec 28 12:36:02 prod-mgmt-001 python3[21472]: 2020-12-28 12:36:02,729 [web_server.WARNING] Prohibited access to not owned execution #997 (user=127.0.0.1)
Dec 28 12:36:02 prod-mgmt-001 python3[21472]: 2020-12-28 12:36:02,729 [tornado.access.WARNING] 403 GET /executions/status/997 (127.0.0.1) 1.34ms

**Comment by bugy** [comment]
Hi @yosefy thanks for reporting, I'll check it

**Comment by bugy** [comment]
Fixed
Sorry for the delay :(
