### ISSUE TITLE
Socket closed. code=1006, reason=

### ISSUE THREAD

**Issue by antonioluzzi** [bugy/script-server#395]
Hi,
I can't connect to the script server behind an HTTPS server apache.
I have the following config in apache:
<Location /bk-script-server/>
    Define ScriptServerUrl http://172.29.48.124:5044/
    Define ScriptServerHost 172.29.48.124:5044

    ProxyPass ${ScriptServerUrl}
    ProxyPassReverse ${ScriptServerUrl}
    RequestHeader set Origin ${ScriptServerUrl}
    RequestHeader set Host ${ScriptServerHost}

    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /(.*) ws:/$1 [P,NE]
</Location>

In the chrome console  I have this error: Socket closed. code=1006, reason=
In the server.log :
2021-02-08 11:50:13,439 [tornado.application.ERROR] Exception in callback functools.partial
Traceback (most recent call last):
  File "/home2/volumes/services/scriptserver/envname/lib64/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home2/volumes/services/scriptserver/envname/lib64/python3.6/site-packages/tornado/websocket.py", line 339, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

Can someone help me?
Regards
Antonio

**Comment by bugy** [comment]
Hi @antonioluzzi do you see any other messages in chrome console and in server.log file?
I think the reason might be `RequestHeader set Host`, try removing this line

Also, could you double-check, that the modules from the list are activated? https://github.com/bugy/script-server/wiki/Reverse-Proxy-setup
