### ISSUE TITLE
Scheduler: Pick individual days

### ISSUE THREAD

**Issue by ThomasWnk** [bugy/script-server#404]
We have a couple of Jobs we need to run on specific days, like every Tuesday, Wednesday and Thursday.
Right now, the Scheduler only supports intervals of n days for repeating  jobs. It would be really cool to be able to pick the day of week.

**Comment by bugy** [comment]
Hi @ThomasWnk, wouldn't "every week" work for you? You can select days of week there

**Comment by ThomasWnk** [comment]
Hi, that looks like it might be what I need. I'll check it out, thanks!

**Comment by ThomasWnk** [comment]
Well, turns out that was exactly what I was looking for.
