### ISSUE TITLE
Possibility of adding a secondary LDAP server in the AUTH block?

### ISSUE THREAD

**Issue by mitchtchesnitch** [bugy/script-server#407]
Hi @bugy !

I was wondering if Script Server would support adding a secondary/failover LDAP server in the "auth" server config block.

The use case would be that we need to achieve some redundancy in case one of the LDAP servers is unreachable.

Thanks, I look forward to hearing from you!

**Comment by mitchtchesnitch** [comment]
Thanks for the quick reply @bugy ! I was mainly looking for confirmation if the current logic in the auth block would support multiple providers of the same type(LDAP), or if this would require a change in code.

That would give a good starting point, thanks!

**Comment by mitchtchesnitch** [comment]
Oh, I just saw that you added the "feature" label, so I think I got my answer:D

**Comment by westerterp** [comment]
I've just figured out that this is already possible with the LDAP library that's in use.
You are able to pass an array of URL's with which the library will create a ServerPool and balances the load over each server using Round Robin.

I'm not able to create a merge request for Wiki pages, but I think it's a good idea that the Wiki reflects this possibility.
I've proposed a change below.

```markdown
### - `url`
(LDAP, Gitlab)
URL of the LDAP/Gitlab server
Can also be an array in case of multiple LDAP servers. In this case the pooling method will be Round Robin

_Required_: yes (for LDAP), no (for Gitlab)
_Type_: string (or array for multiple LDAP servers)
_Example_: `"url": "ldap://192.168.100.3",`
_Example_: `"url": ["ldap://192.168.100.3", "ldap://192.168.100.4"],`
_Default_:  https://gitlab.com (for Gitlab) 
```

More info on the ServerPool option can be found here: https://ldap3.readthedocs.io/en/latest/server.html#server-pool

**Comment by bugy** [comment]
Hi, @westerterp thanks for checking and the description! Did you try it? I'm not sure if it would work with Script server configuration. I might parse configuration files as strings

**Comment by westerterp** [comment]
Yep, I took it for a spin and it worked like a charm.
Checked the network traffic for the Active Directory servers I was talking to and it actually did Round Robin between those two.

**Comment by bugy** [comment]
Cool, thanks a lot!
I'll update wiki tomorrow


Mark Westerterp ***@***.***> schrieb am Di., 30. März 2021,
00:10:

**Comment by bugy** [comment]
Done, I edited wiki and also added a test just in case, so I don't break it in the future with some refactorings
