### ISSUE TITLE
Can I schedule a script it for running?

### ISSUE THREAD

**Issue by mizzunet** [bugy/script-server#410]
Noob here.
Can I set a schedule a script for running every day, say at 9.00 AM in the background, I mean without any user interaction for executing?

**Comment by bugy** [comment]
Hey, please check this one: https://github.com/bugy/script-server/wiki/Script-scheduling

**Comment by mizzunet** [comment]
> Hey, please check this one: https://github.com/bugy/script-server/wiki/Script-scheduling

Thank you so much, let me have a look :)

**Comment by mizzunet** [comment]
> Hey, please check this one: https://github.com/bugy/script-server/wiki/Script-scheduling

It's perfect! BTW, I need a server for setting up this right? Is it ok to ask you, is there any free basic server where I can use it? How about Heroku?

**Comment by bugy** [comment]
Yes, you would need a server. Unfortunately I cannot give you any recommendations on a free server. You can try with Heroku probably.
I'm using a paid AWS server
