### ISSUE TITLE
Powershell support (in docker)

### ISSUE THREAD

**Issue by wardwygaerts** [bugy/script-server#413]
Is Powershell supported as well? I'm also running script server in a docker container, so I don't know how to achieve this.

**Comment by bugy** [comment]
Hi, powershell scripts should be ok.
You would need to install powershell to the docker image.
Script server docker image is based on debian Linux. You can check the
installation guide here:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#debian-10

**Comment by wardwygaerts** [comment]
Thanks for the respond!
So I need to create my own container I suppose? Where can I find the Dockerfile?

**Comment by bugy** [comment]
The script server docker file is here:
https://github.com/bugy/script-server/blob/master/tools/Dockerfile

But you don't need it, you can just base your image on script server image,
by writing
FROM script-server:latest
In your docker file

**Comment by wardwygaerts** [comment]
Ok, I'll need to look into this, because I never write my own Dockerfiles...

**Comment by wardwygaerts** [comment]
I managed to install Powershell, thanks for hemping

```
FROM bugy/script-server:latest

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y powershell
```

**Comment by bugy** [comment]
Cool, glad you find the way!
