### ISSUE TITLE
Run Docker commands from Docker container

### ISSUE THREAD

**Issue by wardwygaerts** [bugy/script-server#414]
I have script-server running in a container, which is working great. Is it possible (and how) to run docker commands so I can eg stop/start other containers?

**Comment by bugy** [comment]
Could you check the answers here, please? https://forums.docker.com/t/how-can-i-run-docker-command-inside-a-docker-container/337/5

**Comment by wardwygaerts** [comment]
It was indeed very simple, I just mouted these 2 volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

thx for pointing my in the right direction
