### ISSUE TITLE
Update Python in Docker image

### ISSUE THREAD

**Issue by wardwygaerts** [bugy/script-server#418]
I saw that the Python version in the Docker image is still 3.6.12.

Is it a possibility to change `FROM python:3.6-slim` to `python:3.9-slim` (https://hub.docker.com/_/python) ?

**Comment by bugy** [comment]
Hi @wardwygaerts good idea! I'll go it soon

**Comment by bugy** [comment]
Done, dev version is based on 3.9 now

**Comment by wardwygaerts** [comment]
thanks, working fine!
