### ISSUE TITLE
[Windows] - Script Powershell - problem ANSI

### ISSUE THREAD

**Issue by BConcept59** [bugy/script-server#419]
Hi,

I would like thank @bugy for Script-Server ! It's very good software !

I my script powershell, the data is good with the special characters ( é à è ... ). But in the combobox it isn't good in the view.
It remplace the special characters by ","

Do you have a solution ?

Thank for advance

**Comment by bugy** [comment]
Hi, which script server version are you using?
Also, which encoding is used in your script?
Stable script server version works with utf8. Dev version has some extended encoding support, but not much

May be you can try a workaround from https://github.com/bugy/script-server/issues/376#issuecomment-745277217
The wrapper with `iconv`

**Comment by BConcept59** [comment]
I use version 1.16.0 Script-Server

My script use UTF8 BOM and adding -Encoding UTF8 on my cmd for forced the coding.

Line : 
`get-content ./src/features/__Informations__/$Company_File.list -Encoding UTF8`

i don't have Iconv on Windows.

**Comment by bugy** [comment]
Hi, @BConcept59 I made it work on my windows machine, by adding this line at the beginning of the PowerShell script:
```[Console]::OutputEncoding = [System.Text.Encoding]::Default```

The problem is, that when run on windows (at least win10), script server is using default system encoding (e.g. cp1251 for me). However, PowerShell writes output (by default) in utf-8 (with or without BOM, doesn't matter). 
By adding the line above, powershell is made to write output in system default encoding

Could you try it, please?

**Comment by BConcept59** [comment]
I have add `[Console]::OutputEncoding = [System.Text.Encoding]::Default` in my script and it's good ! 

Very thanks

I have a two other problems... 

1. Always UTF8 error but with the information provided by the user in the input fields.

the input return :

`powershell -ExecutionPolicy Unrestricted -Command ./script_005.ps1 -LastName Hir Tone -Firstname Ã©glantine -Company RESIDENCE LA GENTILHOMMIERE -SharedMailBox Accueil -Title Agent d'accueil`

2. Always in input return, how to do for adding ( ' ). Because my value is truncate in my script.

Example : `-LastName Hir Tone` --> `-LastName 'Hir Tone'`

**Comment by bugy** [comment]
Hi, @BConcept59 to be honest I don't fully understand you. Maybe you can send me a part `script-server/logs/server.log` file, which corresponds to script invocation?

**Comment by BConcept59** [comment]
Sorry for my english.

In log server : 

`2021-03-26 21:20:50,552 [web_server.INFO] Calling script Créer un utilisateur. User {'ip': '127.0.0.1', 'hostname': 'AZAPPS001.univi.lan'}
2021-03-26 21:20:50,554 [script_server.execution_service.INFO] Calling script #39: powershell -ExecutionPolicy Unrestricted -Command ./script_005.ps1 -LastName béal -Firstname AR to -Company RESIDENCE LA GENTILHOMMIERE  -SharedMailBox Accueil -Title Agent d'accueil`

I need to add simple quotes for the sent values. 

Example: 

`-Company RESIDENCE LA GENTILHOMMIERE`

should be 

`-Company 'RESIDENCE LA GENTILHOMMIERE'`

**Comment by bugy** [comment]
For me it worked, when I passed the script path with -file argument
Works (parameters with whitespaces are parsed as a single argument):
`"script_path": "powershell -file 'path\\to\\encoding_419_bug.ps1'",`

Does **not** work (parameters with whitespaces are sent separately):
`"script_path": "powershell 'path\\to\\encoding_419_bug.ps1'",`

Could you try, please?

**Comment by bugy** [comment]
Hi @BConcept59 any success here?

**Comment by BConcept59** [comment]
Hi @bugy , yes it's success ! Very thanks.

Sorry for my delay.

**Comment by bugy** [comment]
Cool, thanks for confirmation
