### ISSUE TITLE
Steps to install script-server in windows

### ISSUE THREAD

**Issue by DijoJose1** [bugy/script-server#422]
Hello team,
I was looking for a tool like this. Thanks a lot for your efforts in building such a wonderful tool.
I would like to install this in my windows server. Could you please provide me the steps? I had gone through the steps in the url: https://github.com/bugy/script-server
But it is not working. I think I am missing some steps. Could you please provide me the configuration steps for windows?
Thanks and Regards,
Dijo Jose

**Comment by bugy** [comment]
Hi @DijoJose1, could you tell me, what errors/problems do you see?
Did you install python3 with tornado module?

**Comment by DijoJose1** [comment]
Thanks for the quick response.
I will tell you what all steps completed.
Installed python (3.9)
Installed tornado (6.1)
Copied the latest zip file to my server and extracted to a folder (windows server 2019)
Created a sample conf.json file in conf/runners folder . Added ldap configuration in that. Used sample conf json provided in https://github.com/bugy/script-server/wiki/Server-configuration and modified ldap section.
I have a question here. Will the app run if I don't provide the conf file? Will there be a default user to login?

Tried to launch launcher.py from script-server folder. Nothing happens. 
Tried the default url from browser (http://localhost:5000). This also not running

Could you please help me with the missing steps? 

Thanks and Regards,
Dijo Jose

**Comment by bugy** [comment]
> Created a sample conf.json file in conf/runners folder .
the file should be in conf/conf.json (runners are configurations for scripts)
Also, be careful with using the sample file, it has much more things than you usually need

> Will the app run if I don't provide the conf file? 
Yes, it will just pick defaults. By default there is no authentication, so anyone can access it

> Tried to launch launcher.py from script-server folder. Nothing happens.
Ok, this sounds strange. There should be those logs on startup: 
```
2021-03-30 13:03:00,948 [root.INFO] Starting Script Server (custom version)
2021-03-30 13:03:01,221 [asyncio.DEBUG] Using selector: EpollSelector
Server is running on: http://0.0.0.0:5000
```
or some errors

May be you can try to run it using the following command:
`python3 launcher.py` ?  or `python launcher.py`
Unfortunately I'm not very familiar with running python on windows servers

**Comment by DijoJose1** [comment]
Thank you so much for the updates.
I removed the conf.json file.
Executed init.py --no-npm first and then python launcher.py.
Now I am able to open the portal in localhost. Thank you so much for the help.
I have one more doubt. If I have to open it from my client browser, what all changes are required?

**Comment by bugy** [comment]
By default there are no constraints in Script server, you can open it from any machine in a network for any user. Just use the server IP in the browser URL.

**Comment by DijoJose1** [comment]
Thank you so much for the updates.
I have more more query.
I have a powershell script which is running as a part of windows scheduled task.
If I have to run that job from script-server, what all settings are required here?
I used the following parameters in scheduler:
Start Program: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Argument: -NoProfile -Executionpolicy bypass -file "D:\Script\script.ps1" -Parameter 'Value'

**Comment by bugy** [comment]
You would need to create a json file in conf/runners folder, with the following content

```
{
  "name": "Some name",
  "script_path": "powershell -NoProfile -Executionpolicy bypass -file 'D:\\Script\\script.ps1'",
  "description": "Some description",
  "scheduling": {
    "enabled": true
  },
  "parameters": [
    {
      "name": "text",
      "param": "-Parameter",
      "description": "Some parameter description"
    }
  ]
}
```

(please update names/descriptions as per your use case)


And then on the UI, you would be able to see this script and would be able to schedule it (there will be a button on a right side, when you open it)
