### ISSUE TITLE
Title update issue

### ISSUE THREAD

**Issue by billybenson** [bugy/script-server#426]
Hi - I am using a very basic conf.json file to try and update the Title of the page.

The 'tab' on my browser is showing the new title, however my understanding is that the title on the left above the scripts should show the new title as well. Instead - it just shows the default 'Script server'.

I am using Windows as the server.

Thanks for your work!

**Comment by bugy** [comment]
Hi @billybenson, I believe this is the same issue as https://github.com/bugy/script-server/issues/350
This is fixed only for dev version at the moment

**Comment by billybenson** [comment]
Hi @bugy , thanks for the quick reply, I am running the dev version currently.

**Comment by billybenson** [comment]
Hi - ignore me, it's working now :)
