### ISSUE TITLE
Allowed Values in List disappear?

### ISSUE THREAD

**Issue by bgpgrid** [bugy/script-server#427]
Hi there,

I'm trying to get a list to work properly.  When I try to add "Allowed Values" via the admin gui and click Save, the values I enter disappear.  No matter what format I put the values in, they just keep disappearing.  

What is the correct format to put "allowed values" when using Lists?

**Comment by bugy** [comment]
Hi @bgpgrid please try pressing enter after entering each value

**Comment by bgpgrid** [comment]
Hi bugy,

That worked...man, I spent so much time trying to figure out what to do with that field, ha!

How about with the "arg" field?  (sorry I'm new to this)

I have 3 possible flags in my script that can be used so how would I do that with the args field?

Thanks again

**Comment by bugy** [comment]
Sorry for the confusion @bgpgrid , I have plans to improve the UX for it

Regarding the arg, to be honest I don't understand your use case. Could you give an example please?

**Comment by bgpgrid** [comment]
Sure, in my script I have 3 variables set to match an ip block:

Example:

block1=10.0.0.0/24
block2=20.0.0.0/24
block3=30.0.0.0/24

I need these variables to match the values in the dropdown list in the UX.

**Comment by bugy** [comment]
I'm super sorry, still don't understand the expected result :(

Are all these 3 blocks used inside a script? Or a user has to select one of those 3 blocks and pass to a script?

**Comment by bgpgrid** [comment]
No worries. I'm probably just not explaining it right.

A user should select one of the 3 blocks from the dropdown list in the UI and should be passed to the script ideally.

**Comment by bgpgrid** [comment]
I figured out what I was doing wrong with the arg field.  

Thanks for the help!  BTW, great piece of software!

Also, another vote for being able to change the "script server" text in the top left. I know it's only in dev right now but hopefully will get pushed to prod at some point. :)

**Comment by bugy** [comment]
Cool :)

yes, i hope to release new prod version in the next month
