### ISSUE TITLE
Detaching shell execution

### ISSUE THREAD

**Issue by Haxprox** [bugy/script-server#439]
Hi bugy, hello community!
Can someone help with understanding and run the script(_mpv player or any process_) in the background mode?
The problem here:
```
...
h264_60fps)
exec mpv $options --ytdl-format="bestvideo[vcodec^=avc1]+bestaudio/best" $FORM_link > /dev/null 2>&1 &
echo "Watch it!"
;;
...
```
Seems, generally, it's not a problem and made by design. So, when I try to execute it without "&"(send to the background) it does work but looks like a process that running in real-time via Dashboard and waiting for some input or stop execution.

To reproduce:
```
#!/bin/bash

sleep 30 &
```
The 'sleep' command will never run.

How to run the shell script in detached mode?

**Comment by bugy** [comment]
Hi @Haxprox, I executed echo in the background just for a test and it worked fine:
`echo '123' &`
Also, I tried to reproduce the sleep command in the background, and it was running fine in a separate process (I saw it using `ps ax | grep sleep`)

So I'm not sure, what is the problem here :( Script server is not limiting background processes

Could it be, that `exec mpv` is failing with some errors? And you don't see it because of `> /dev/null` ?

**Comment by Haxprox** [comment]
Yup, 'echo' executes without issues because it prints then detached. How about this attempt?

```
#!/bin/bash

sleep 2 && echo "Hello world!" &
```
Can you see the result on the Dashboard with "&" because without, it waitings for the end of the 'sleep' command?

> Could it be, that `exec mpv` is failing with some errors? And you don't see it because of `> /dev/null` ?

Definitely not :( It works perfectly by using a commandline and without "&" by the Dashbord.

![Screenshot from 2021-05-09 22-11-16](https://user-images.githubusercontent.com/13851216/117584381-42518380-b115-11eb-973e-5bf8465a1f15.png)

Expected behavior is to run the script(_process_) without tying to the Dashboard.

**Comment by bugy** [comment]
> How about this attempt?

It prints "Hello world" after 2 seconds for me. Both in normal terminal and script server

I tried with mpv, and it also works for me in Script server. I used this command (without any `$options`):
`exec mpv --ytdl-format="bestvideo[vcodec^=avc1]+bestaudio/best" 'https://www.youtube.com/watch?v=EngW7tLk6R8'  2>&1 &`

Whole script:
```
#!/bin/bash

set -e

exec mpv --ytdl-format="bestvideo[vcodec^=avc1]+bestaudio/best" 'https://www.youtube.com/watch?v=EngW7tLk6R8'  2>&1 &
```

**Comment by Haxprox** [comment]
Still with no luck from my side. It can't run from the Dashboard with '&'.
Seems like somewhere on my side. Apologies for spending your time.

Thanks for supporting!
Have a nice day!

**Comment by bugy** [comment]
No problem at all. If you need further help, feel free to contact me
