### ISSUE TITLE
same_arg_param parameter doesn't work

### ISSUE THREAD

**Issue by deelerke** [bugy/script-server#441]
I'm trying to get a result like --ip=1.1.1.1
but keep getting --ip= 1.1.1.1

```
"name": "destination IP",
      "default": "",
      "required": "false",
      "type": "ip",
      "same_arg_param": "true",
       "param": "--ip="
},
```

for a test, I just did an 'echo $1 $2 $3' as the script....

**Comment by bugy** [comment]
Hi, are you using dev version or 1.16?

**Comment by deelerke** [comment]
I believe it's 1.15.2 (is there a file to check this? Didn't see the version number in the README.md)
thanks!!

**Comment by bugy** [comment]
You can mouse over script server title in the left upper corner.
Could you try dev version please?
Or 1.16 (but the setting called repeat_param there, as far as i remember)

deelerke ***@***.***> schrieb am Di., 18. Mai 2021, 08:41:

**Comment by deelerke** [comment]
thanks! I'm unable to upgrade at the moment, but I trust it to be fixed there
