### ISSUE TITLE
Load data from script execution doesn't work

### ISSUE THREAD

**Issue by drehelis** [bugy/script-server#442]
Hi,

Seems like below feature is broken on `dev`
https://github.com/bugy/script-server/wiki/Script-config#script

```
  "parameters": [
    {
      "name": "Test",
      "param": "--profile",
      "type": "list",
      "values": [
        "Test 1",
        "Test 2"
      ],
      "required": true
    },
    {
      "name": "Test 2",
      "param": "--test",
      "values": {
        "script": "echo ${Test}"
      },
      "required": true
    }
  ]
```

This used to work in `1.6`

**Comment by bugy** [comment]
Hi @autogun it works for me, (if I add `"type": "list"` to the second parameter)

**Comment by bugy** [comment]
![image](https://user-images.githubusercontent.com/1275813/119256758-86875e00-bbc2-11eb-904e-3a11d8e7c60f.png)

**Comment by autogun** [comment]
I can swear it also worked with `"type": "text"`, no?

**Comment by bugy** [comment]
I don't think so. How is it supposed to work?

**Comment by autogun** [comment]
This is embarrassing, I think I have custom code which I forgot about :-D
