### ISSUE TITLE
It is possible to run a script at the launch of script server ?

### ISSUE THREAD

**Issue by Clemorange22** [bugy/script-server#453]
I am running a discord bot with script-server (it allows me to easily view logs of bot).
It is possible to launch the script when script-server launch so I don't need to manally start it ?
( I am using trusted ips login )

**Comment by bugy** [comment]
Hi @Clemorange22, unfortunately there is no such possibility in script server. But you could create your own launching script, which would start both

**Comment by Clemorange22** [comment]
Ok, thanks
