### ISSUE TITLE
Environment Variables Missing In Output Files Directive

### ISSUE THREAD

**Issue by vbaidak** [bugy/script-server#454]
Hi!

Here is a part of my runners json:
```json
  "parameters": [
    {
      "name": "Collection Name",
      "description": "Collection Name",
      "required": true,
      "type": "text"
    },
    {
      "name": "Export Directory",
      "constant": true,
      "default": "$$HOME"
    }
  ],
  "output_files": [
    "${Export Directory}/${Collection Name}.json"
  ]
```

What's strange is that `${Export Directory}` is always empty, however environment variable is present. Am I missing something?

**Comment by bugy** [comment]
Hi, thanks for reporting, looks like a bug. I committed a quick fix, may be you could try dev version, once it's built

**Comment by bugy** [comment]
The build is finally done. There were some issues with docker hub pull limit

**Comment by vbaidak** [comment]
Hi, @bugy !

I'm confirming this fix works in the current **dev**.

Thanks!

**Comment by bugy** [comment]
Cool, thanks for confirming
