### ISSUE TITLE
Is it possible to use environment variables to configure script-server?

### ISSUE THREAD

**Issue by zrks** [bugy/script-server#456]
As title says - do we have such possibility?
That would ease secret management

**Comment by bugy** [comment]
Hi Marcis,
This feature is available only for some fields (like passwords or default
values)
You can use env variables by using $$VAR_NAME syntax (i.e. double dollar
sign)

Marcis Veveris ***@***.***> schrieb am Di., 8. Juni 2021,
11:49:

**Comment by zrks** [comment]
Thank you very much, will try.
Awesome work by the way :)
