### ISSUE TITLE
[feature] Add possiblity to run via SSL

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#46]
Currently script server is working via plain HTTP only. There should be possilibility to turn on HTTPS. 

Proposal:
1. Add conf folder
2. Read web.json configuration from conf folder
3. If ssl parameter exists there, read key and cert paths from it
4. Start http server with ssl config, on the port 5443
5. Add port parameter to web.conf file, which will allow to override default port
6. Move current script configurations locations to conf/runners

Additionally: test on windows

**Comment by bugy** [comment]
Implemented as specified in the description

**Comment by bugy** [comment]
Tested on Win.
Need to add ssl test files (cert and key)

**Comment by shinebayar-g** [comment]
If I'm running Nginx with SSL in front of script-server. Do I need to add SSL to script-server too?
