### ISSUE TITLE
Is it possible to password protect an entire group (collapsable header on the UI)?

### ISSUE THREAD

**Issue by tsp-kucbd** [bugy/script-server#460]
We are making great use different groups ability provided by the collapsable header on the UI. (the "group" property in the script config.
Is it somehow possible to password protect a complete group? e.g. that expansion/unfolding of the group is only possible with a password?

**Comment by bugy** [comment]
Hi @tsp-kucbd, unfortunately this is not possible
But the group won't be shown, if it's empty (i.e. all the scripts are protected)

**Comment by tsp-kucbd** [comment]
Ok, great. That's useful!
