### ISSUE TITLE
Import of CSV

### ISSUE THREAD

**Issue by billybenson** [bugy/script-server#462]
Hi - is there a way to import a csv so it can be used when executing the script? I want to use data in the csv for my script. How is best to do this? Thanks

**Comment by bugy** [comment]
Hi @billybenson you could make an "upload" parameter: https://github.com/bugy/script-server/wiki/Script-config#file_upload
Then a user would be able to upload the csv file
The script would get the path to the uploaded file as an argument

**Comment by billybenson** [comment]
Hi - thanks for replying. But then how do we use this CSV as a variable in a Powershell script if the temp directory changes ?

**Comment by bugy** [comment]
The shell script will always get an absolute path to the new uploaded file

billybenson ***@***.***> schrieb am Mi., 16. Juni 2021, 15:19:

**Comment by bugy** [comment]
@billybenson did you manage to find a way how to use the csv parameter?
