### ISSUE TITLE
regex parameter checking

### ISSUE THREAD

**Issue by hamsterbacke** [bugy/script-server#466]
Hi there, sorry that I couldn't check the history case sensitive thing yet.
Now I would like to propose a regex check for parameters. It is great to have parameters as int oder text oder something like that. It would be also great to enforce some additional rules. This could be achieved with giving a regex as type.
I also have such things in my script but it would be great to enforce it on more levels.
I guess it wouldn't be a security features as in input validation because the validation would be in javascript but maybe a nice feature?

**Comment by bugy** [comment]
#459 it's being implemented by @autogun :)
By the way, validations in script server always happen both on UI and server side, so it should be safe

**Comment by hamsterbacke** [comment]
that is awesome :)
