### ISSUE TITLE
Scrolling log for running jobs in history

### ISSUE THREAD

**Issue by ThomasWnk** [bugy/script-server#468]
In the job-view, after klicking "execute", the command output will be scrolled so that the job execution can be observed.
I'd like this for the history, too, for jobs that are in running state.

**Comment by bugy** [comment]
Hi @ThomasWnk, I think this is the same as https://github.com/bugy/script-server/issues/170, is it?

**Comment by ThomasWnk** [comment]
> Hi @ThomasWnk, I think this is the same as #170, is it?

I think it is, yes.

**Comment by bugy** [comment]
Thanks for the quick response. Then I'll close this one as a duplicate
