### ISSUE TITLE
HTTP (5000) to HTTPS (5443) Redirect?

### ISSUE THREAD

**Issue by jarrah31** [bugy/script-server#469]
Is it possible to configure an automatic redirect to HTTPS please?

My script server was initially set up with HTTP access on port 5000, but I've now figured out how to implement our corporate certificate to use HTTPS/SSL on port 5443 on my test environment. 

If I include the two SSL configuration lines (below), script server is then only accessible via 5443 (HTTP/5000 no longer works). I have tried specifying port 5000 with HTTPS, but old bookmarked links to HTTP/5000 don't work (as expected). I would need to tell all the users who access script server to update their bookmarks (which would be fine), but ideally a HTTP to HTTPS redirect would be a more seamless option. 
```
  "ssl": {
    "key_path": "testing/ssl/script-server.key",
    "cert_path": "testing/ssl/script-server.crt"
  },
```
Thanks.

**Comment by bugy** [comment]
Hi, I'm afraid this is not possible :( I think you could use some reverse proxy for it
SSL support in script server is very basic, as most people keep it on HTTP and just put reverse proxy in front

**Comment by jarrah31** [comment]
No problems at all, thanks for letting me know!
