### ISSUE TITLE
Line breaks between parameters

### ISSUE THREAD

**Issue by tsp-kucbd** [bugy/script-server#470]
Is it possible to force a line break/\<br> or a breaking text field after a parameter field?
Like imagined in this fake screenshot below - instead of parameter fields flowing one after each other, having them separated by a forced line break or a line breaking description field.

![image](https://user-images.githubusercontent.com/54399273/126155924-c61ac3d2-802e-43bb-87b9-50a54f588a5f.png)

cheers
/T

**Comment by bugy** [comment]
Hi @tsp-kucbd, unfortunately this is not possible. I think this is the same request as #182
