### ISSUE TITLE
Ability to format the parameters in a script in the WebUI

### ISSUE THREAD

**Issue by dwestness** [bugy/script-server#477]
Currently all parameters for a script are displayed in a horizontal list in the WebUI
Is it possible to have them display in a vertical list instead?

E.G.
Current (Horizontal):
![image](https://user-images.githubusercontent.com/48287057/128184729-c70e1986-0ffd-446c-b8ea-9b8462e4166a.png)

New (Vertical):
![image](https://user-images.githubusercontent.com/48287057/128184889-46f55d91-3642-4988-bb3f-baa18612d2ae.png)

**Comment by bugy** [comment]
Hi, unfortunately this is not possible. I think this is similar to https://github.com/bugy/script-server/issues/182

**Comment by dwestness** [comment]
Understood. Not a big deal, but wanted to ask. Thank you!
