### ISSUE TITLE
Question: when starting a script that forks an infinite loop process in background the status keeps on running

### ISSUE THREAD

**Issue by hamsterbacke** [bugy/script-server#482]
When I start a bash shell script and this script forks another process with an infinite loop in the background, the status keeps to be running. Is there a way to overcome this?
The command looks like:
/home/someuser/sm/somescript.sh $i 202105 1 &

**Comment by bugy** [comment]
Hi @hamsterbacke as far as I understand, the new process is still attached to a parent process (i.e. parent/child relationship there). So the parent process waits for all the children to finish.

Could you try solutions from this SO answer, please?
https://unix.stackexchange.com/questions/269805/how-can-i-detach-a-process-from-a-bash-script

**Comment by hamsterbacke** [comment]
Neither disown nor nohup did the job. Answer which suggested "at" did the trick: https://unix.stackexchange.com/a/269846

**Comment by bugy** [comment]
Thanks for sharing the solution, @hamsterbacke!

I won't change existing script server behaviour here (to avoid unexpected zombie processes). For those, who really want to keep detached processes running, they should use your solution
