### ISSUE TITLE
How to generate a parameter based on another parameter

### ISSUE THREAD

**Issue by Savamoti** [bugy/script-server#488]
Hi,
I have 2 parameters:
- first-list
- second-list
![image](https://user-images.githubusercontent.com/32238565/132102166-dc9cfac2-2265-404e-8074-f52a6af0b94d.png)
```
{
  "name": "test",
  "script_path": "scripts/test/test.py",
  "parameters": [
    {
      "name": "first-list",
      "required": true,
      "type": "list",
      "values": [
        "a",
        "b",
        "c"
      ]
    },
    {
      "name": "second-list",
      "type": "list",
      "values": [
        "1",
        "2",
        "3"
      ]
    }
  ]
}
```

Looking for a way to generate second-list that based on first-list, for example:
When "a" chosen, run script `gen_a` and fill values in second-list,
When "b" chosen, run script `gen_b`...

Is that possible?

**Comment by bugy** [comment]
Hi, yes, it's possible, could you check this section please?
https://github.com/bugy/script-server/wiki/Script-config#values

Savamoti ***@***.***> schrieb am Sa., 4. Sept. 2021, 19:01:

**Comment by Savamoti** [comment]
I can generate values for parameters via another script, once(when I open main script?). That's great.
scripts/runners/test.json
```
{
  "name": "test",
  "script_path": "scripts/test/test.py",
  "parameters": [
    {
      "name": "first-list",
      "required": true,
      "type": "list",
      "no_value": false,
      "values": [
        "a",
        "b",
        "c"
      ]
    },
    {
      "name": "second-list",
      "type": "list",
      "values": {
        "script": "scripts/gen.py"
      }
    }
  ]
}
```
scripts/gen.py
```
#!/usr/bin/env python3

import sys

# argument not given, print all
if len(sys.argv) < 2:
    for i in range(1,4):
        print(i)
    sys.exit()

if sys.argv[1] == "a":
    print("1")
elif sys.argv[1] == "b":
    print("2")
elif sys.argv[1] == "c":
    print("3")
```
![image](https://user-images.githubusercontent.com/32238565/132103620-6ac19310-0929-4c68-9fcb-b84c6b060332.png)

But I'm trying to do a little different.
Depending on which variable is selected in the first parameter(a, b, c), generate different lists for the second parameter.
When I choose in first parameter **a**: generate **1** to second-list.
When I choose **b**: generate **2**.
When I choose **c**: generate **3**.

How can I pass a selected variable to another script(to: `scripts/gen.py a`)?

**Comment by bugy** [comment]
You pass it using ${param_name} syntax
So the values script is called every time, when  param_name parameter
changes

Savamoti ***@***.***> schrieb am Sa., 4. Sept. 2021, 19:52:

**Comment by Savamoti** [comment]
Thank you @bugy, this is exactly what I wanted.

by the way - your app is convenient as hell!

**Comment by Savamoti** [comment]
Struggling with another thing, how can I bind the OR logic for the parameters?
If **first-list** is set, then the **second-list** will be empty, and vice versa.

**Comment by bugy** [comment]
Unfortunately OR logic is not supported

Savamoti ***@***.***> schrieb am So., 5. Sept. 2021, 08:46:
