### ISSUE TITLE
external access to scripts

### ISSUE THREAD

**Issue by jpf01** [bugy/script-server#504]
Hello

first of all, CONGRATS for the great job....seems easy, and the first tests dont give any problem

sorry if this is not an issue, but a more a question:

i need to execute the script from another LAN computer.....i add my proxy IP on _def_trusted_ips_ and i reach the admin page, but in the scripts page the EXECUTE button is disabled with error: _Failed to load script info. Try to reload the page. Error message:
Failed to connect to the server_

log:
_2021-11-18 14:50:54,801 [tornado.access.INFO] 304 GET /auth/info (10.144.128.254) 2.00ms
2021-11-18 14:50:54,804 [tornado.access.INFO] 304 GET /conf (10.144.128.254) 3.99ms
2021-11-18 14:50:54,815 [tornado.access.INFO] 304 GET /scripts (10.144.128.254) 7.00ms
2021-11-18 14:50:54,818 [tornado.access.INFO] 304 GET /executions/active (10.144.128.254) 1.00ms_

its all by default....

thanks in advance

**Comment by bugy** [comment]
Hi @jpf01, I hope I answered you in gitter :)

**Comment by jpf01** [comment]
thanks....i change port for another not managed by the proxy, and works like a champ!
