### ISSUE TITLE
Code editor?

### ISSUE THREAD

**Issue by ReisRyos** [bugy/script-server#506]
Screenshots show the code editor. But there is no button in the GUI to edit scripts code. How to use it?

**Comment by bugy** [comment]
Hi @ReisRyos, which version are you using? code editor available only in dev version

**Comment by ReisRyos** [comment]
Version: 1.17.0-master@9a57ce1

**Comment by ReisRyos** [comment]
I'm sorry. I'm a real noob. I didn't notice the menu under the "three dots" that opens the editor.

**Comment by ReisRyos** [comment]
solved
