### ISSUE TITLE
runner does not appear in GUI when working_directory ends with slash

### ISSUE THREAD

**Issue by RollingHog** [bugy/script-server#522]
Replication:
* add `working_directory `parameter ending with slash `/`. Example: `/home/dp/Desktop/MyProject/`

Proposal:
* if it's caused by failed parsing - show "cannot parse [json]" (see #521)
* alter parsing code and allow trailing slash

I can try to implement first or second solution as soon as repo owner choose which one is preferable

**Comment by bugy** [comment]
Hi @RollingHog, I'm not 100% sure if I understand it.
Is it json parsing error or some other error on script server side? Because if it's json error, then the json file is corrupted and should be formatted properly with json

**Comment by RollingHog** [comment]
Sorry, will try to clarify. You see, this file
```json
{
  "script_path": "docker-compose up -d",
  "working_directory": "/home/dp/Desktop/backend"
}
```
appears in web GUI left panel properly; but this file (which only difference is trailing slash `/` in `working_directory` key) doesn't:
```json
{
  "script_path": "docker-compose up -d",
  "working_directory": "/home/dp/Desktop/backend/"
}
```

My system is (L)ubuntu.

**Comment by bugy** [comment]
And which error do you see in server logs?

**Comment by RollingHog** [comment]
I must apologize. Error does not replicate, logs are clear. I'm not sure why I didn't see scripts but looks like it was not because of trailing slash. I'll try to replicate it later with fresher head, but looks like it doesn't cause the problem.
