### ISSUE TITLE
file_upload large files

### ISSUE THREAD

**Issue by antonellocaroli** [bugy/script-server#523]
I was trying file_upload

seems to work with small files, but with large files I get this message, am I doing something wrong

```
Calling the script...

Connection error. Please contact the system administrato
```

**Comment by bugy** [comment]
@antonellocaroli could you try this setting?
https://github.com/bugy/script-server/wiki/Server-configuration#max_request_size

**Comment by antonellocaroli** [comment]
@bugy I have never used conf/conf.json
as it should be in this case?
