### ISSUE TITLE
LDAP group for accessing script

### ISSUE THREAD

**Issue by fnpanic** [bugy/script-server#528]
Hi,

currently it is only possible to use a group for general access to script server via LDAP.

It would be handy to also limit scripts via groups. If you get the membership of a user at login then this could be matched without exessive queries or is there a reason why it is not in?

**Comment by bugy** [comment]
Hi, it should also work for script access, the same syntax

fnpanic ***@***.***> schrieb am Do., 24. Feb. 2022, 12:13:

**Comment by muzzol** [comment]
yeah, I'm using groups pulled from LDAP to filter my scripts.

this is my main conf:

```
{
  "auth": {
    "type": "ldap",
    "url": "ldap://ldap.example.net",
    "username_pattern": "uid=$username,ou=Users,dc=example,dc=global",
    "version": 3
  },
  "access": {
    "allowed_users": [ "fixeduser01", "@rol-system", "@rol-support" , "@rol-telephone" ],
    "admin_users": [ "@rol-system" ]
  },
  "title": "MY Scripts"
}
```

and on runners I got something like this:

`"allowed_users": [ "127.0.0.1", "@rol-system", "@rol-support" ],`

**Comment by fnpanic** [comment]
Awesome! Thanks for pointing this out. Was not clear to me from the docs.
