### ISSUE TITLE
Not having success with running scripts - noob

### ISSUE THREAD

**Issue by skaboy71** [bugy/script-server#531]
Apologies but I can't seem to run a script.

I keep getting:
No such file or directory: './conf/runners/test3.py'

I'm not sure where/ how to enter the commands.

I'm running the server with the params:
 -f '/var/script-server/conf/serverconf.json' -d '/var/script-server/conf'

I can get into the UI, I can get to the admin.  I'm trying to run the script ffrom the ./conf/runners/ dir but having no luck.

I know I'm just missing something stupid but can you help?

![image](https://user-images.githubusercontent.com/5784265/155901165-2531f166-aef5-4bf3-ab28-d2e91de6a1e5.png)

**Comment by skaboy71** [comment]
ahh ... nevermind.  I figured it out.  Thanks!  keep up the good work!

**Comment by bugy** [comment]
I'm happy that you found a solution :)
