### ISSUE TITLE
Version mismatch in version.txt

### ISSUE THREAD

**Issue by everlanes** [bugy/script-server#554]
Hi,

I just downloaded the latest release ZIP-file 1.17.0.
This contains a version.txt file with the content: `1.18.0-master@caf25c0`

Is it intentional, that the version numbers differ?

Cheers,

  Andreas

**Comment by bugy** [comment]
Hi @everlanes, no, this is wrong. For stable releases the version should match

**Comment by everlanes** [comment]
Thank you for the information. Are you going you provide a new 1.17.0 file or should I wait for next stable release?

**Comment by bugy** [comment]
Hi @everlanes please use release 1.17.1, version.txt seems to be good there.
I still don't know why it happenned, will keep an eye on it for future releases
