### ISSUE TITLE
How do I use file uploading?

### ISSUE THREAD

**Issue by Beinish** [bugy/script-server#563]
Hello,
I'm trying to understand how to properly use the file-upload feature.

I would like to use it as a wrapper for uploading files to my S3 bucket.
Not sure if it's possible the way I think of it, but I would like to upload a file to the scriptserver > then to S3 somehow.

The issue I'm having is that I don't know where the file will be located at. I know the name, I know it's under the temp folder, but what from there?

Thanks

**Comment by hank-pim** [comment]
it will pass the file's path as an argument to your script. here is a simple python3 example that will pull in the first argument/parameter in your script runner and print it. 


import sys
uploadedfile = sys.argv[1]
print(uploadedfile)

**Comment by Beinish** [comment]
thank you @hank-pim this is perfect. This should enable me to continue with the uploading to S3 part.

Thanks!
