### ISSUE TITLE
How to send complex texts in text field?

### ISSUE THREAD

**Issue by Nottt** [bugy/script-server#564]
I have a script that takes as input complex text, with new lines, emojis, special characters, everything.

This being the configuration:

```
   "parameters":[
      {
         "name":"TEXTO",
         "type":"text",
         "param":"-text",
         "required":true
      },
      {
         "name":"LINK",
         "type":"text",
         "param":"-link",
         "required":false
      }
```

However when people copy and paste into the text box it loses all the new lines. Is there a way to avoid that ?

**Comment by bugy** [comment]
unfortunately this is not supported
https://github.com/bugy/script-server/issues/475

**Comment by Nottt** [comment]
there is really no way to add this?

**Comment by Nottt** [comment]
Is there any workaround ?

**Comment by bugy** [comment]
Not any easy one, which I'm aware of, unfortunately

ad90xa0-aa ***@***.***> schrieb am Fr., 22. Juli 2022, 03:34:
