### ISSUE TITLE
Pass variable to script shell from browser

### ISSUE THREAD

**Issue by Trawx** [bugy/script-server#566]
Hi @bugy 

I really have liked your script server . just I still missing one point, could you please explain to me how I can enter variables to my script throw browser?
example: 

in commande line I can run my script.sh like this:    # source ./myscript.sh var1 var2 
is this possible to made using your script server ? I want to enter it through browser like this
![image](https://user-images.githubusercontent.com/111055945/184117888-04123329-53b4-4a93-be38-855949a49b19.png)

and this is the configuration on Admin side 
![image](https://user-images.githubusercontent.com/111055945/184118014-46200463-69ec-4a81-90ef-3376a6f6e84b.png)

could you support please, Vielen dank :D

**Comment by Trawx** [comment]
hi @bugy, 


yes you are right, just I want know how I can enter 2 variables to my script from browser.
example let say that I have script shell for a calculator and I want to do something like this:
#source ./myscript.sh 1 4 
that means the script will took first variable is "1" and second is "4". is that possible to made using script server ? 

many thanks to you !

**Comment by bugy** [comment]
Hi @Trawx I'm confused. You are doing it already :)

**Comment by Trawx** [comment]
@bugy 

I'm doing it but it's not working, I have 2 variables "PASSWORD" and "PATH". don't get confused with PATH. it's just variable not a file. 

I have create a script in Admin panel, then I have entered 2 parameters. ( is the configuration on the previous picture is correct ?

this is what I see on logs: 
 Calling script #28: /home/ubuntu/tmp/conf/scripts/sync_images_windows.sh $1 ****** $2 'C:/Users/Ghassen/Desktop/myphotos'
 
 
 my script.sh : 
 
 password="$1"
 path="$2"
 
 
 then I will use those 2 variables in my script. 
 
 
 is all this correct, thanks again

**Comment by bugy** [comment]
please remove `$1` `$2` a param section

**Comment by bugy** [comment]
You only need these 3 options:
![image](https://user-images.githubusercontent.com/1275813/184122962-6db0f3db-bbcb-4294-bc63-a495cd880409.png)

Everything else should be empty/disabled (except password, where you should use `secret`)

**Comment by Trawx** [comment]
thank you @bugy , you save my day! I don't know how the generated json file doesn't take my changes. so I changed manually and remove $1 $2 . thank you again we can close this issue.
