### ISSUE TITLE
Interactive terminal options

### ISSUE THREAD

**Issue by SergeWielhouwer** [bugy/script-server#568]
Hi bugy,

Thank you for developing this nice and user-friendly web UI to start and keep track of running scripts. 

I would like to know if interactive terminal options, where (for example) you use the arrow keys to navigate through the terminal, can be used.

Below an example using the inquirer package for Python. I am currently unable to use the up/down and spacebar to go through the selection list

![image](https://user-images.githubusercontent.com/87863674/185628477-7577aa07-8b03-4974-90f1-4f9291cb8dec.png)

Is support for this considered or do you have any suggestions/ideas on this?

Best regards,

Serge

**Comment by bugy** [comment]
Hi @SergeWielhouwer unfortunately this is not supported :( And I don't have plans for it

**Comment by SergeWielhouwer** [comment]
Hi @bugy, I will try to work around it, thanks for your fast and clear reply 👍
