### ISSUE TITLE
Wanted to add a extra column in history page which is related to one specific script

### ISSUE THREAD

**Issue by BeingCreative09** [bugy/script-server#573]
Actually i was using script server as my side project.And it is awesome becoz my friend just have to press execute and everything happens on fly super.I just wanted to know can i add one column into my history page as i have to maintain one column related to scipt running.Is it possible
Thank you

**Comment by bugy** [comment]
Hi @BeingCreative09 which data should be in this column? Is it some text from the output?

**Comment by BeingCreative09** [comment]
Hii,
Thank you for your reply.
I have script for example it takes 3 inputs
I have to display the 3 input value with lets take column name as input3
followed by the value to it

**Comment by bugy** [comment]
Sorry for late reply, there is a ticket for it already:
https://github.com/bugy/script-server/issues/382

Unfortunately I didn't have time to work on it
