### ISSUE TITLE
bat script can't recognized parameter

### ISSUE THREAD

**Issue by mgfjx** [bugy/script-server#576]
Windows script does not recognize the passed parameter. Is it a bug?
![image](https://user-images.githubusercontent.com/13596540/191222046-4f6a4203-3808-4b4e-a098-3455b0e4b1fd.png)
![image](https://user-images.githubusercontent.com/13596540/191221785-7b55383e-37f1-40d8-8a27-178599fd5cc8.png)
![image](https://user-images.githubusercontent.com/13596540/191221873-fec45d36-d748-4dc9-a4b0-c208b31e0245.png)
![image](https://user-images.githubusercontent.com/13596540/191222588-b4003577-be98-47aa-9ad0-8feb6c76a97b.png)

**Comment by bugy** [comment]
Hi @mgfjx please remove the parameter from "script path". All the parameters are appended automatically

**Comment by mgfjx** [comment]
![image](https://user-images.githubusercontent.com/13596540/191222953-389dbd30-e1d5-4724-80bb-4fb06b175de6.png)
Python scripts also do not recognize parameters.

**Comment by mgfjx** [comment]
> Hi @mgfjx please remove the parameter from "script path". All the parameters are appended automatically

It works! Thank you very much.

**Comment by bugy** [comment]
Glad it helped :)
