### ISSUE TITLE
can we set some Image below description of scripts ?

### ISSUE THREAD

**Issue by jack99trade** [bugy/script-server#578]
Hi wanted to ask if there is an option to set some image while creating a script for user. just like there is a description for a task.

**Comment by bugy** [comment]
Hi, if an image is available by some public URL, you can use markdown syntax
`![Hello World](https://website.com/path/image.png)`

**Comment by jack99trade** [comment]
> Hi, if an image is available by some public URL, you can use markdown syntax `![Hello World](https://website.com/path/image.png)`

Hi Thanks it works for me :) able to see the image.  

just one question. how do I define the size of this image. it is filling the complete page. if possible to define the size would be nice. I tried something like {:height="36px" width="36px"}.  Do you have some suggestion.

**Comment by bugy** [comment]
Oh, actually there is another way:
just use `<img src="https://localhost/images/steps.png" width="36" height="36">`

**Comment by jack99trade** [comment]
> Oh, actually there is another way: just use `<img src="https://localhost/images/steps.png" width="36" height="36">`

@bugy Thank you Mate.. this is working for me. very nice 💯
