### ISSUE TITLE
не работает скрипт сервер

### ISSUE THREAD

**Issue by sata20** [bugy/script-server#579]
Здравствуйте установил  запустил но админ панель не работает  и не не могу найти  ее как запустить где нужно поправить заранее спасибо еще раз помогите пож

**Comment by bugy** [comment]
Нужно больше информации. Как запускаете, какие конфиги, авторизация. 
По умолчанию, без авторизации и на локальном сервере, админ панель доступна через admin.html, или ссылка на неё через главную страницу, слева сверху, иконка шестерёнки (если там иконка гитхаба, значит одно из условий выше не выполнено)

**Comment by sata20** [comment]
еще раз здравствуйте  а какую ос нужно поставить ??  дебиан 10 тую ставил
11 тую ставил все тоже самое 1 страница главная грузиться и все. а вот
админка не грузиться для запуска скрипта  очень она мне нужна могу ли я вам
предоставить данные от сервера и можете мне. скинуть подробную инструкцию и
како. нужно  скрипт сервер скачать  все дела по этим шагам больеш не
xutj не делал




Installing on virtualenv (linux)
Shinebayar G edited this page on 3 Sep 2019 · 3 revisions
 Pages 14
Find a page…
Home
Admin interface
Authentication
Authorization
Installing on virtualenv (linux)
OpenBSD process termination issues
Reverse Proxy setup
Running as a linux service
Script config
Script scheduling
Server configuration
Store config in Git
Themes
Upgrade script (linux)
Clone this wiki locally
https://github.com/bugy/script-server.wiki.git
Install python virtualenv using (replace apt with your package manager)

######
Установка на чистый сервер делал по таким шагам

1) sudo apt install python3-venv
2) python3 using python3 -m venv any/path/envname
3) source any/path/envname/bin/activate
4) mkdir -p any/path/script-server && cd any/path/script-server
5) wget
https://github.com/bugy/script-server/releases/latest/download/script-server.zip
6) unzip script-server.zip
7) pip install -r requirements.txt
8) python launcher.py

Все после чего страница запускатся но там все пусто !!!


Create virtualenv named envname for python3 using python3 -m venv
any/path/envname
Enter to virtual env source any/path/envname/bin/activate
Check python version using python -V
Create a folder for script server and navigate to it mkdir -p
any/path/script-server && cd any/path/script-server
Download latest release wget
https://github.com/bugy/script-server/releases/latest/download/script-server.zip
Extract zip contents unzip script-server.zip (If unzip command not found,
install unzip with sudo apt-get install unzip)
Install requirements pip install -r requirements.txt
Run the server python launcher.py
Bonus: If using virtualenv's python, then systemd startup script python
path would be:

Find out virtualenv's python path (When virtualenv is activated) which
python copy result
Edit /lib/systemd/system/script-server.service ExecStart=/usr/bin/python3
would be -> paste here Example something like this:
/home/user/script-server/envname/bin/python
The similar change should be done for init.d

Notes: If you're getting

пт, 23 сент. 2022 г. в 12:14, Iaroslav Shepilov ***@***.***>:

**Comment by sata20** [comment]
server - 188.127.235.108
login - root
passwd - dX0pA7sE5sgP

чистый ос дебиан 11 поставил  а еще ее можно установить на  ubuntu 18 04 или по выше ??

**Comment by bugy** [comment]
Пожалуйста, не указывайте данные в публичных тикетах :)
Я так понимаю, вы это устанавливаете на какой-то хост, а не на локальную машину?
Админка по умолчанию доступна только если на localhost подключаться

Чтобы иметь админ доступ на удаленном хосте, нужно пользователя сделать админом. Как это сделать зависит от метода аутентификации, который вы выберете

**Comment by sata20** [comment]
так это простой сервер можете. там мне установить пож   или как. с вами связаться мне очень нужно установить и проверить этот скрипт а то в ручную запускать очень как то не удобно хотел бы попросить вас даже и о платной услуги если поможете мне как то решить этот. вопрос

**Comment by bugy** [comment]
Напишите на почту, buggygm@gmail.com

**Comment by sata20** [comment]
спасибо шас

**Comment by RollingHog** [comment]
I have a feeling this ticket can be safely closed.
