### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 7054company** [bugy/script-server#593]
launcher.py: error: unrecognized arguments: logs

**Comment by bugy** [comment]
Hi @7054company could you kindly provide a bit more details?

**Comment by 7054company** [comment]
It fix by resetup it.

**Comment by 7054company** [comment]
After succesfully launched then close it by exit 
retry to lauched it give error
launcher.py: error: unrecognized arguments: logs

**Comment by bugy** [comment]
I still cannot help without any details, unfortunately

**Comment by 7054company** [comment]
What do you mean?

**Comment by 7054company** [comment]
Wait can you setup it in my server i provide you server ssh link

**Comment by bugy** [comment]
What did you configure, how do you try to run it

**Comment by bugy** [comment]
I'm sorry, but I won't setup it myself

**Comment by 7054company** [comment]
Mean you have to show me live demoenstration pls with admin panel

Beacuse i run it one time obline index.html work admin.html not work
So please could you help me???
Reply

**Comment by 7054company** [comment]
No you have to show how i ran in my own server i give you my ssh

**Comment by bugy** [comment]
https://github.com/bugy/script-server/wiki/Admin-interface
here is the documentation for admin interface

**Comment by 7054company** [comment]
pls bro!!!!

**Comment by 7054company** [comment]
My problem is i run python3 laucher.py but only index.html works any other function shows 404

**Comment by bugy** [comment]
I'm really sorry, I already put quite some time into the project and documentation. I find it fair, if you would read the documentation and setup everything yourself. 
I can give some answers to uncertain questions, but I do not have time to do some demo or setting up anything

**Comment by 7054company** [comment]
I will give you a link of ssh connect it pls

**Comment by 7054company** [comment]
ssh
4RZvHMaFBZaU4CbTSPg4PgTyg@sfo2.tmate.io

**Comment by 7054company** [comment]
no pass require

**Comment by 7054company** [comment]
I am single user bro
