### ISSUE TITLE
Ability to backup history

### ISSUE THREAD

**Issue by gautam-nutalapati** [bugy/script-server#600]
Hey Script-Server Team!
For compliance and tracking purposes, it would be good to have ability to backup history. We loose the history today when script server restarts.
Proposal:
- [Manual] Download option for history
- [Automated] Provide ability to access script history via scheduled job, so that users can write their own backup jobs (e.g. job that runs every X hrs and sends history file to AWS S3)

**Comment by bugy** [comment]
Hi Gautam, script server stores history on a hard drive, so normal restarts
won't delete the history.
Are you using docker, and just restart a container, may be?

Gautam ***@***.***> schrieb am Mo., 28. Nov. 2022, 22:07:

**Comment by gautam-nutalapati** [comment]
Thanks for quick response!
yep, I am using docker, and its restarted every time we make a change to our script server contents.
If it is being stored in HDD, can we run a job that transfers this file as needed? Where is this file located?

**Comment by gautam-nutalapati** [comment]
@bugy Thank you for this info!
I do see the history in the location `/app/logs/processes`.
Closing this issue.
