### ISSUE TITLE
Searching the script doesn't return the result if the scripts is under a group

### ISSUE THREAD

**Issue by jeffboon97** [bugy/script-server#621]
Dear @bugy  I wish you a good day. The script I am searching for doesn't appear when I search under an upper level.

Let's say I search [Script A], and Script A is grouped under [Script Directory]. the search result doesn't show [Script A] immediately, however I need to expand [Script Directory] to only see the search result.

I deeply appreciate your help to take a look into this issue. Thanks! <3

**Comment by bugy** [comment]
Hi @jeffboon97 it's the same as https://github.com/bugy/script-server/issues/325
I'm not convinced about proposed behaviour, you can find my reasoning in the linked ticket comments

**Comment by bugy** [comment]
Hi @jeffboon97 please read the linked issue and my concern regarding expanding groups
