### ISSUE TITLE
Can't run PS script on Windows 

### ISSUE THREAD

**Issue by oron89** [bugy/script-server#622]
Hi,
Thank you @bugy for the great tool!

I have a problem with Powershell on a Windows machine.
When I'm trying to trigger a Powershell script, it looks to be loading it, but nothing happens.

this is my runner:
`{
  "name": "ps",
  "script_path": "conf\\scripts\\ps.ps1",
  "description": "test",
  "output_format": "terminal",
  "parameters": []
}`

The script is just supposed to print something like that:
`Write-Host "hello from ps"`

Please let me know if more details need here.
Thank you!

**Comment by oron89** [comment]
@bugy any chance you have any idea here?

**Comment by bugy** [comment]
Hi @oron89 really sorry that I missed it :(

Could you try:
`"script_path": "powershell -file 'conf\\scripts\\ps.ps1'"` 
?

**Comment by oron89** [comment]
Works!
Thank you!
