### ISSUE TITLE
Regression from dev (Oct 22) vs dev (today) Linux bash

### ISSUE THREAD

**Issue by father-mande** [bugy/script-server#630]
Hi,
Short script (shell) displaying USER, HOME, PATH ... nothing more
in Dev from Oct result is like this (scriptserver running as root (but not the problem)
CONTROL ... U = root ; H = / ; P = /usr/local/AppCentral/scriptserver/python3_venv/bin:/sbin:/us........ etc.
using last Dev loaded today (02/24/2023) result is like : 
CONTROL ... U =  ; H =  ; P = /usr/local/AppCentral/scriptserver/python3_venv/bin:/sbin:/u...... etc.

So shell is started without USER nor HOME environment.
script have no args, just the shell /usr/local/bin/test.sh , output is text or terminal and pseudo terminal is checked.
Philippe.

**Comment by father-mande** [comment]
need more test to analyze ...

**Comment by bugy** [comment]
Cool, let me know if there are any updates :)

**Comment by father-mande** [comment]
Hi,
OK, I will manage next week series of tests to identify why this problem exist ... BUT at this time, I have it during some tests and no with a short rewrite ... so ... I prefer to determine if it's a writing script (accepted) but generating the error ... or an external problem (external to scriptserver). 

Philippe.
