### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by qk-santi** [bugy/script-server#631]
Hi @bugy !

More of a question than an issue.

What's the current roadmap to get to a new release on 1.18?
Is the head supposed to be stable enough to run?

I've been running 1.17 and can't wait to get some of the new features in 1.18 👍 

Thanks a lo for your amazing work!

**Comment by bugy** [comment]
Hi @qk-santi there are no plans yet, it can take a couple of weeks or months, depending on my free time

You can try dev version, it should be more or less stable. I know that at least some people are using it regularly, so they would report any major issues with it

**Comment by qk-santi** [comment]
Thanks @bugy ! 💪
