### ISSUE TITLE
parameters - name - colour

### ISSUE THREAD

**Issue by antonellocaroli** [bugy/script-server#634]
Hi @bugy ,

do you think it would be possible in the future to assign a specific colour to the parameter name? directly in the json file?
so that specific colours can be assigned to certain names so that they can be associated with each other?
i.e. the parameters of these colours belong to the same 'family/category'.

I don't know if I have explained myself well.

**Comment by bugy** [comment]
Hi @antonellocaroli could you share the use case please, why do you need it? I don't get the idea of this feature

**Comment by antonellocaroli** [comment]
in effetti non so se è strettamente necessario, ma lo pensavo in questa situazione:

parametri base:  par1,par2,par3
enable parametri avanzati1:  par4
i parametri successivi appartengono a avanzati1: par5,par6,par7
enable parametri avanzati2:  par8

**Comment by bugy** [comment]
If you would have all these parameter groups on separate lines, won't it be enough for a user to distinguish it? Or may be even having a line separator between those.

To be honest, I think using different colors on UI doesn't look great
