### ISSUE TITLE
Delete Script from frontend

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [bugy/script-server#641]
Hi @mgfjx, unfortunately this is not possible via UI
You can delete config files in `conf/runners` folder

_Originally posted by @bugy in https://github.com/bugy/script-server/issues/464#issuecomment-864361885_
            

Regarding this comment, why is that not possible?

**Comment by bugy** [comment]
Hi @EduardSchwarzkopf, what do you mean exactly?

**Comment by EduardSchwarzkopf** [comment]
yes, I know, but technically it is possible to implement, right?

**Comment by EduardSchwarzkopf** [comment]
Is there a contribution guideline? I'd like to add this feature

**Comment by EduardSchwarzkopf** [comment]
ok found it. Now the question is, how should the solution look like?
I thought of an icon here, probably the trash-bin icon:
![grafik](https://user-images.githubusercontent.com/48969167/228465187-cfaa416d-f78f-4af9-8baf-ee6fb9fabc2c.png)

**Comment by bugy** [comment]
Hey

> Is there a contribution guideline?

Unfortunately no. You can ask any questions, i could help with them

> Now the question is, how should the solution look like?

May be we should add it to a script configuration page? To prevent an unintended click in the table

Also, I'm not sure about permanent deletion. May be we could move it "to archive"? E.g. conf/deleted folder, and change prefix to .json.deleted. In this case it will be easier to revert unintended deletion
My point is, that some script configurations are very complex, so deleting it by accident might be super annoying

What do you think?

**Comment by EduardSchwarzkopf** [comment]
yeah, totally valid points. Where do you think would be the best place for that button?

**Comment by EduardSchwarzkopf** [comment]
sounds good. Not worked that much with vue before, but let's see how i can get this done :D
