### ISSUE TITLE
Configuration for scheduling

### ISSUE THREAD

**Issue by vnghia** [bugy/script-server#671]
Hi, I would like to ask if there is anyway to write down the scheduling configuration without any UI interaction. Theoritically, I think I could write down the json and copy it into `conf/schedules` but there are many fields like `id` and `user` which I am not sure if this is required or not ?

**Comment by bugy** [comment]
Hi, yes you can configure everything via json. Just copy one of the existing configurations
Id and user are required

**Comment by vnghia** [comment]
Thank you very much !
