### ISSUE TITLE
Default values for multiselect parameter

### ISSUE THREAD

**Issue by marikadabra** [bugy/script-server#672]
Hi!

Maybe i'm just missing something but... is it possible to specify default values (from a script) in a multiselect type parameter with checkboxes ticked in ui combobox where default values returned from script match?

Anyway.. great work! 

<3

**Comment by bugy** [comment]
Hi, yes, it's possible, just specify them as an array

**Comment by MNeill73** [comment]
Yep, the parameter config for multiselect accepts a list of default values
to check.

**Comment by marikadabra** [comment]
> Hi, yes, it's possible, just specify them as an array

Sorry.. my mistake.. was specifying string not array. It worked! Thank you!
