### ISSUE TITLE
File Upload Max Limit Change

### ISSUE THREAD

**Issue by Jaydip-Chabhadiya** [bugy/script-server#673]
I want to upload file >10MB but it shows error

**Comment by bugy** [comment]
Hey,

Please try this option
https://github.com/bugy/script-server/wiki/Server-configuration#max_request_size

**Comment by Jaydip-Chabhadiya** [comment]
It's working changed conf/conf.json

  "max_request_size": 100

Really appreciate your quickness 
Thanks for blazing fast response :)
