### ISSUE TITLE
Sort html table

### ISSUE THREAD

**Issue by enriquetoledano** [bugy/script-server#674]
Hi:

Would it be possible to apply a class or an ID to HTML table generated as output from a script, so that the table becomes sortable (similar to activity logs)?

Thank you and best regards

**Comment by bugy** [comment]
Hi @enriquetoledano I think with an iframe option, you can include javascript into your output code, which could include sorting as well.

**Comment by enriquetoledano** [comment]
Yes thanks, I've got it working that way.
I was just trying to use "html" instead of "html_iframe" (that I think is not recommended)

Thanks again

**Comment by bugy** [comment]
Just to note: iframe is not recommended as a default option. But of course, when you want to add some javascript, iframe is the only option.
