### ISSUE TITLE
Schedule repeat end date / execution count

### ISSUE THREAD

**Issue by UrekD** [bugy/script-server#676]
Hey,

For scheduling repeatable task it would be nice to have extra options to specify when the task should stop/not be executed anymore or how many times a task should execute.

For I instance I reworked the current repeatable option to require the end time to satisfy our needs as:
![image](https://github.com/bugy/script-server/assets/38784343/5b27f1b3-2e8b-41cc-b8b9-515e7a9ace8e)

I'm open to working on a proper implementation, but I'd need someone to do the frontend, as I'm terrible with that.

**Comment by bugy** [comment]
Hi @UrekD great idea, thanks. Feel free to submit PR for backend. 
You can try to do frontend too, it should be pretty simple in this case. I could tell you which classes are affected

**Comment by UrekD** [comment]
> Hi @UrekD great idea, thanks. Feel free to submit PR for backend. You can try to do frontend too, it should be pretty simple in this case. I could tell you which classes are affected

Hey @bugy, yeah I figured it would be much easier to edit the vue and build it than the manual js editing I did like an idiot before xD

After managing to get it to build on windows, I managed to construct the box shown below.

![brave_dpBB3Fl6x2](https://github.com/bugy/script-server/assets/38784343/7e5eea0d-225b-42b6-8983-9985f43cd258)

If you are happy with the structure of that I'll move onto the functional part. As you can see the styling is not good with that, if there is an easy way to handle that I'd appreciate that. The yet unformatted additions can be found [here](https://github.com/bugy/script-server/compare/master...UrekD:script-server:master).

**Comment by bugy** [comment]
Looks very good to me! If you struggle too much with styling, you can leave it for me

**Comment by UrekD** [comment]
Minor bug the date field is not required, so user can sent it empty as it just grabs the default value.

![image](https://github.com/bugy/script-server/assets/38784343/10ad6f37-d04a-413b-ba1f-ae7f63700caf)

**Comment by UrekD** [comment]
> Looks very good to me! If you struggle too much with styling, you can leave it for me

Ah I thought the styling was dynamic not static, in this case I got it.

![brave_XAUBlsHBCw](https://github.com/bugy/script-server/assets/38784343/a6fc127b-0e2b-42bd-9d76-3be1d83c7cb7)

I think I got the functionality down I'll give it a day or 2 test then open merge 😄
