### ISSUE TITLE
Is it possible to keep different colour for the groups and different color for the scripts inside the groups ?

### ISSUE THREAD

**Issue by sbalakrishna** [bugy/script-server#678]
Hi,
I would like to keep different colors for the main menu items and different color for the submenu items.
If it possible by editing the css files ?

The current theme won't support this option.

**Comment by bugy** [comment]
Hi @sbalakrishna you can add smth like this to theme.css:
```
.script-group {
    color: red !important;
}
```

(don't forget to reload a page with cache refresh, smth like ctrl + f5)

**Comment by sbalakrishna** [comment]
Thanks @bugy , it is working. We can close this issue

**Comment by sbalakrishna** [comment]
Thanks for your quick response.
