### ISSUE TITLE
Menu with categories of scripts instead of list

### ISSUE THREAD

**Issue by ludolhoir** [bugy/script-server#680]
Hello, first of all big thanks for script-server which is nice/great. We today are using it as kind of global IT Operations tool fr a lot of main needs using lots of scripts.

Nevertheless, I would like to know if there is a way to be be able to organise scripts which are all in a list on the left to have either categories or to display categories with script inthe meddle of the main page instead of the "Welcome to the Script Server.". Because it his quite complicated when you use a lot of scripts to find the proper ones and might cause running not the proper one.

Thanks by advance for your feedback, and again thanks a lot for this great work

**Comment by bugy** [comment]
Hi @ludolhoir did you try this option?
https://github.com/bugy/script-server/wiki/Script-config#group

**Comment by ludolhoir** [comment]
rhaaaaa sincerely sorry, did not see this option, honestly did not see it, thanks a lot, you can close this, it is not an issue just me.....

**Comment by bugy** [comment]
No worries :)
