### ISSUE TITLE
Temporary upload folder does not seem to be cleaned-up

### ISSUE THREAD

**Issue by tristanlatr** [bugy/script-server#683]
Hello @bugy, 

I'm running into "Internal Error" when executing any scripts, looking at the logs I see a "No space left on device". 

I believe that script-server should manage itself the temporary files so they get deleted after some or when there is no space left on the volume anymore.

Where are the temporary files located? so I can fix the issue for the short term.

Note that I'm using script-server version 1.16 currently, so it might already be fixed in the latest version.

Thanks

**Comment by bugy** [comment]
Hi @tristanlatr temp files should be cleaned up automatically. 
The files are located in temp folder of script server. Could you check how old are they? They should be removed after 7 days

**Comment by bugy** [comment]
It could be because of logs. Logs are not cleaned up automatically unfortunately
