### ISSUE TITLE
Setting up ldap authentication for multiple domains

### ISSUE THREAD

**Issue by bard7969** [bugy/script-server#685]
Hi,

I am fairly new with script server, need some help to sort some authentication concerns with this,
In our environment script server is running on unix and doing ldap authentication for domain1.

Now we have some users part of domain2 who needs access,  ldap server (lets says y.y.y.y) for domain 2 is different.

Is this possible to setup script server to authenticate user from both domains, where auth request from domain 1 user will be sent to x.x.x.x while for domain2 it should be sent to ldap server  y.y.y.y

This is current config :

 "auth": {
    "type": "ldap",
    "url": ["ldap://x.x.x.x"],
    "username_pattern": "domain1\\$username",
    "version": 3,
    "base_dn": "dc=domain1,dc=xxx,dc=xxx"
  },
  "access": {
        "allowed_users": [ "*", "@somedomain1ADgroup" ],
       
  }

NOTE : domain1 ldap cannot authenticate with domain 2 from AD perspective.

**Comment by bugy** [comment]
Hi @bard7969 unfortunately this is not possible :(

**Comment by bard7969** [comment]
Okay, thanks !
