### ISSUE TITLE
Script not available to execute for Admin User

### ISSUE THREAD

**Issue by TheSteveBennett** [bugy/script-server#686]
I have a script that can be executed by certain users but certain admin users can't see it from the main menu.  Where do I need to look to correct this?

**Comment by bugy** [comment]
Hi @TheSteveBennett, if you want admin users to be able to see (and execute) the script, you have to give them access explicitly.   You can use `@admin_users` group, to give an access to all admins at once

**Comment by TheSteveBennett** [comment]
> 

Do I have to edit the JSON file for the script or can I do that from the admin panel.  If I can do that from the admin panel then what would prevent me from doing so?

**Comment by bugy** [comment]
You can edit it from the admin panel. 
Of course, usually admins have extended access to scripts/server and can execute anything. In this case `access` settings is only to prevent unintended invocation of a script by an admin. E.g. if by a company policy, a script should be only executed by a Financial department. Then for admins, it will be obvious, that they shouldn't do it, since there is no access. 
At least, that was my way of thinking about it, when I implemented this restriction :)

**Comment by TheSteveBennett** [comment]
Thank you.  When I use the @admin_users and hit save, nothing happens and when I edit the json file directly the script disappears from the menu until I remove my changes.

From: Iaroslav Shepilov ***@***.***>
Sent: Thursday, July 27, 2023 4:39 PM
To: bugy/script-server ***@***.***>
Cc: Steve Bennett ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [bugy/script-server] Script not available to execute for Admin User (Issue #686)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

You can edit it from the admin panel.
Of course, usually admins have extended access to scripts/server and can execute anything. In this case access settings is only to prevent unintended invocation of a script by an admin. E.g. if by a company policy, a script should be only executed by a Financial department. Then for admins, it will be obvious, that they shouldn't do it, since there is no access.
At least, that was my way of thinking about it, when I implemented this restriction :)

-

**Comment by bugy** [comment]
> When I use the @admin_users and hit save, nothing happens

Could you try pressing "Enter" before pressing Save?

> when I edit the json file directly the script disappears from the menu until I remove my changes

Please check logs/server.log file. Most probably there is missing comma in json file or smth similar

**Comment by TheSteveBennett** [comment]
> > When I use the @admin_users and hit save, nothing happens
> 
> Could you try pressing "Enter" before pressing Save?
> 
> > when I edit the json file directly the script disappears from the menu until I remove my changes
> 
> Please check logs/server.log file. Most probably there is missing comma in json file or smth similar

**Comment by bugy** [comment]
I'm glad it worked :)
