### ISSUE TITLE
Script stops abruptly, but it continues to run in the backend

### ISSUE THREAD

**Issue by sbalakrishna** [bugy/script-server#698]
Hi,
  With the latest bits (1.19.0-master@0da869e), I am experiencing a strange issue that the scripts are exiting abruptly. Almost all the scripts are exiting abruptly.
But, if I check the history window, it is running in the backend.
This problem is not happening with the old versions (say 1.18.0-master@c86f076).

I have deployed the tool on different environments (on-prem, AWS), but seeing the same problem.

Please let me know if there is any solution for that.

Thanks in advance.
Regards,
Bala

**Comment by bugy** [comment]
Hi @sbalakrishna could you check the network tab in the browser and send me screenshots of the socket connection and all the messages inside the websocket

**Comment by sbalakrishna** [comment]
![image](https://github.com/bugy/script-server/assets/16516157/c94fd729-39aa-4e4b-9cdf-4b0b7d89263c)

**Comment by bugy** [comment]
Thank you! Could you also share details of the websocket? Those should be open, when you click on details.
Also, please send a screenshot for the abruptly interrupted connection

**Comment by sbalakrishna** [comment]
![image](https://github.com/bugy/script-server/assets/16516157/8e6456cb-ce27-41e1-8a11-7c146a42a093)

**Comment by sbalakrishna** [comment]
The attached screenshot provide the details for one of script. The same issue is happening with all the scripts.
As I mentioned earlier, I tried to install the tool on multiple different setups (Centos 7, 8, RHEL 7 and 8), but the issue still persists.

Please let me know if you need any additional info.

**Comment by sbalakrishna** [comment]
![image](https://github.com/bugy/script-server/assets/16516157/a0e17262-d1b7-43fc-be83-1fc1d06d9ffc)

**Comment by bugy** [comment]
Hi @sbalakrishna, just to double check: your script prints more output after this line:
![image](https://github.com/bugy/script-server/assets/1275813/c56cfcca-969c-4a54-860a-fb6145e373b6)
is it correct? Or you don't see this text in script server output window?

Unfortunately, I don't see anything suspicious in the browser logs. Could you create a minimal reproduction script for me, which I can use locally to reproduce the problem? I assume even having smth like:
```
echo 1
sleep 1
echo 2
sleep 1
echo 3
sleep 1
echo 4
sleep 1
```
Would fail for you. Or just some `ping google.com`

**Comment by sbalakrishna** [comment]
Closing the issue since it is not reproducible. 
Thanks for the support.
