### ISSUE TITLE
Login Screen - Image behind --login-header-background dialog possible?

### ISSUE THREAD

**Issue by ojtimsen** [bugy/script-server#703]
Hi,
is it possible, to have a Image behind the login dialog, if using i.e. htpasswd to manage the users / logins? I mean an image instead of the "background color".

I found to set the 

--script-header-background
--login-header-background

in the example theme.css definitions and I am wondering if an image "behind" the --login-header-background is also possible?

Thank you in advance! toj

**Comment by bugy** [comment]
Hi, you can add any custom style, but in this case you would need to define a custom style using normal css selectors (classes, ids). There is no variable for this case

**Comment by ojtimsen** [comment]
Thank you for the update, sadly I am not into css yet. Will check it out on the run.. :)
