### ISSUE TITLE
Build multiarch Docker image

### ISSUE THREAD

**Issue by vnghia** [bugy/script-server#714]
Right now the docker image on the `budy/script-server` only has `amd64` image. Can we also build `arm64` image ? I can send a PR if it makes sense to you.

**Comment by bugy** [comment]
Hi @vnghia yes, highly appreciated!

**Comment by bugy** [comment]
I don't know if travis has support for it, though

**Comment by vnghia** [comment]
No worry, there is an official guide here: https://www.docker.com/blog/multi-arch-build-what-about-travis/
