### ISSUE TITLE
How can i block the user input when running a script?

### ISSUE THREAD

**Issue by TheSirTigerr** [bugy/script-server#731]
How can i block the user input when running a script?

![image](https://github.com/bugy/script-server/assets/96537622/97ef6670-ef04-4cea-acec-fb892bd0a44f)

**Comment by bugy** [comment]
Hi, unfortunately it's not possible
https://github.com/bugy/script-server/issues/279

**Comment by TheSirTigerr** [comment]
Okay sad it would be perfect for the app
