### ISSUE TITLE
Add a second level/group in side panel to allow for more organized script grouping

### ISSUE THREAD

**Issue by CynicalWilson** [bugy/script-server#740]
I love the script-server, especially due to it's overall simplicity and usability.
One thing I'd love to see, or maybe somebody could provide me the modified code for the index.js file and I'll just pop that in, would be to not only be restricted to main groups --> list of scripts, but instead allow for main-group --> Sub - Group --> list of scripts.
That would enable a structure like :

### Main Group A: **Production**
- **Sub-Group 1**: **Client A** or script **topic group A**
--- Script 1  (associated with Main Group A and Sub-Group 1)
--- Script 2  (associated with Main Group A and Sub-Group 1)
...

- **Sub Group 2**: Client B or script topic group B
--- _**Script 1**_  (associated with Main Group A and Sub-Group 2)
--- **_Script 2_**  (associated with Main Group A and Sub-Group 2)
...

### Main-Group B: **Sandbox**
- **Sub-Group 1**: **Client A** or script **topic group A**
--- _**Script 1**_  (associated with Main Group B and Sub-Group 1)
--- **_Script 2_**  (associated with Main Group B and Sub-Group 1)
...

- **Sub Group 2**: Client B or script topic group B
--- _**Script 1**_  (associated with Main Group B and Sub-Group 2)
--- _**Script 2**_  (associated with Main Group B and Sub-Group 2)
...

Looks like this could, for somebody that's a bit more advanced than me in JavaScript, be rather easily be accomplished by some changes to the components ScriptsList , ScriptsListGroup, and ScriptsListItem.

**Comment by bugy** [comment]
Hi, thanks for reporting. The same request here: #608 
Regarding which classes should be changed, you are right.

**Comment by sbalakrishna** [comment]
Hi, any update on this request?

**Comment by bugy** [comment]
Hi @sbalakrishna unfortuantely not
