### ISSUE TITLE
Need to correct paths for proper deployment

### ISSUE THREAD

**Issue by zoulja** [bugy/script-server#76]
Installation guide is incomplete, probably need to provide requirements.txt will all dependencies and correct path logic 

**% git clone https://github.com/bugy/script-server**
...
**% tools/init.py**                            
Traceback (most recent call last):
  File "tools/init.py", line 8, in <module>
    import utils.file_utils as file_utils
ImportError: No module named 'utils'

**After 'pip3 install utils'** 

**% tools/init.py**                                    
Traceback (most recent call last):
  File "./init.py", line 8, in <module>
    import utils.file_utils as file_utils
ImportError: No module named 'utils.file_utils'

And so on
There are a lots of path related errors

**Comment by bugy** [comment]
Hi @zoulja, thank you for the report. I've improved the script, now it should be able to resolve internal dependencies based on current dir.
Coul you git poll and try again, please?

**Comment by zoulja** [comment]
Hello.
Not sure what I'm doing wrong - all utils.* imports still fail
% git clone https://github.com/bugy/script-server
% ./init.py
Traceback (most recent call last):
  File "./init.py", line 10, in <module>
    import utils.file_utils as file_utils
ImportError: No module named 'utils.file_utils'

Python 3.5.3@Ubuntu 17.04

**Comment by bugy** [comment]
Hi @zoulja, please run it from script-server folder (not tools), i.e. steps should be smth like:
1. git clone https://github.com/bugy/script-server
2. cd script-server
3. *tools*/init.py

**Comment by zoulja** [comment]
Nope
[script-server]
% tools/init.py                                                              
Traceback (most recent call last):
  File "tools/init.py", line 10, in <module>
    import utils.file_utils as file_utils
ImportError: No module named 'utils.file_utils'
                                                                  
[script-server/tools]
% ./init.py                                                                  
Traceback (most recent call last):
  File "./init.py", line 10, in <module>
    import utils.file_utils as file_utils
ImportError: No module named 'utils.file_utils'

**Comment by bugy** [comment]
Hi @zoulja, this time it looks like a conflict with global *utils* module, you had installed. I've fixed the issue and now internal utils module should be imported.
Please update from the git repo and try again please (don't forget to run it from script-server path, as  tools/init.py)

Thank you for your time and sorry for the inconvenience

**Comment by zoulja** [comment]
Ah, now I remember, I really installed utils module trying to solve this issue.
Not it's ok, thank you
