### ISSUE TITLE
Workflow consultation

### ISSUE THREAD

**Issue by 2531** [bugy/script-server#762]
Thank you very much for creating this excellent project, it is very useful to me. I have a question about the workflow of the tool. If I want to run a Python script, but the script imports a package that does not exist in the server environment, I currently have to log in to the server and use pip to install the package. Is there a more elegant way to handle this, such as uploading a requirements.txt file on the web management page, and then the server automatically adds the required dependency packages? Or have I missed some features? Thanks.

**Comment by bugy** [comment]
Hi @2531, unfortunately there is no such possibility in the tool. In the end, scripts are not necessary to be python scripts, so such management would be complicated.

**Comment by MNeill73** [comment]
This is such a weird edge case, running a script that you've seemingly
never run before to confirm the libraries required...

But, you could install pipreq, then set up a cron job that runs every few
minutes against your script directories, then action against any generated
requirements files that were generated.

**Comment by 2531** [comment]
Hi @bugy @MNeill73 ,thanks for your reply. I completed the script writing and testing on my local computer, and then uploaded it to the server, so there may be a situation where the server cannot find the package.
