### ISSUE TITLE
How to run a python script in a venv?

### ISSUE THREAD

**Issue by kakarata** [bugy/script-server#776]
Hi, I'm trying to run a python script with its own venv, but tried many ways and cannot achieve it.

Running something like this on script path: 
"source venv/bin/activate && python scripts/test.py"
but then I see server.log this:
 FileNotFoundError: [Errno 2] No such file or directory: 'source'

Even trying:
"venv/bin/python scripts/test.py"
it runs with that python, but not inside the venv (libreries installed, not loaded).

Any help to avoid creating a shell script as wrapper for each python script I have?
Thanks!

**Comment by kakarata** [comment]
I finally did it by adding "bash -c" to the Script path, as this:
bash -c "source venv/bin/activate && python scripts/test.py"

**Comment by bugy** [comment]
you could also provide a direct link to the python executable from the venv :) But whatever works for you

**Comment by kakarata** [comment]
Tried that, but didn't work.
"venv/bin/python scripts/test.py"
I'm trying to use python from venv specifically, but no load libreries.

Or you mean using "bash -c" but without invoking activate??? Will try it tomorrow.
BTW, great app!

Thx!
