### ISSUE TITLE
Large history makes the frontend slow

### ISSUE THREAD

**Issue by luhahn** [bugy/script-server#778]
Hi there,

i just had a case, where i had quite a large history of script executions. And i noticed, that every history entry causes a get request to executions/config/<idx>. When the history is growing this is causing some heavy performance issues.

I havent found a way to limit the history. Is there something im not seeing?

**Comment by bugy** [comment]
Hi @luhahn unfortunately there is no way :( Only to write less logs :sweat_smile:

**Comment by luhahn** [comment]
well, i ended up creating a cronjob within the container to limit the history to a certain number of files :D

**Comment by luhahn** [comment]
for anyone wondering, its not really the history itself, the problem was, in addition to the history. That i started the scripts via api request and did not run executions/cleanup/{id} after finishing
