### ISSUE TITLE
Fix issues, when script-server is run via reverse proxy (with location substitution)

### ISSUE THREAD

**Issue by bugy** [bugy/script-server#82]
In some places script server is using absulote urls. So using it with a reverse proxy is not possible at the moment. 

See PR #81

**Comment by bugy** [comment]
This feature is implemented long ago and seems to be working.
Added description to a wiki with example of proper proxy (nginx) config: https://github.com/bugy/script-server/wiki/Using-as-a-reverse-proxy

**Comment by muzzol** [comment]
sorry for resurfacing this issue but I need a proper example for apache as I'm facing same issue.

can you post a working example with apache proxypass?

**Comment by bugy** [comment]
Hi @muzzol,
Unfortunately I don't have an example (and experience) with apache at the moment.
I'll try to prepare it today.
