### ISSUE TITLE
Feature to have possibility to downloads each times the logs file after script execution

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#88]
It cool be cool to have a feature that allow the download of the log file after each execution of a script (in addition to the potentials output files).

**Comment by bugy** [comment]
Hi @csphoenix1, this shouldn't be hard to implement, but I'm not sure how to make it from UX perspective. Why do you/users want to download log file? You as admin always have access to these log files.
Probably we could add a configuration parameter, which will enable log download. 
Do you want to have it for every script? Or only for some of them?

**Comment by csphoenix1** [comment]
Hi @bugy ,
What mean "from UX perspective"?
From the administrator view, yes we could going to the logs directory, but from a non-admin user, or if we can't going to the logs directory because we launch the script from a computer which if not the same than the script-server app's host, I could be cool to have the possibility to download the logs file, instead of copy the output manualy (ie : with a script with lot of verbosity).

It could be for every scripts, but we could add a parameter in the runner conf to disable this feature (I mean the feature is on by default, but we can disabled it in the runner conf file).

**Comment by bugy** [comment]
Hi @csphoenix1, with "UX perspective" I meant how it will be most convenient for users and with keeping UI as simple as possible. 
To be honest I still do not understand why users would like to download log files. Will they extract some important information from these files later? 

For admins there is a pending more global feature - admin panel #83, with possibility to view logs via web interface as well.

**Comment by csphoenix1** [comment]
Hi @bugy,
For example, I have some scripts which install some packages remotely on my servers.
And sometimes, the installation failed :(

So : I have to copy the text and paste it in a file, then save it to analyse it later.

Finaly, it could be more easily for me if I've just to click on "Download Log File" at the end of the script by using the functions which already exist :)

However, I understand in #83 there will be an administrative panel, but with this request, we could just download it without going to the administrative panel and without be admin :)

**Comment by bugy** [comment]
Hi @csphoenix1, to be honest, I'd prefer _not_ to add this feature - to keep user interface as simple as possible. In all the cases I met, non-admin* users didn't care about logs, they even don't read it on a screen sometimes.
For admin* users, all script log files are stored in server folder and can be accessed anytime later. I agree that it's less convenient, but hopefully abnormal cases don't happen so often. The main idea, that admin* and normal users are different people usually.
If you want, I can add "save log" feature in your fork :)

* with _admin_ I mean the people, who are supposed to fix scripts/configs and do other maintenance work.
