### ISSUE TITLE
Feature to add the basic auth username in the logs

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#89]
In order to have an authentication system based on the auth basic I have implemented a reverse Proxy (with NGinx) by authenticate the users and it could be interessant to have the possibility to add the basic auth username in the logs.

**Comment by bugy** [comment]
Hi @csphoenix1, good idea! This can be used instead of IP/PC Name, correct? Do this parameters come as http headers?
And how do users specify their credentials? I don't have much experience with reverse proxies

**Comment by csphoenix1** [comment]
Hi @bugy :)
The username field could be come in addition with the historical fields (ie : IP and PC Name which are very useful informations to identity the person who have launched the script).
The user specify their credentials via a popup (https://www.ntu.edu.sg/home/ehchua/programming/webprogramming/images/HTTP_BasicAuthLogin.png).
And the username parameter come in the http header, yes (I not very sure but I think ^^).

**Comment by bugy** [comment]
Hi @csphoenix1, I added this feature. Now if basic auth username is available, it will be shown as an audit name (instead of hostname/ip)
In addition, when starting a script, all available user information is logged (ip, hostname, basic auth username, ldap username)

Could you test my change on your setup please? Does it work properly?

**Comment by csphoenix1** [comment]
Hi @bugy ,
It's been a long time ! :)
So I test this feature, and it work perfectly! :)

One more thing, do you think it if it could be possible to customize the log filenames?
I would like to have the possibility to customize the timestamp "YYYYDDMM-HHmmSS" instead of "YYDDMM-HHmmSS" and also have the possibility to keep the hostname/ip with also the username if available?

Thank you, and as usual: congratulation for your work! :)

**Comment by bugy** [comment]
Hi @csphoenix1, 
Just out of curiosity - why do you need a full year in the log name?

And I didn't get your proposal about hostname/ip. Do you want to see it in the filename? It will be too long.
All this information is already available in the server.log file

**Comment by csphoenix1** [comment]
@bugy ,
I hope that my future grandchildren will continue to use your super script-server program in the year 2119. So with 4 digits, we could make the difference between years 2000 and years 2100 ^^
More seriously, it's because I like the year be on 4 digits. It's psychological ^^.

About hostname/ip and informations in the filename, I love informations and details, so I was thinking a feature to have possibility to generate the log filename as we want through the config file.
We could imagine a variable named "log_syntaxe" and the user can customize the value, example:

`{
"log_syntaxe": "$SCRIPT_NAME$-$HOSTNAME$-$IP$-$USERNAME$-$DATE$"
}`

Like that, each one of us can customise the log filename as we want and add the hostname and the IP, or not :)

**Comment by shinebayar-g** [comment]
Is this still working? I don't see any mention of it on https://github.com/bugy/script-server/wiki/Authentication

**Comment by bugy** [comment]
It's in master branch (no-released yet). I'll add documentation after release (coming in Jan-Feb)

**Comment by bugy** [comment]
Hi, should work, please check: https://github.com/bugy/script-server/wiki/Server-configuration#logging
