### ISSUE TITLE
Custom the site title from the server configuration file

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#90]
Actually the website title in hard-coded in the index.html page.
Is possible to add a feature to custom it in the server configuration file?

Thank's!

**Comment by bugy** [comment]
Hi @csphoenix1, I've made a change (it was quite simple). Now you can set it in server conf.json file via "title" parameter. This change requires server restart
At the moment, the page will always open with default title (Script server), but in a second it is replaced with a custom title. Hopefully it's not a large problem

**Comment by csphoenix1** [comment]
Oh it's perfect thank you :) I'll analyse the modifications and maybe, I could implement some new features like that by myself and without disturb you :)

**Comment by bugy** [comment]
Hi @csphoenix1, does the change work for you? Can I close it?

**Comment by csphoenix1** [comment]
Hi @bugy,
It work perfectly :) Thank you.
You can close this involved.
