### ISSUE TITLE
UI responsive fix

### ISSUE THREAD

**Issue by pollier** [bugy/script-server#93]
Hello,
Would it be possible to make arguments drop down list responsive to the size of the values ?
Actually there is a horizontal scrollbar which is not very usable in some case.
![screen shot 2018-02-14 at 12 26 42](https://user-images.githubusercontent.com/18324962/36202022-6a31916e-1182-11e8-8155-c1e0bc9c59e8.png)

Thank for your great work so far :)

**Comment by bugy** [comment]
Hi @pollier, thank you for the ticket and feedback!
I think this improvement should be possible. I'll try to fix it this week

**Comment by bugy** [comment]
Hi @pollier, I made a small fix for it, now the width should be able to extend up to 50% of a screen.

But I have a question regarding your screenshot: do you always have so narrow dropdows? On your screenshot, "Choose your option" is split into 2 lines, however on my machines it's always a single line (so the whole combobox is a bit wider).
Which browser do you use? Or do you have a retina display?

**Comment by pollier** [comment]
Chrome on macOS High Sierra 10.13.3
Version 64.0.3282.167 (Official Build) (64-bit)

1440 x 900 pixels
24 bit

BROWSER WINDOW SIZE
1440 x 825 pixels
"Do Not Track" is Enabled
ABP Enabled

Yes all dropdown are the same width

**Comment by bugy** [comment]
Hi @pollier, thank you for the info. I've checked on Chrome in Mac OS and can see the same problem (all the fields are narrower than should be). Actually even Safari seems to render them in proper width.

I'll change fields layout to be fixed grid, so it will be independent on Browser width for different fields.

Have you checked my fix for the dropdown already?

**Comment by pollier** [comment]
Perfectly fixed on my side 💯 
Thanks

**Comment by bugy** [comment]
@pollier, cool, thanks for the feedback!

I'll leave the ticket open - going to add support for even longer values.

**Comment by bugy** [comment]
Even longer values was too hard to support, so for now they are just ellipsised, until anyone needs them.
